### ISSUE TITLE
Save Favorite Broadcaster/Save to Broadcaster folder

### ISSUE THREAD

**Issue by joelang1699** [Franiac/TwitchLeecher#113]
Hello

Wonderful piece of software here!

Could you add an option to save a list of favorite broadcasters and also when saving it auto generates a folder specific to the broadcaster

**Comment by Franiac** [comment]
Cool idea. I like 😄

**Comment by obs-x** [comment]
A "Save favorite broadcaster seems to be what I want too, so I'm posting here.

OP mentions a "list", which is more than 1. 10 should be perfectly fine (enough), but the very simple way I imagined it first does not permit for a user-chosen amount - so maybe 5?

The way I thought of it first was basically like this: https://vgy.me/7NgXRn.png - Doing it this way there's no fuss about adding more buttons to the top/resizing them so an addition fits neatly etc, and the Search tab is displayed by default on opening so the buttons are there anyway vs having to go to a different pane between search and favorites etc. Clicking one of the buttons would simply launch a channel search for the fav.

Maybe there's a better, cleaner way to do this (the UI of this is gorgeous). I had just imagined it like this because it seems really simple/easy to add. Cheers!

**Comment by Franiac** [comment]
Nice attempt... don't like it :D

Here's mine:

In the preferences you will be able to click some +/- buttons next to the "channel name" textbox. This way you can add unlimited favourite streamers to a list. The Textbox will be changed to a dropdownbox. This way you are able to type in the control like it was and in addition you can choose one of your favourite streamers.

The same applies to the textbox on the search panel. Just click the dropdown, choose a favourite streamer and it "search".

Pros:
- Not many additional controls
- Unlimited favourites
- Current behaviour isn't changed
- Ability to choose a favourite streamer as the "search on application startup" thingy.

Cons:
- 3
- 2
- None
