### ISSUE TITLE
not saving to network share

### ISSUE THREAD

**Issue by NightRider0** [Franiac/TwitchLeecher#118]
Hi,

When i try downloading to samba share on freenas server it says i do not have write permissions when i click download. yet when i add, delete, modify existing files and folders i get no permission issues

**Comment by Franiac** [comment]
investigating...

**Comment by Franiac** [comment]
How do you address this path? is it a network share with a drive letter or do you address it via an UNC path like "\\server\path\to\folder"?

**Comment by Franiac** [comment]
I think I have the solution. I mistakenly check the given folder for windows FileSystemRight "Write" instead of "WriteData + Delete". Big difference actually, because "Write" also includes the right to change access permissions to the folder (that you usually don't have on network shares).

So I think that's it. You'll see if it works after the next update of TL (incoming this week).

If not, let me know!

**Comment by Franiac** [comment]
🎉

**Comment by NightRider0** [comment]
Works great on new version! thanks!
