### ISSUE TITLE
Adding unit tests

### ISSUE THREAD

**Issue by madmatt** [Franiac/TwitchLeecher#123]
Hey Dominik,

I wanted to play around with unit testing in C# a bit, and noticed you didn't have any tests yet so thought I could contribute a bit at the same time. Would you be interested in accepting these?

[The first test is here](https://github.com/madmatt/TwitchLeecher/compare/master...pulls/add-first-test) (based on the `v1.3.7` tag as `master` appears to be broken at the moment).

This is using MSTest because I'm not familiar with any of these. Would NUnit be better? I'm happy to submit a pull request but figured it's better to get started with the right framework before sending the PR in.

If you're interested, I'd be happy to write some more tests too. I'm not aware of any decent C# continuous integration tools, but if you have a preferred one I can try setting that up too.

Thanks!

**Comment by Franiac** [comment]
Hi,

thanks a lot for your will to contribute. First I have to admit that I do not have any developer guide set up since I didn't expect anyone wanting to contribute in a bigger scale to this rather small and unknown project.

Before you fully get your head into this, we should definitely communicate about the project structure, tooling and some code related stuff (formatting etc.).

The master branch is definitely not broken but has recently been updated to Visual Studio 2017 (1.3.7 is 2015). Maybe that's why you have problems with it.

In addition to that I am about to change a lot of things in TL for a 1.4 release (new download manager and video processing service). This will break a lot of service tests so I strongly recommend you to NOT start with this project until 1.4 is released. The branch is already there but not runnable at the moment due to my lastes preparations.

Regarding the test framework: Don't use MSTest, it's shit, period. I don't know anyone serious using it because it has so many flaws and quirks. NUnit is the way to go. It is widely accepted and used in many large scale software projects.

So, I'm really happy that you want to work on the test part because this was just not done by me because of the lack of time and the fact that TL is definitely a project that I can handle without a large amount of tests. But I recommend you to wait until 1.4 is released because otherwise you will implement many tests twice in the end and that is not efficient.

**Comment by Franiac** [comment]
@madmatt I don't see this happening anytime soon, unfortunately. I am simply too busy with other stuff to take care of it. Just want to be honest. Wouldn't be much better if we keep this issue open for the next 3 years without any action.

**Comment by madmatt** [comment]
No worries :)
