### ISSUE TITLE
"Video Quality" default not working

### ISSUE THREAD

**Issue by xXSnowyXx** [Franiac/TwitchLeecher#130]
This worked in previous version but seems to have broken recently. Have tried defaulting settings and changing again but it makes no difference. After clicking download the quality is always set to Source ignoring whatever is set in the Download settings.

**Comment by Franiac** [comment]
I think I saw this, too. Twitch changed the API again and resolutions are being handled differently now. I have to investigate.

**Comment by xXSnowyXx** [comment]
Looks like it will only require changing the list in the settings from Low, Medium, etc to 360p30, 480p30, etc. After editing the settings file manually it's giving the correct defaults again.

**Comment by Franiac** [comment]
There was a time when Twitch actually used both variations. If I change TL to the new pattern, maybe the old one for old VODs won't work anymore. This needs in-depth testing.

**Comment by Franiac** [comment]
After investigation, the selection of the default quality is not possible the way it was before. Here are a couple of different JSON segments from various streamers:

```json
"fps": {
  "audio_only": 0,
  "chunked": 29.907692307692308
},
"resolutions": {
  "chunked": "1280x720"
}
```
```json
"fps": {
  "audio_only": 0,
  "chunked": 29.982565551700798,
  "high": 22.01837187162655,
  "low": 19.982320916405406,
  "medium": 22.01837187162655
},
"resolutions": {
  "chunked": "852x480",
  "high": "852x480",
  "low": "400x226",
  "medium": "638x360"
}
```
```json
"fps": {
  "160p30": 30,
  "360p30": 30,
  "480p30": 26.25,
  "720p30": 26.25,
  "audio_only": 0,
  "chunked": 30
},
"resolutions": {
  "160p30": "284x160",
  "360p30": "640x360",
  "480p30": "852x480",
  "720p30": "1280x720",
  "chunked": "1280x720"
}
```
```json
"fps": {
  "160p30": 30,
  "360p30": 30,
  "480p30": 30,
  "720p30": 30,
  "720p60": 60,
  "audio_only": 0,
  "chunked": 60
},
"resolutions": {
  "160p30": "284x160",
  "360p30": "640x360",
  "480p30": "852x480",
  "720p30": "1280x720",
  "720p60": "1280x720",
  "chunked": "1280x720"
}
```
So there is not only a difference in how the resolution is named, but also the amount of entries. In addition to that Twitch has started to provide the same resolution in different fps settings (see last JSON example with 720p30 and 720p60).

So it is not possible anymore to select a default resolution just by setting one of 5 quality options in a dropdownlist. And even if there is a default set, does not mean that this selected quality is there.

I will probably ditch this option completely and default to source quality. A new GUI layout for multiple downloads will compensate for that in 1.4.0

**Comment by xXSnowyXx** [comment]
You could always leave the drop down how it is and default to the nearest available but I understand if that'd be a pain to write around. I like having the feature but I'll get over it if it goes away.

**Comment by Franiac** [comment]
Yea, but what should I do if you select "High" and there ist 720p30 and 720p60... basically you don't know what you'll get in the end. And the latter is bullshit for the user. A setting where the user chooses what he wants and cannot be sure if he gets it... that's not how I want to program software :)

But nevertheless I am currently working on this so that TL sorts the different resolutions in the right order and so on. That's also not happening atm for all permutations.

But in the end it is just bullshit what Twitch did there. This resolution and fps JSON is just stupidly set up. One of the worst API I've ever seen to be honest. Why not something like this and be consistent with it:

```json
qualities: [
  {
    "identifier": "source",
    "resolution": "1920x1080",
    "fps": 30
  },
  {
    "identifier": "high",
    "resolution": "1280x720",
    "fps": 30
  }
]
```
An API that delivers 4 different styles of data for the exact same thing is just a case for the recycle bin.

**Comment by xXSnowyXx** [comment]
Maybe a "Prefer 60fps" tick box?

**Comment by Franiac** [comment]
And what if "high" is not 720p? The above JSON examples are only a few. There is no dependency between qualities like "source" or "high" and actual resolutions. So "high" can be 720p, but is could also only be 480p depending on the stream.
Now if I think like a user, I would expect the same quality of a downloaded VOD whenever I select "high". And sure I could opt for a checkbox for FPS, but again... 30? 45? 48? 60? What do I get in the end? I don't like this approach and don't want to confuse the users. If I did this, it would take 2 days at most until the first issues get opened because of it. SO the longer I think about it, the less I want to mess around with it and try to fix what Twitch already broke. I can only be as good as the data I get... that sucks sometimes.

**Comment by xXSnowyXx** [comment]
Fair enough

**Comment by Franiac** [comment]
🎉
