### ISSUE TITLE
Twitch Leecher wont install

### ISSUE THREAD

**Issue by PoppySilver** [Franiac/TwitchLeecher#131]
I've been tryna install your program and when it starts installing the whole installer breaks and i have to go into task manager to close it. It gets past everything until it starts actually installing. I've tried version 1.3.8 and 1.3.7. I'm running windows 7 and I am using the (x64) version. :(

**Comment by Franiac** [comment]
Are you familiar with cmd.exe (the windows command line)? If so, you can start the installer with -l "logfile.txt" in order to get a logfile of the installation process.

Example:

1. copy your installer to drive D:\ or any other drive
2. open cmd.exe
3. change drive to D:\
4. start the installer with: TwitchLeecher_1.3.8_x64.exe -l "logfile.txt"
5. click through the installer and let it fail

either one or two logfiles will be created during this process. send em over please :)

**Comment by Franiac** [comment]
Closed because stale
