### ISSUE TITLE
Option to retry infinite times

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#132]
As I understand a new download manager is a work-intensive request, can a stopgap solution for 504 Gateway timeouts be implemented so it can optionally retry an infinite number of times? A data cap makes download failures significant.
FYI, I haven't noticed download problems with other sites, so this may be a problem with Twitch.
(Moved as this is not really part of issue 46)

**Comment by Franiac** [comment]
You are right that this is indeed a problem with the kinda unstable Twitch servers or their loadbalancing. I don't know the real reason for that but cannot do anything in TL about it.
I would have to implement preferences for the retry time and the wait time (how log TL waits between an attempt). This is also a significant change and given the fact that I am already working on the new DL manager I really don't want to start another construction site to be honest. I have so little freetime for TL right now so that I really want to invest it into the DL manager if possible. I'll take a look at the work needed to implement this bypass but no guarantees....

**Comment by tezJR** [comment]
I appreciate your adding it as Possible. Would a Retry button (like you have for Cancelled) and a sound when an Error occurs be easier?

FYI, I had a 504 error once with a 15 second low quality clip too, so download size doesn't matter.

**Comment by Franiac** [comment]
I will introduce this into TL 1.4.0 when the new download manager is done. ATM it is not worth doing considering the amount of time the implementation and testing needs.
