### ISSUE TITLE
Support for direct download to SMB shares

### ISSUE THREAD

**Issue by NightlyDaze** [Franiac/TwitchLeecher#142]
Twitch Leecher 1.3.8

"You do not have permissions..." shows up when I try to set my Download or Temp folder as a Network drive running in my Synology. I ran as admin, checked all privileges on Synology OS, and it still won't cooperate. All accounts on my network have permission to do anything on the drive itself, as long as they have the password to the Synology Login. I'm trying to set up Twitch Leecher 1.3.8 on my NUC linked to my Synology drive; the NUC never has any problems writing to the drive since I connected it as a network drive. Am I missing something? I feel like I'm overlooking something important.

Thanks

**Comment by Franiac** [comment]
How is that drive connected to the NUC? Please provide the download folder and temporary download folder that you specified in TL.

Do you use an UNC path like "\\synology-device\path\to\directory\" or have you mounted the synology drive as a network drive in windows like "L:\path\to\directory\"?

**Comment by NightlyDaze** [comment]
The drive itself is connected over the network. Whether I try to connect it by a path like \\Server\Folder or Z:\Folder, neither one works. I'm trying to run TL on a user that has complete Read/Write access to the drive and folders, so I'm not sure why it says I don't.

**Comment by Franiac** [comment]
Be aware that read/write is not sufficient. TL also needs to delete files and folders in oder to clean up the temporary download folder. Maybe that is your issue? Because we already had an issue #118 where someone successfully saved downloads on a NAS device. Please check that again and let me know.

**Comment by NightlyDaze** [comment]
Oh yeah, I read through the other thread before but nothing there seemed to help the issue. I had however already allowed the permissions to delete/read/write, but still nothing :/

![untitled](https://cloud.githubusercontent.com/assets/20627159/26041560/ddee2eb0-38fb-11e7-94a3-31a5593f06d0.png)

**Comment by Franiac** [comment]
Anther question: Did you need to provide a username and password when you first mounted the drive Z:\ in Windows? I really don't understand what makes your drive so special opposed to all other network drives. I have tested multiple NAS systems (unfortunately I don't have a Synology) and TL works flawlessly.

Because it is pretty obvious what TL checks:

```C#
foreach (FileSystemAccessRule rule in rules)
{
    if (rule.FileSystemRights.HasFlag(FileSystemRights.WriteData & FileSystemRights.Delete))
    {
        if (userIdentity.User == rule.IdentityReference || userIdentity.Groups.Any(g => g == rule.IdentityReference))
        {
            return true;
        }
    }
}
```
If I have time later, I could write a little exe file you can run that logs the available access-rules of your Z:\ drive. Would you run this tool and send me over the results?

**Comment by NightlyDaze** [comment]
Yeah, I believe I have to enter the username and password each time I turn in the PC. But after that, every other program can write/read/delete on the network drive just fine. It's just TL that's giving me trouble. But yeah, I'll send you the logs if you make that exe.

**Comment by Franiac** [comment]
Ok, that makes sense then. TL checks for permissions for the current user that runs TL (in your case the user you login to Windows). Other tools probably don't check for permissions and just try to write or do whatever they want. But lately I had some users reporting errors because of insufficient write permissions so I decided to rather check them beforehand.

I wrote a little tool to see what's going on with your Z:\ drive:

1. Download http://www.fakesmilerevolution.com/files/TestPermissions.zip
2. Start exe and type in your folder (Z:\path\to\folder)
3. Click "Check"
4. Post the log here

Now here's the deal: The tool responds with how TL would react but in addition to that I have just implemented another method to check permissions. I hope the new implementation gets it right. We'll see...

**Comment by NightlyDaze** [comment]
Alrighty, thank you. I just tried the Permission checker. For "Z:\TwitchDownloads" it reads: 

```
Twitch Leecher would have permission? => False

New implementation says:

None
```

For UNC path "\\\Server\Drive\TwitchDownloads\" it reads the same thing:

```
Twitch Leecher would have permission? => False

New implementation says:

None
```

**Comment by Franiac** [comment]
I read the Synology manual and it makes sense... those are smb shares. Basically it is not really a windows share but a remote share with a specified user. Well, yea, so far TL does not support that obviously. But it is not a bug but a feature which needs implementation and testing. but at the moment I have to prioritize on some other features du to my lack of time I can invest into TL.

**Comment by NightlyDaze** [comment]
Ok, that makes sense. I can live with downloading to my main drive and moving it for now. Thanks for all your help!

**Comment by Franiac** [comment]
Update: There is no way (or I cannot find one) to detect if a network share is a SMB share or not. Therefor the only possible solution to this issue would be to disable permission checks for network shares altogether. IF a local directory is chosen, it would still warn the user if he has no permissions (e.g. the Windows directory or something like that).

**Comment by NightlyDaze** [comment]
That's fine man, I've found a way to streamline transferring it across my network, from my server to Synology.
