### ISSUE TITLE
temporary folder on samba share slowdown

### ISSUE THREAD

**Issue by theultramage** [Franiac/TwitchLeecher#144]
While downloading a 7-hour 160p stream to a networked share, I noticed that eventually the download will slow down to a trickle and smbd will max out one cpu core. Cancelling the download will let smbd recover, after all the temporary files get deleted.

After seeing that the temporary folder contained many thousands of small files, I'm assuming that TwitchLeecher does some inefficient activity when downloading each chunk. Something like listing all the files in the directory, or finding the highest chunk id by testing the existence of all previous files one by one. I don't see anything obvious in ProcMon when saving to a local disk, though. I did notice that when doing the processing step from a local disk to a network share, the data is written inefficiently, in many small chunks (100-1000 bytes), creating a processing speed bottleneck of 1MB/s.

**Comment by Franiac** [comment]
A 7hr stream usually has about 11000 parts or more, you can see the number in the download log. Why would the smbd process max out a CPU when TL is programmed inefficiently? That makes no sense and is a very bold claim. Maybe TL is too efficient for smbd... just an assumption.
First of, you won't find any of the described fail-patterns in my applications. The download process is a very simple but efficient parallel download pattern via TPL with 10 open connections. Therefor 10 files get written at a time concurrently. I don't know what machine you are working on, but it very well seems like smb simply cannot handle the I/O.

Here you go... you don't need any tools to get your head around that:

```C#
Parallel.ForEach(parts, new ParallelOptions() { MaxDegreeOfParallelism = maxConnectionCount - 1 }, (part, loopState) =>
{
	int retryCounter = 0;

	bool success = false;

	do
	{
		try
		{
			using (WebClient downloadClient = new WebClient())
			{
				byte[] bytes = downloadClient.DownloadData(part.DownloadUrl);

				Interlocked.Increment(ref completedPartDownloads);

				FileSystem.DeleteFile(part.LocalFile);

				File.WriteAllBytes(part.LocalFile, bytes);

				long completed = Interlocked.Read(ref completedPartDownloads);

				setProgress((int)(completedPartDownloads * 100 / partsCount));

				success = true;
			}
		}
		catch (WebException ex)
		{
			if (retryCounter < DOWNLOAD_RETRIES)
			{
				retryCounter++;
				log(Environment.NewLine + Environment.NewLine + "Downloading file '" + part.DownloadUrl + "' failed! Trying again in " + DOWNLOAD_RETRY_TIME + "s");
				log(Environment.NewLine + ex.ToString());
				Thread.Sleep(DOWNLOAD_RETRY_TIME * 1000);
			}
			else
			{
				throw new ApplicationException("Could not download file '" + part.DownloadUrl + "' after " + DOWNLOAD_RETRIES + " retries!");
			}
		}
	}
	while (!success);

	if (cancellationToken.IsCancellationRequested)
	{
		loopState.Stop();
	}
});
```

**Comment by theultramage** [comment]
Here's the first 30% of the download. I/O overload is not an issue, it very quickly drops down to maybe 500kB/s average. The client seems to be requesting some cpu-intensive activity, and things get worse over time. My initial guess is ```FileSystem.DeleteFile(part.LocalFile);```. I can see the Disposition: Open / Error: object name not found messages going back and forth. This would cause a problem if for some reason, file lookups by name in a large directory were expensive. No idea why they would be, though.
![untitled](https://cloud.githubusercontent.com/assets/1738190/26172722/abbb9e1e-3b49-11e7-86d7-d7485da0fe43.png)

**Comment by Franiac** [comment]
FileSystem.DeleteFile(part.LocalFile) only deletes the file to be downloaded if it already exists. That is just a simple check with no consequences. If the file does not exist, the method does exactly nothing (which is 100% the case because the directory is empty at the beginning of the download). It is just a safety measure.

It is a false statement that file-exist checks take longer in directories with a larger amount of files. That is just wrong. The file to be found is always specified with the full path and therefor the filesystem can easily check the existence without caring about any other files in the same directory.

For fun I have just tested a 10 year old USB HDD with 5400rpm. It is able to do 1 million file-exists checks in a directory with 30000 files in less than 570ms. So I doubt we have a problem here and that was expected.

You are assuming and guessing a lot regarding TL. There is absolutely no clue that TL has anything to do with your given problem.

**Comment by theultramage** [comment]
Note that everything is going through the samba software layer, which involve mount points, acl emulation and god knows what else. I have reproduced the problem with a simple fopen() loop. Just adding a file to a directory takes longer the more files there already are. I'll go see if anything can be done on the smb side.

**Comment by Franiac** [comment]
Ok, but I cannot fix shitty Samba implementations/emulations within a .NET application that uses standard/well designed/approved .NET runtime/Win32 API calls to do its job. You cannot complain that a Ferrari (TL) doesn't go 200mph in the middle of Sahara desert (Samba).

Resolved -> Closed

**Comment by theultramage** [comment]
Well, yea... Some software tries to mitigate nonetheless, for example by sharding their data directory. Svn server by default splits revisions by 1000's into subdirectories, and the client splits objects by the first 2 characters of the hash into 256 subdirectories. Of course, that shouldn't be needed on a normal filesystem.

**Comment by Franiac** [comment]
I disagree. Basically you are asking me to implement TL less efficient for 25000 users because a single user has a problem with a SMB server. I agree that software should mitigate small bugs that can be worked around quite easily. But I don't see why I should fix a major flaw of another tool.

Obviously the source of this issue is your SMB server failing at storing files in large directories and that's where it should be fixed. Because a file server failing at storing files... I mean... really? I also don't use a mail program that cannot send mails, right?

You definitely should take this issue and head over to the samba project and post it there. You even have a reproducable pattern (fopen() loop). Because every tool that stores a large amount of files would fail, not only TL. Software issues need to be fixed where they occure, not where they have an effect (biggest rule of software development in my opinion). It cannot be a solution that every tool that possibly stores files on SMB shares implements directory splitting. That is just stupid.

And just saying: I have an Ubuntu Server here running with a SMB server and TL is running super smoothly, reacting nearly as fast as the local windows file system. No problems with large directories whatsoever. So again, it is even unsure if SMB is the problem or maybe just the configuration. I don't know SMB very well to be honest, so I cannot tell. And don't ask me how I host that share... I just fiddled around with a Samba GUI and it worked...
