### ISSUE TITLE
Problems with Downloading Complete Video

### ISSUE THREAD

**Issue by RickardNi** [Franiac/TwitchLeecher#162]
Couldn't find any known issues, maybe I'm missing something, but I'm trying to download the following video:
https://www.twitch.tv/videos/47968582

The video is recognized correctly in the application, and the length is showing (01:54:30), which is correct. However, downloading it results in a 381 MB video file with a length of 26:55 instead. Most of the time. Sometimes it gets shorter than that, and in all cases it says "100%" in the applications.

I have never had this problem before, and downloaded plenty of other videos in older versions, and a few with the latest release. Is this a bug, or is something funamentally broken with this specific video? I can watch the entire video in the browser with Twitch's video player without any problems.

**Comment by Franiac** [comment]
There are plenty of issues regarding this but most of them with a misleading title. The behavior you have there occures if the source material has a major hickup at a certain point. Web players are much more error-prone than ffmpeg. So if there is a big hickup like a 1s lag or many dropped frames and so on, the browser might just skip that part whereas ffmpeg fails completely. The hickup in the source material does not necessarily have to be visually recognizable. Can be just a wrong byte at the wrong place and ffmpeg says "screw you". There is absolutely nothing I can do because if ffmpeg does not want to merge correctly, TL cannot do anything because it relies on ffmpeg.

**Comment by RickardNi** [comment]
Thanks for the quick response.

Is the problem that it won't be able to download all split segments because of the hickup, or that it can't merge all the parts together? If the latter, would it be possible to download all segments to a folder with an option parameter perhaps?

**Comment by Franiac** [comment]
TL is not able to leave the files on the HDD, because that is the main thing TL tries to hide from the user. What you could do is to crop the video in 2 parts. If you know the problem is at 26:55 you can download from 00:00 to 26:50, and a second time from 27:00 till the end. Then you have to handle only 2 files and could merge them together in a video software.

**Comment by RickardNi** [comment]
I'll try that, thanks for the informative answers!
