### ISSUE TITLE
External ffmpeg usage

### ISSUE THREAD

**Issue by wallrik** [Franiac/TwitchLeecher#163]
Hi there.

Any chance that you could add a configuration option to use my own ffmpeg.exe in a different folder?
And with that, offer a lightweight download without ffmpeg included?

I use several software that make use of ffmpeg so I have different versions scattered around my PC everywhere, but I always keep an updated version in a specific place.

So with [streamlink](https://github.com/streamlink/streamlink) I just point it towards that location, for example.

I would love to do the same with TL. Thank you :)

Right now I delete ffmpeg_x64.exe and create a symbolic link instead, which works, but it's extra work.

**Comment by Franiac** [comment]
What is the purpose of using a different ffmpeg version? TL is tested with the bundled version every time it gets released. What is the advantage of using a older/newer one? I don't see any good reason why you would want to do that.

I don't want to support this since it opens up TL for errors regarding ffmpeg that are then being posted here on GitHub again. There are ffmpeg versions that don't work probably and I don't want to tell every second guy "no, you are using an unsupported ffmpeg version...".

In addition to that it is such a speciality not many users would actually take advantage of because they simply don't want to care about ffmpeg. Users want to download VODs easily without thinking about ffmpeg versions. That's the main purpose of TL. My goal is to make TL less complicated, not more.
