### ISSUE TITLE
TwitchLeecher on Linux Debian

### ISSUE THREAD

**Issue by wiiarctus** [Franiac/TwitchLeecher#172]
Hi, I wanted to ask if it is possible (or could be made possible) to use TwitchLeecher on Debian so that a download would be even faster (on a virtual server of course^^) and stuff..?^^

**Comment by Franiac** [comment]
I don't see what the OS has to do with download speed :)

The answer is: No, sorry. I am not interested in dealing with hundreds of different package formats for hundreds of scattered Linux derivatives that are not able commit to a reasonable size of package formats and call that even "freedom". I simply not into it and changing TL in order to run on Linux is not worth the effort for the 3 people using it then ;)

**Comment by GenesisB** [comment]
@wiiarctus you can use youtube-dl on linux. It's a superior piece of software for the 3 people that use Linux.

**Comment by teocci** [comment]
https://github.com/teocci/TwitchLeecher  I created this project for the people that uses mac or linux.
