### ISSUE TITLE
Show already downloaded videos in Search

### ISSUE THREAD

**Issue by EpicLPer** [Franiac/TwitchLeecher#182]
Simple little feature request: Show already downloaded videos marked in the search list directly so we won't have to click on Download on every single video to check if the file is already there or not.

**Comment by Franiac** [comment]
This is anything but simple. TL does not track what you have already downloaded, so it cannot show any hints. As soon as you remove the completed download from the list, TL does not have any information about that download (which also happens when you close TL). You can specify any filename by yourself, so there is no relation between a Twitch video and a file on your disk. In addition to that, you can download multiple parts (cropping) of the same video.

Conclusion: This feature is not possible without a download history. I think it is not worth the effort. In the end it is a little gimmick that eats up days (if not weeks) of coding.

**Comment by EpicLPer** [comment]
A possible solution is to keep a database of what files you have downloaded with their filenames you gave them, if the filename isn't in the folder anymore then mark it as "Not Downloaded" regardless of anything else.

**Comment by Franiac** [comment]
Yes, that is a possible solution and suddenly we talk about introducing a database system into TL just because of a little gimmick. Don't get me wrong but I don't see a good cost-benefit ratio here.

**Comment by EpicLPer** [comment]
To archive whole channels at once. Or introduce a "Download All" button for search queues, would also help since it'll ignore downloads with the same name anyways.
