### ISSUE TITLE
Optional error & success notifications

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#184]
I request this enhancement as sometimes I expect a large download to be done but find an error, or I'm waiting for a download and would appreciate a notification so I don't have to keep checking. I'd like it to persist so it stays until I move my mouse, in case I'm afk. Would a system tray notification work?

**Comment by Franiac** [comment]
This implies that TL can be minimized to system tray due to the fact that only applications running with a try icon can show standard windows tray notifications. Implementing a try icon that does nothing and is basically only there to enable notifications seems not like a good idea to me. I have to investigate if there is a way to show notifications without the tray part.

**Comment by tezJR** [comment]
Or make the taskbar icon flash? It might be a small disadvantage to not have different notifications for error and success, but the point is to be alerted one of the two happened.

**Comment by randomname42** [comment]
An option to have a sound play when there's an error or when all downloads finish would be really helpful, so you know without having to check on the program periodically. 

Actually, to be able to have TL auto-retry a failed download after something like five or ten minutes would be incredibly helpful. Any time all downloads error out for me it's been because of a temporary net hiccup that almost never lasts longer than a few minutes. But I usually don't notice everything stopped prematurely until quite a number of hours later. There would probably have to be a retry limit of course, in case a vod got deleted or something.

**Comment by Franiac** [comment]
@randomname42 I'll take the audio-part into account

**Comment by Franiac** [comment]
Update:

System tray with standard Windows notifications cannot be used because they are not persistent on Windows 7/8/8.1.

The only way I can think of is letting TL message boxes popup as top-most. But let's say you're enjoying a game of PUBG or CS and suddenly TL grabs your mouse cursor's focus and you're in the middle of a cool fight.... probably results in an instant uninstall of TL....
Brute force notifications are bullshit, that's not gonna happen.

I tried to find a software piece that does the same thing but they all use non-persistent notifications. And 95% have a good chance to be overlooked by the user because they are quite subtle.

I am open to other ideas but so far I cannot find a compromise between "don't annoy me" and "I don't want to miss anything".

**Comment by randomname42** [comment]
Well, that's unfortunate. Thank you for taking the time to look into it. I'm surprised there isn't a better way of doing things that fits between the "don't annoy" and "don't miss", but sometimes it's the things that seem like they should be simple that turn out to be far from it.

Could there be options to have a sound play when there's an error that stops a download, and a separate sound for all downloads have finished? That would at least give some kind of notification. 

A couple nights ago I set up some downloads to go overnight while I slept, and it turns out almost everything had failed when I got up. From what I could tell my net must have hiccuped shortly after I set up the downloads, and I think before I had gone to bed. If there was just some kind of audio cue to warn you about this I probably would have known before I went to sleep that something went wrong so I could make them all retry.

I do understand not wanting to cause that PUBG or CS situation you mentioned. On the other side of it, though, sometimes when I use TwitchLeecher I feel like I need to be glued to the pc to keep checking on downloads manually. I kind of have started to avoid using TwitchLeecher as much as possible because of this. I'm not trying to be mean here, or put on any pressure. It's just, that's where I'm at.

Other more general downloaders I've used usually let you set up an audio sound to play when certain things happen, like all downloads finish or a download failed. And I have found that to be incredibly helpful. So I hope it would be possible to put in a way for sound notification.

**Comment by Franiac** [comment]
The audio part is an option. The bad thing is that I need an external library in order to play back mp3 which would be the most common file format to use. *.wav is ok-ish but does not feel "complete". I have to check the licenses of mp3 libraries. Recommendations are welcome.

The issue would be a lot less important if I already had a proper download manager (#46). I could wait half an hour and try again and all the fancy stuff like saving state, closing TL, open it again and continue the download. You only have to look at your PC all the time because the download manager is not a thing yet.

As for this issue: I'll look into audio and that's it. I am uncomfortable implementing any kind of popup notifications for the given use case.

**Comment by randomname42** [comment]
I don't know anything about mp3 licensing unfortunately. The general download managers I've used usually only let you choose wav, so it wouldn't be unusual to not have an mp3 option for notification if that turns out to be too messy like popups were. 

Good luck on the download manager. It will be so great when (if?) that can eventually be done and ready to go in TwitchLeecher. I wasn't surprised when you said in the other thread that it will be as much work as TwitchLeecher itself. Hopefully nothing compared to building a house though :)

Honestly, it's kind of amazing that you've been able to do as much as you have without a true download manager. There's only one other thing I know of which can even get Twitch vods anymore, and that can't set a start/end time, nor tell if a download finished properly or not--so you have to check everything manually afterwords to see if it was really complete. 

This is something I've been wondering about. One upside to that other thing is somehow it doesn't have to use twice the disk space in the processing stage, which means half as much having to write to the hd, which I worry is long term bad for a hd if I use TwitchLeecher too much. It seems like it's very intensive when TwitchLeecher is processing at the end.

You would know much better than me. Is that paranoia on my end, or is having to write everything to the hdd a second time during the processing stage something that could cause a lot of extra wear over time? Traditional hd of course, not a ssd.

**Comment by erkantaylan** [comment]
> I am open to other ideas but so far I cannot find a compromise between "don't annoy me" and "I don't want to miss anything".

What about https://github.com/raflop/ToastNotifications ?
I can try to implement if you give some tips.

**Comment by Franiac** [comment]
@erkantaylan I know this library. Cool stuff but nothing that solves the issue. I kinda have toast notifications in TL already (when saving preferences or adding a download).

I don't remember exactly but as far as I know the notifications of that library ar strictly bound to a WPF window instance (positioning). What we need is a decoupled system of top-most notifications positioned relative to the active display even if the user is in-game. Steam does this for example. This combined with an optional audio-notification would be the best approach in my opinion.

**Comment by erkantaylan** [comment]
> What we need is a decoupled system of top-most notifications positioned relative to the active display

With this config we can achieve it

    // PrimaryScreenPositionProvider
    Notifier notifier = new Notifier(cfg =>
    {
        cfg.PositionProvider = new PrimaryScreenPositionProvider(
           corner: Corner.BottomRight,
            offsetX: 10,  
            offsetY: 10);
       /* * */
    });

https://github.com/raflop/ToastNotifications/blob/master-v2/Docs/Configuration.md

> even if the user is in-game

This only works if game is `borderless window` I tried with a few games, and does not work with `exclusive full-screen`.

**Comment by Franiac** [comment]
That's a shame... most of the games are played in exclusive full-screen, some don't even support optional borderless.

what about

`cfg.DisplayOptions.TopMost = true; // set the option to show notifications over other windows`

normally TopMost means it literally. Have you tried that?

**Comment by Franiac** [comment]
And the fact that I want to switch from WPF to a Chromium web view for the GUI (maybe Electron) does also not fit. I really am done with WPF. Our software at work is also WPF and the amount of XAML and C# code you need for a nice themed GUI is insane. WPF is one of the most unproductive GUI libraries I know. A test on my side showed that the code needed for all the current controls to look the same in HTML/JS/SCSS is 15 times less. That's just rediculous.

**Comment by Franiac** [comment]
As an addition: This example clearly shows that no matter what library or framework you have, the best experience of a software piece is achieved by programming closest to the native API as possible. Every framework lacks something, and .NET is no exception.

**Comment by PatrickMitchellUI** [comment]
Could this be implemented the same way steam shows online notifications (seems to do it even with the tray icon turned off)

**Comment by Franiac** [comment]
#803
