### ISSUE TITLE
Installation Failed - Your System Has not Been Modified 

### ISSUE THREAD

**Issue by Bj007pro** [Franiac/TwitchLeecher#185]
https://i.imgur.com/e23fVud.png
I not sure if I need to provide any more information but if I do just ask.

**Comment by Franiac** [comment]
What OS and Bit (32/64) are you using?

If you are familiar with the command line you can start the installer with the argument "-l" (without quotes) so it writes logfiles.

**Comment by Bj007pro** [comment]
Windows 10 64-bit.
I also don't think it helps that you are using a 32-bit installer to install a 64-bit program.

**Comment by jcward** [comment]
Same problem, Windows 7 64-bit.

Running the installer with `-l` does nothing at all. Running without `-l` at this point asks to uninstall (odd, it doesn't seems like anything's installed, no items in start menu.)

But, following through, let it uninstall, then run installer again, and install completes successfully!

![selection_999 1162](https://user-images.githubusercontent.com/2192439/30548550-b301fd8c-9c4f-11e7-8078-c07ae48760a9.png)

**Comment by Franiac** [comment]
@Bj007pro You cannot install TL 32 Bit on a 64 Bit system ;) but I just wanted to know because the installer is different.

Regarding the -l argument: I forgot that you actually must specify a filename for the logfile:

`TwitchLeecher_1.4.1_x64.exe -l log.txt`

So please try this and see if the file gets written.

**Comment by Franiac** [comment]
Closed because stale
