### ISSUE TITLE
All vods downloaded have audio desync

### ISSUE THREAD

**Issue by ChiggaYuan** [Franiac/TwitchLeecher#194]
I'm using 1.4.2 rn. I've tried using 1.4.1 and it didn't work. I've tried changing the quality and downloading from different streamers. I've also tried reinstalling. So far nothing is working. Does anyone know how to fix this?

**Comment by Franiac** [comment]
TL does not encode, it only merges files so TL cannot be the source of the problem. Tl does not change of shift the audio or video stream.

The more important thing is what program do you use to watch the video? There are a bunch of video players (especially Windows Media Player) and video editors (especially Adobe Premiere) that cannot handle downloaded Twitch streams and generate A/V desync. I strongly recommend VLC to test it because usually VLC does not mess things up.

**Comment by ChiggaYuan** [comment]
I tried with vlc and it worked, the audio was in sync. My editing software (Camtasia Studio 8) doesn't play the vods in sync. Is there anything I can do to make the videos' audio in sync in Camtasia?

**Comment by ChiggaYuan** [comment]
I know another person that also downloads twitch vods at source but can open them with wmp and Movies & TV.

**Comment by Franiac** [comment]
The most common problem is that projects of various video editing softwares run at a certain FPS. Let's say you open up a new Camtasia project and you choose either 30 or 60 FPS for your project. Now you import the downloaded video from Twitch. That video has 29.97 or 58.76 FPS (and that is sometimes the case, don't ask me why). Now shit gets real when Camtasia interprets the 29.97 FPS video as 30 FPS. Basically what happens is that it stretches the video to 30 FPS but leaves the audio stream alone resulting in A/V desync over time. So the longer the video is, the more desync there will be.

The solution is to set the project FPS to exactly the same FPS of the Twitch video. But then again the problem is that some consumer products like Camtasia cannot set the FPS to odd values like 58.76 FPS or something like that. I personally use Sony (or now Magix) Vegas Pro and it asks me to set the project FPS to the FPS of the very first imported video file. Now the whole project has 58.76 FPS and then I export it as 60 FPS. In this case Vegas interpolates the whole project and it works very smoothly without any desync.

I hope this explanation helps. I will use this issue in the future to link similar issues and requests to it.

**Comment by sparcut** [comment]
@Franiac As you described TL process of combing clips, it sounds very similar to person I found on the adobe forums as they describe this issue of audio dsync occurring, when they combined (grouped) multiple "chapters" (clips) with the audio.

Before searching here for issues regarding such problem, I was trouble shooting Premiere Pro (PP), in the process I tried converting, copying etc. though got an error along the lines of `The file duration is too long for timebase`. Also trying to play the video with QuickTime (was changing to `.mov`, since PP has an easier time with them for some reason), the video would not open at all exiting with an error: `a bad public movie atom was found in the movie`. Which apparently refers to the mp4 container being damaged or incorrect.

So it I feel like something is happening when you're combing the clips and audio. I'm going to take a look  now, but I haven't dabbled in a lot of C#.

**Comment by Franiac** [comment]
Well, you don't need to search:

TwitchService.cs line 1099, method "ProcessVideo". That's where TL calls FFMPEG with some arguments. It receives some parameters like the m3u8 playlist with all the downloaded VOD parts on the HDD alongside some cropping times (if cropping is enabled).

The main ffmpeg arguments are

```C#
"-y" + (cropInfo.CropStart ? " -ss " + cropInfo.Start.ToString(CultureInfo.InvariantCulture) : null) + " -i \"" + playlistFile + "\" -analyzeduration " + int.MaxValue + " -probesize " + int.MaxValue + " -c:v copy -c:a copy -bsf:a aac_adtstoasc" + (cropInfo.CropEnd ? " -t " + cropInfo.Length.ToString(CultureInfo.InvariantCulture) : null) + " \"" + outputFile + "\""
```

Now that does all the magic. There is a concat argument available in ffmpeg that I tried also but this way the resulting video was actually a concatination of the parts with little freezes between them (like every 2s). What we need in order to solve this issue here is not me fiddling around in C# (because that's not what the merging does) but a true ffmpeg pro who knows the shit (I am not!).

Thanks for your input. If you think you found something out that we should try on ffmpeg, let me know!
