### ISSUE TITLE
Minor functions.

### ISSUE THREAD

**Issue by CloudedMind** [Franiac/TwitchLeecher#199]
Hello,

I appreciate your works of TL.
TL is very precious.

If possible, would you consider adding these functions to the future release?

1. After searched VODs. display the exact time that went live. The old releases have it, but latest releases don't. The exact time is quite helpful.

2. After searched and selected a VOD, I'd like to enter the END time that exceeds the length of the VOD.
Sometimes, need to search several times to get the real length of VOD especially it's on live. It'd be very helpful.

Thanks.

**Comment by Franiac** [comment]
I'll think about the time thingy.

Point 2 makes no sense. It is not possible for TL to download VODs that are currently live, because the playlist must be complete BEFORE TL starts downloading. You'll never get the full VOD the other way. Consequently I should not display VODs that are not finished recording.

**Comment by CloudedMind** [comment]
Thanks for your replay.

About second one, I understand your point.
However, please keep displaying them. It's still useful.

Thanks you again!!

**Comment by Franiac** [comment]
Maybe display them but make them not downloadable...

**Comment by CloudedMind** [comment]
Well... I think lots of people might be using TL before finished recording.
It was not expected that the useful function will be removed because I mentioned it.
If I made you feel bad by posting it, I apologize to you.

Please consider it again.

Thanks.
