### ISSUE TITLE
Remember last several searches

### ISSUE THREAD

**Issue by ihabunek** [Franiac/TwitchLeecher#201]
I always do the same searches and I always need to type in the channel name and choose "last 10 results".

Would it be possible to save the last several searches and show them underneath the search box so I can just click on one of them instead of typing?

**Comment by Franiac** [comment]
The defaults for the whole dialog can be set in the preferences. That eliminates setting "last 10" every time.

As for different channel names, please see my answers from #113

Keeping the whole history of the search input is a cool thing, but honestly, I don't know, when to do that considering more important issues like #46 or #174 and the fact that I am currently building a house :D

Another thing would be the compatibility between versions (if the input dialog changes). So this issue is not trivial. I'll put it on my non-official feature list and close this one here.

**Comment by ihabunek** [comment]
Understood. Another idea which would work for me is a screen which shows recent broadcasts of all the people i follow on twitch.

**Comment by Franiac** [comment]
That would require me to authenticate TL to your account (same as downloading sub-only VODs). The API-information who you follow is non-public. The thing is, I'd like to keep TL as smooth as possible without requiring authentication. To many users authenticating is a hassle and has a fishy touch to it because they quickly think I steal their account info or email address or something like that. I want to avoid popups that tell you to log in as much as possible.

You cannot argue objectively on that matter, it's just how users work :)

**Comment by ihabunek** [comment]
OK, I can appreciate that. KISS is a good rule to follow. All in all, these are all minor nitpicks on my side. You've made a great tool which makes my life easier. Thanks.
