### ISSUE TITLE
Able to watch 1 but not another

### ISSUE THREAD

**Issue by forumaccount1** [Franiac/TwitchLeecher#209]
i downloaded 1 vod and was able to watch it on windows media player but the next 1 is like an mp3 file where only the audio is playing. kinda forces you to watch it on vlc. is this a bug or a known thing?

**Comment by Franiac** [comment]
It is very well known that Windows Media Player is not a piece of software but a giant pile of crap that fails at tasks it was programmed for :)

No, dark humor aside, WMP has serious problems with downloaded Tiwtch VODs (depending on the encoding settings of the streamer) and it is not recommended to use it. Being forced to use VLC is not a bad thing because it is simply one of the most reliable video players out there. It is my default player... just saying.
