### ISSUE TITLE
Installer wont launch

### ISSUE THREAD

**Issue by SmseR** [Franiac/TwitchLeecher#210]
I launch it, and it just closes right away.
I did the **-l "logfile.txt"** thing
Here it is:
[logfile.txt](https://github.com/Franiac/TwitchLeecher/files/1586070/logfile.txt)

**Comment by Franiac** [comment]
You have Windows 7 Service Pack 1. Probably you don't have the requirements installed to run TL. You need .NET Framework 4.5 or higher as stated [HERE](https://github.com/Franiac/TwitchLeecher#download--requirements)

The logfile tells me, the UX could not be loaded. The UX is a .NET 4.5 application...

**Comment by SmseR** [comment]
But I have NET 4.5 installed and the older version of TL (1.3.7) is working fine

**Comment by Franiac** [comment]
See those threads (googled "Failed to run per-user mode" -> the actual error in your logfile):

[Click 1](https://social.msdn.microsoft.com/Forums/vstudio/en-US/4156dc61-8e16-4e5f-b310-c67c9eb85a5d/vs-11-mysterious-installation-error?forum=vssetup)
[Click 2](https://forums.garmin.com/forum/garmin-express/garmin-express-pc/120877-)
[Click 3](https://ricardodsanchez.com/error-0x80131902-failed-to-create-the-managed-bootstrapper-application/)

The TL installer has not changed since TL 1.1 so it is very unlikely that there is a problem with it. Otherwise there would be more issues reported. As stated within the above threads everything points to a wrong installation/configuration of .NET Framework. What it actually is, I don't know since I don't have access to your computer.

**Comment by Franiac** [comment]
Oh and this:

[27C8:18E8][2017-12-25T21:08:38]e000: Error 0x8013101b: Failed to create the managed bootstrapper application.
[27C8:18E8][2017-12-25T21:08:38]e000: Error 0x8013101b: Failed to create UX.
[27C8:18E8][2017-12-25T21:08:38]e000: Error 0x8013101b: Failed to load UX.
[27C8:18E8][2017-12-25T21:08:38]e000: Error 0x8013101b: Failed while running 

This is a strong sign that the installer actually did not find .NET Framework 4.5 because the managed bootstrapper is the .NET Framework part of the installer that needs it. So you really have to check or update your .NET Framework.
