### ISSUE TITLE
is not installed

### ISSUE THREAD

**Issue by zelentcov** [Franiac/TwitchLeecher#217]
I reinstalled the window 10 pro ( х64 ), after that the program did not install/work
![2018-01-13_11-54-10](https://user-images.githubusercontent.com/35394449/34904577-9fbac716-f859-11e7-96d3-1f0703292ebd.png)
This is the standard error notification. I tried to run as administrator, install the previous version and x86 version. All the same error when installing.
Sorry for my bad english and mistakes
[Installation_Log.txt](https://github.com/Franiac/TwitchLeecher/files/1628194/Installation_Log.txt)

**Comment by Franiac** [comment]
The log does not show any error within the installer itself. If the managed installer of TL fails, the source exception of the error gets written to the log. But in your case the program simply crashed without any reason. Maybe you could check the windows event log (category "Application") for more info...

**Comment by zelentcov** [comment]
I found what you asked for, but I absolutely do not understand what to look out for.
I am hope for your help
[log.zip](https://github.com/Franiac/TwitchLeecher/files/1628532/log.zip)

**Comment by Franiac** [comment]
The log says:

"Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program Twitch Leecher 1.4.2 because of this error"

Are you trying to install TL from a network drive or some kind of USB drive? If so, try copying the installer to a local drive of your harddisk and try installing from that.

**Comment by zelentcov** [comment]
I installed from the local disk of my hard drive.

**Comment by Franiac** [comment]
Then I don't really know unfortunately. The log states that Windows kills the installer process. Why? I don't know but like I said before it is not an internal error in the installer that I could fix.
