### ISSUE TITLE
1.4.2 giving a trojan warning on download

### ISSUE THREAD

**Issue by raistiff** [Franiac/TwitchLeecher#218]
Part way through downloading I get a warning of trojan:Win32.fuerboos.D!cl probably a  false alert but on previous releases I do not have this issue,

**Comment by Franiac** [comment]
I cannot fix false positives. Because... they're false, right? :D
You could send it to the anti virus software manufacturer that you are using, though. It's their problem if they detect a virus where there is none. I cannot do anything about it, unfortunately. But thx for the info (not the first one)
