### ISSUE TITLE
Cannot install/uninstall

### ISSUE THREAD

**Issue by saasasasasa** [Franiac/TwitchLeecher#224]
I have Windows 7 Sp1 x64. I tried installing the x86 version of the application, it installed microsoft .net framework 4.5 but then gave me a warning that I need to install the 64 bit app. Ok, so I downloaded and tried to install the x64 but now I get the message:
![1](https://user-images.githubusercontent.com/34808532/36061279-8c8e989c-0e58-11e8-8afa-deccb069ff85.jpg)

So I got to Programs in control panel and I see an entry for Twitch Leecher, but when I try to uninstall it gives me this message: 
![uninstall](https://user-images.githubusercontent.com/34808532/36061303-cbac37e6-0e58-11e8-8c59-c9420738bfe2.jpg)

I tried looking for any Twitch Leecher entry in regedit, but couldn't find any. There is also nothing in Program files and Program Files x86. Nothing in appdata, I cleaned temp folder but it still says that the application is installed, but dunno where.

Here is a log file of the 64 bit installer: 
[log.txt](https://github.com/Franiac/TwitchLeecher/files/1713289/log.txt)

**Comment by Franiac** [comment]
Ok, first thing you should try is downloading "Revo Uninstaller" and see if that helps. It is not malware or anything, I just recommend you that software since the good old Windows Uninstall Clean Utility is deprecated.

If it uninstalls TL successfully, check if it is not present in the control panel anymore. Then try to reinstall the 64 Bit version.

Question: Why did you try to install the 32 Bit version in the first place? I am just curious, because as of 2018 it absolutely makes no sense since all available CPU's and OS' are 64 Bit.

Leads me to the question if I should completely discontinue the support of TL 32 Bit :)

**Comment by saasasasasa** [comment]
Ok, the revo uninstaller actually worked. And it reminded me that I forgot to look for the twitch leecher leftovers in Program Data, it deleted these things and now the program installed perfectly. Thanks for the help.

I have a really old pc and with some apps developers recommend the 32 bit version as it uses less ram and stuff like that so I thought I'd try that here too.

**Comment by Franiac** [comment]
The ram argument is like 10 years old :)

32 Bit programs can only allocate a maximum of 3,5GB of ram. That has nothing to do with the fact that 64 Bit programs use more or are less efficient. In fact they just use the AVAILABLE ram IF necessary which is a good thing because it speeds up the program. In the very early days of 64 bit tools there were a couple of annoying problems that actually caused problems on runtime but that is long gone.

TL uses FFMPEG in the background. FFMPEG 32 bit cannot run on 64 bit systems and vice versa so TL shares those specs.

I think I just discontinue the 32 bit version of TL completely since there is absolutely no downside to it.
