### ISSUE TITLE
setting for default download quality

### ISSUE THREAD

**Issue by nzall** [Franiac/TwitchLeecher#226]
I download for watching on an iPhone SE, which has a smaller screen than 1080p (closer to 720p). As such, I do not need to download 1080p videos and always change the quality manually to 720p60. However, downloading a lot of videos at once, I have to manually configure this quality every time. It would be nice if I could choose a default download quality for videos in the settings.

**Comment by Franiac** [comment]
Impossible since the streaming quality is dependent on the streamer

**Comment by nzall** [comment]
I thought as much. Would it instead be possible to remember the last selected streaming quality, even if only while the program is open?

**Comment by Franiac** [comment]
Nope, sorry :) The streaming qualities can differ not only between channels but even between single videos (even if that's not very often the case, it is still possible). Just because one video is 720p@60fps, does not mean the next video from the same streamer has this exact quality as well. There is no coherence and for that reason I cannot implement somthing like a default quality reliably.
