### ISSUE TITLE
[NOT AN ISSUE, QUESTON]

### ISSUE THREAD

**Issue by MPeti1** [Franiac/TwitchLeecher#228]
Hi!
In the filename box what keywords can i use other than date, id and Game? i wanted to put the title to the files name automatically, and i found out fast i can use simply title, but are there such keywords what i can use? I've read the wiki and there is no info about it

**Comment by Franiac** [comment]
Why do you think there are those little yellow questionmarks on the righthand side in the preferences view ;)

Just hover the mouse cursor over them and there you go...

**Comment by MPeti1** [comment]
Oh, really :D but at an other settings option i even used it... xd
Sorry for bothering you, I'm a bit tired and forgot to check this help button :D

**Comment by EllyKida** [comment]
I don't know if you will read this, because the thread is closed, but I still want to try it ^.^

If I start downloading a broadcast, which has just finished streaming, which is say... 7 or 9 hours long, twitch starts to do its "music recognition" in the background... when the download is 70% done and twitch finished its recognition the download will stop and fail because twitch replaced the files or something... idk.
The point is, I already downloaded 70% of the stream and the files of the "failed" download are getting deleted from the program on my drive. Is there a possible way, to add a checkbox so I could chose to deactivate this feature so that the program won't delete the files? 'Cause the downloaded files are okay and I could use them and join them together in another program...
