### ISSUE TITLE
Feature request: turn off system after downloads complete

### ISSUE THREAD

**Issue by MTphilclothier** [Franiac/TwitchLeecher#233]
Thanks for creating this awesome software!

I have a suggestion for a feature which I think would be desirable for a lot of users. Could there be a setting to switch off the computer after all downloads complete. Kind of like uTorrent or FileZilla does. So you could leave the queue downloading overnight.

**Comment by Franiac** [comment]
This was requested some time ago. I personally don't like such features because they are inconsistent.
Let's assume we have a checkbox on the download page you can activate.

Scenario 1: You activate it, add a download, download completes, pc goes offline -> OK
Scenario 2: You add a download, you activate it afterwards, download completes, pc goes offline -> OK
Scenario 3: you add 3 downloads, activate it, one download throws an error -> what to do??? go offline and lose the log or stay online?
Scenario 4: you add 3 downloads, activate it, download starts, you remove the downloads because you changed your mind, you add a different 1 again but forget that you enabled the checkbox, download complete -> pc goes offline -> SHIT!

This seems like an easy to implement feature but we need to clarify what users really expect in scenarios 3 and 4

MY expectation for 3 would be: If there's an error, don't go offline. But that again is only because TL does not keep logs right now.

Expectation for 4: If I clear all downloads manually, the checkbox resets automatcally. But then again the user has to remember setting it again when adding another download.

That's why I am generally not a fan of such a feature because you suddenly need a manual to know exactly what it does. So far TL is pretty much manual-less and I like that (I my eyes self-describing software is good software).

What do you think?

**Comment by Doublespin** [comment]
Scenario 3: The main interest ist that the pc should shut down. I think this suits more people than the other way around. Probably most just try the download again and only if the error persists go here to ask for help. Contra: people may wonder why a file is missing.

Scenario 4: You could add an alert sound 30 secs before Shutdown so the user has time to react. But I don't think this is a good solution. Another one: Monitor key and mouse aktivity and only shut down after downloads are finished and inactivity is longer than x.

**Comment by Franiac** [comment]
Maybe shutting down in scenario 3 is better, yes, but I really would like to implement persistant logs with that (along with a "open logs folder" button somewhere in TL).

Scenario 4: Sound is a bad idea. It would require the user to use some sort or audio equipment, so that is not leading anywhere. Monitoring mouse and/or keyboard activity (even if ONLY activity and not real key presses and such) has a suuuuuuper fishy touch to it for many users. Once revealed in source code, the shitstorm is there even if you do no harm (I had that in the past and won't make that mistake again). And even some anti-virus software does not like such native calls.

So you see why I am hesitating implementing this feature. I'll let this one open and hopefully we can get a few other opinions on the matter but so far I am not pleased with the solutions we have.

**Comment by FireLemons** [comment]
If this ever gets implemented, it would be cool if instead of shutting down it called a user defined script which could contain shutdown instructions or something to post process the video files.

**Comment by PatrickMitchellUI** [comment]
@FireLemons Agreed, custom execute on finish would be amazing, maybe even with a variable for the file name so you can set an forget

**Comment by Franiac** [comment]
#803
