### ISSUE TITLE
filename template: start, end

### ISSUE THREAD

**Issue by Doublespin** [Franiac/TwitchLeecher#234]
I like to download streams in smaller parts about 1 or 2 hours runtime. If one download fails I dont have to download everything again. For now I label the videos by hand but it would be much more convinient if the labels for the start and end time would be added automatically:
`{channel}_{date}_{id}_{game}_{start}-{end}.mp4`

**Comment by Franiac** [comment]
If I ever have the time to implement a proper download manager (project size of TL probably), that feature would be unnecessary. What would you expect the format to be?

Given the fact that noone ever should download a VOD with 3 digit hours we could go with a format like 014356 (HHmmss). What do you think?

**Comment by MiGraber** [comment]
I would be totally satisfied with `HHmmss`. I dont think that there is the need for a delimiter.

**Comment by Doublespin** [comment]
I think HHmmss is just fine.

**Comment by Franiac** [comment]
I have looked into this and relized that it is not as easy as I have thought. The filename is determined as soon as you click "Download" on a VOD. Every information for any wildcard is available in the VOD info at this time. Now the filename is created (all wildcards resolved) and shown in the filename textbox. The cropping and with that the start/end time is too late...

I would have to implement some kind of radio button like "Use filename template" and "Use custom filename". This is shite to be honest. Only template is not an option because you would have no option anymore to specify a custom name if you wanted to. Meh, that sucks. Now I kinda dislike the whole issue to be honest. It makes the download dialog just 10 times more complicated because of two little wildcards... no me gusta!

**Comment by Doublespin** [comment]
Alternative:
Dont use `{start},{end}` wildcards but implement the option to download a video in parts:

Create a new checkbox after the crop section (start/end timestamps).
`Download Video in [60] minute parts.` With [] as customizable field.
The filename can be extended with `-x`. Where x is the part counter.


- This should work well with the cropping options.
- It would be make downloading (at least for me) much more comfortable.
- It should avoid the wildcard problem

Only negative point I came up with:
- Its not customizable. So everyone has get along with it or dont use it :P

How do you think about this?

**Comment by EwoutVDC** [comment]
I have an issue similar to this. I would like the filename to be updated when changing the video quality in the download dialog.
Could you not somehow pass the template to the download dialog and update the filename when any of the used wildcards changes?

I could try to make a pull request if you want

**Comment by Franiac** [comment]
@EwoutVDC Passing the template to the dialog and updating wildcards on-the-fly is not the problem at all. The unintuitive thing would be this:

1. Open the dialog
2. Template gets updated ({start} and {end} default to 000000 and video length)
3. now you change the filename MANUALLY (just by typing in the textbox)
4. Enable cropping and change start or end
5. filename gets updated from the template and all your manual changes are gone

This is what bothers me because:

1. if we say once a manual change has been made the template does not update anymore, the whole template update thing makes no sense anymore. I hate features that work and suddenly after I typed something they don't work anymore. That is inconsistent.
2. if we update always from the template the manual changes are gone if you mess around with cropping

That is why I commented earlier we would have to implement some kind of radio button to specify if we want to specify the filename manually or automatically (by the template). Even if we make this a preference option I don't see how that is intuitive for the user. We developers all know what it does but it needs a lot of explanation for the average user. What I want to say is this: I don't want to introduce features in TL that are unintuitive or hard to understand for the average user. Wen need a consistent solution that always works the same.

**Comment by EwoutVDC** [comment]
@Franiac I understand that, but you already have an option (res, fps) that is not updated when changing it.
I wanted to limit the filesize of some streams and DL 720p 30fps and i had to manually change the filename to match the resolution (or not include the wildcard).

Your option 1 is definitely frustrating, but option 2 sounds decent to me.
If you specify a template, i think it makes sense to update the filename if a wildcard changes.
You would have to put the filename below the cropping options for that to make sense though.
Perhaps with a warning label if it changes if you want to add focus to it?
Making it an option would be more work and probably not add much.
You could also add a button to update the filename if you don't want it to happen automagically.
It's your project so you decide of course.

Ideally, you would only generate the filename once all wildcards are known, but then you would need another step to confirm the quality and cropping options before generating the filename.

BTW, a default quality would also help not having to change it for every video. As well as showing the filesize for each quality in the dropdown box. I'm not sure if that is possible though.


Either way, thanks for this project. it really brightens up my commute 😄

**Comment by Franiac** [comment]
@EwoutVDC The quality not being updated is a bug that I was not aware of until now. But it shares the same context as start and end wildcards.

I recommend reading #226 #244 and #238 😄 

So as of now... if I update to Helix, the whole quality selection will be gone. And I surely won't update on the last day so prepare yourself losing that feature in the near future.

The custom filename also will become obsolete as soon as I implement multi-selection in the search window together with a "Download Selected" button.

Option 2. of my previous comment is also super frustrating to me. I know some software pieces that handle input like this and I rage everytime.

The only bearable solution to the current issue is the following for me:

I place a CheckBox next to the filename saying "Custom Filename". If checked, the user can manually overwrite whatever is shown currently. The filename will NOT be updated automatically as long as the checkbox is checked. If the checkbox is not checked, the filename gets readonly and updated through the template. That is the only consistent way I see here.

**Comment by EwoutVDC** [comment]
Thanks for your responsiveness! I was on a holiday and didn't feel like answering on my phone, but here's a late reply.

I like your idea for a checkbox but i agree that it's not really worth it to put any effort into this before updating to the new api.
Sucks that we won't have quality options there but it is what it is.

I should have done a simple search before just blabbering ideas 😊 
Thanks again for the great work you are putting in!
