### ISSUE TITLE
Feature Request - File Size?

### ISSUE THREAD

**Issue by Goldninja100gn** [Franiac/TwitchLeecher#244]
So I was wondering if there is a way to add a File Size before downloading it. Like with Sony Vegas before I render a video it tells me how big the file will be. 
![filesize](https://user-images.githubusercontent.com/12952449/39411678-5e7238b0-4bd4-11e8-8d77-c8353614696b.PNG)
_24 MB is just one photo I added to be able to get to the render screen_

I just thought it would be a Nice addition to the program.

**Comment by Franiac** [comment]
that is not possible. a VOD consists of thousands of small pieces. the file sizes of these are not available pre-download. with #46 we could introduce the file size while downloading but not before.
example: a 3 hour VOD can consist of 11000 pieces depending on the quality. so i have to make 11000 html head requests in order to get all those file sizes and add them up. that is not possible just "on the fly" (takes a minute or two depending on your internet connection).

**Comment by Codereaders** [comment]
Aren't all single pieces of the same size?
The total size would then be calculated as:
`total_size = count(parts)-1 * size(part_0) + size(part_n)`

Also at least you could give an approximated size by:
`approx_size = max_pkt_size * count(parts)`
The maximum packet size will be of an fixed bound, depending on the underlaying network protocol.

**Comment by Franiac** [comment]
No, the parts are not the same size always. Sure, an approximation would be possible but I do not have the playlist information before the download. I need to generate a token, call the Twitch distribution API and get the playlist, parse it for the file urls and then query the metadata. That's simply too much stuff just for providing a file size. I stick to my previous answer... file size wihile downloading is fine but just as an info in the download dialog, nope.

**Comment by Goldninja100gn** [comment]
Thanks, I was just wondering if we could add an approximation time... It was a good try lol
