### ISSUE TITLE
Support for Linux and Mac?

### ISSUE THREAD

**Issue by teocci** [Franiac/TwitchLeecher#245]
Franiac,

It will be nice to provide support for Linux. I Don't have windows and this is the only app I saw that allow us to download VOD from twitch.

**Comment by Codereaders** [comment]
[Arne Vogel](https://www.arnevogel.com/) wrote a go application called [concat](https://github.com/ArneVogel/concat) to download VoDs from Twitch. I never tried it up to now. For Linux users that feel comfortable using the CLI it might be a appropriate solution.

However, there is also a [website](http://concat.org/twitch-download/) that builds its service on concat, but the website provides only limited access to what concat is able to do.

**Comment by Franiac** [comment]
See #172 #190 #221

**Comment by teocci** [comment]
https://github.com/teocci/TwitchLeecher I created this project for the people that uses mac or linux.

**Comment by gqunukhwebe** [comment]
HOW DO I USE THIS?
I can't run a folder using Java?

**Comment by gqunukhwebe** [comment]
Please give me a tutorial on how to use this!

**Comment by Codereaders** [comment]
If "THIS" is some third party software that doesn't belong to Franiac/TwitchLeecher:
This Issue tracker is limited to the @Franiac 's TwitchLeecher project. You won't get any third party software support here.


Franiac's TwitchLeecher isn't a Java application, it's written in C# and that's why it's not possible to run it as a Java application.
Here you should find an executable as well as the source code to download: https://github.com/Franiac/TwitchLeecher/releases
On Windows, just download and run the executable. It's not designed to run on macOS or Linux.
