### ISSUE TITLE
Will not run- prompts to uninstall

### ISSUE THREAD

**Issue by edub28** [Franiac/TwitchLeecher#249]
I'm running W10 64 bit. Installed program, but every time I try to run, it prompts me to uninstall. I've reinstalled twice and having the same issue. Please help.

**Comment by Franiac** [comment]
That sounds a little bit weird... how do you actually "run" it. Do you open TL from the start menu?

**Comment by edub28** [comment]
The shortcut on my desktop or the task bar.

**Comment by Franiac** [comment]
And where does that shortcut point to? I have a strong suspicion you are calling the installer again instead of TL in

`C:\Program Files\Twitch Leecher\Twitch Leecher.exe`

because the above is not even capable of displaying the uninstall window. Right click on your shortcut and select "properties". Where does that point to (Target)?

**Comment by edub28** [comment]
You're correct. It was in the windows folder not my desktop. Thanks.
