### ISSUE TITLE
Mark Previously Downloaded Videos

### ISSUE THREAD

**Issue by photonometric** [Franiac/TwitchLeecher#256]
This is a fairly simple request. It would be great if there could be some kind of indication on the Search or Browse windows that indicated the videos one had previously downloaded successfully. It would help when browsing through my freinds' collections of dozens-hundreds of saved videos, when I don't download them in sequence. 

A fairly simple request, but a quintessential and extremely helpful feature in any downloading program. Thanks!

**Comment by Franiac** [comment]
This is not a simple issue at all. Keeping track of downloads is not trivial. Many users just copy the downloaded videos to some other location so the resulting files cannot be an indicator of a downloaded video.

TL could write a history file with the video ID's that have been downloaded but then the user has to have the option to reset this history and/or be able to mark videos as downloaded/not downloaded.

We as software developers rarely speak of simple things to implement because most of the time they are not 😄

We have to put in way more thoughts into this to come up with a solution that everybody is happy with.

**Comment by sparkyman215** [comment]
It could be done the way youtube-dl handles keeping track of past downloads, with a text file recording the ID's of videos. However resetting/selectively removing videos would probably be difficult to integrate into a UI area.

**Comment by Kaszanas** [comment]
@Franiac I think there could be at least some quality of life improving feature which would tell You which video You already started downloading and pushed it from the Search tab into Download tab.
E.g. Today I have to download 100 videos from a channel and it is hard to manually keep track of which I have already clicked and which I haven't.
The software itself is a really nice piece of work! Keep it up!

**Comment by Franiac** [comment]
I don't want to invest the time into workarounds. Don't get me wrong, I definitely see the need of all those nice features, but my time for the project is limited. I really should be working on #46 more.

**Comment by Franiac** [comment]
#803
