### ISSUE TITLE
Audio only when downloading VOD

### ISSUE THREAD

**Issue by vince94** [Franiac/TwitchLeecher#261]
Twitch VOD: [8344251](https://www.twitch.tv/videos/8344251)
Version: 1.5
OS: Windows 7 Professional, 6.1.7601 Service Pack 1 Build 7601
Download log: https://pastebin.com/U1YrjSdU
(I removed my username from the filepaths, as it contains my last name.)
Comments: I tried to download this VOD (a live feed from a convention), and it took the normal amount of time, but it seems to have produced a corrupted mp4. Opening it results in audio only, and uploading it to YouTube results in a "please only use compatible file formats" kind of error.

**Comment by Franiac** [comment]
That is not a problem of TL. You cannot upload a video without a video stream directly to YouTube. TL creates a mp4 just with an audio stream in it. YouTube will reject this. You'll have to convert it first with an external video tool. TL's job is not to generate "YouTube-Ready" video files.

**Comment by vince94** [comment]
Then why doesn't it play in Windows Media Player?

**Comment by Franiac** [comment]
I think your expectations are a little bit off. No offense, let me explain:

If you want a video stream within the mp4 file, why don't you select a quality WITH a video stream in it (as in: not "Audio Only"). "Audio Only" means exactly that... "Audio Only". Why should TL notify you that there is no video stream when you selected "Audio Only"? That makes no sense. And it is not TL that "messes it up", Twitch provides the stream like this. And this is the point.
TL is a downloader that packs a source stream from Twitch in a mp4 container "as is" without re-encoding. Otherwise downloading a 2 hr VOD would result in 8 hrs of re-encoding by FFMPEG. That is not the job of TL. TL does not change the source material that is provided from Twitch. TL is not an encoder. That's the common misunderstanding that occasionally leads to an issue (like this one). And I see why but that does not change the purpose of TL.

The normal workflow of people using TL is:
1. Download a stream with TL
2. Open it up in a video software or re-encode it to a different format with whatever external tool you can find
3. Cut your video
4. Render it (re-encode it)
5. Upload to YouTube in a format that is supported.

In your mind is "point 1 and I am done" and that's the misunderstanding.

Regarding Handbrake: I know the tool and I am surprised it cannot handle mp4 containers with an empty video stream. But as mean as it may sound, that's not my problem. If you think TL does provdie a wrong mp4 file, you don't have to talk to me but to Twitch. TL is only the "copy guy", that also means "shit in -> shit out". Twitch provides an empty video stream when downloading with "Audio Only". They are the source of your problem, not TL.

I hope that makes it clear for you what the purpose of TL is an why you can't expect any changes regarding this issue.

**Comment by Franiac** [comment]
Oh and... Windows Media Player... for the love of god and all that is holy... use VLC. You are wondering why the worst video player in the world cannot handle Twitch streams? Yea, that's why...

😄😄😄

**Comment by vince94** [comment]
I use VLC all the time at home, I was just using my work computer because the download/upload speeds are very fast, and it's easy to minimize and run in the background while I get things done. MP4 is a pretty widespread format, and other VODs played back in Windows Media Player just fine, so I just assumed it would be worth mentioning... 
Also, I did not select Audio Only. In fact, I tried several different quality settings, all with the same result. In the log I posted (from my final attempt), it says this:
`Line 10: Selected Quality: 1280x720@30fps (Source)`
`Line 38: Playlist url for selected quality 1280x720@30fps (Source) is`
Yes, I realize that some things are out of scope of the project, or not worth implementing. I wouldn't expect TL to be able to re-encode a Source-quality file to different resolutions or something, it'd be more straightforward to use video editing software or a tool designed to do that like Handbrake, like you said.
Whether I ran across a bug or not, I'm getting pretty strong "hey idiot" vibes so I'm just gonna back away slowly :/

**Comment by Franiac** [comment]
And this is exactly what I didn't want to achieve. I am grateful for every single bug reported. The problem is, explaining the facts and a workflow of a tool seems to upset people because someone is explaining them that what they want will not be implemented. That always has a negative vibe to it for the one reporting the issue. I have been in the software business for over 15 years and your last sentence doesn't surprise me and it is not the first time I read something like this.
But on the other hand you have to understand that this is a free time project and the fastest way of dealing with things is straight to the facts. For some people that may feel "harsh" but ey... that's the way I do it. And that's not because I think I am something better or have some arrogant attitude. I do not invest time into wording my answers correctly so hopefully I don't step on someone's foot. I have 1000 better things to do in my life than answering issues on GitHub the whole day, so I keep it short, accurate and to the point. You know what I mean...

So.... back to the issue. As you pointed out I misunderstood the "Audio Only" thing. I tried to download the VOD again with the given quality setting. On my end the whole video gets downloaded and it plays back completely fine in VLC 3.0.3. In addition to that I tried to open it in Sony Vegas Pro and Blackmagic Davinci Resolve. Both handled the file without any errors.

I don't know what else to say... it works on my end.
