### ISSUE TITLE
Errors resulting in all downloads failing 

### ISSUE THREAD

**Issue by pooiyx** [Franiac/TwitchLeecher#266]
Hi. With the latest version of TL (1.5.2), I often get Status: Error (in red text) when I try to download a video. 
I don't know exactly when during the download I get the error message (because I'm usually afk when I start downloads), but I've sometimes seen them happen near the beginning of a download for no apparent reason. 
Also, when a video in a queue suffers from such an Error, the rest of the videos in the queue seem to automatically get Status: Error too, meaning nothing has been downloaded while I'm away and waiting for my downloads to complete. 

Here are the error logs of a few such failed downloads (they were all sequentially in a queue): 
https://pastebin.com/iwDKCh5c
https://pastebin.com/s6SAxWRr
https://pastebin.com/HBdnTmiL
https://pastebin.com/6QnXYkiq
https://pastebin.com/YXDNPZn4
https://pastebin.com/Br2nNFUN
https://pastebin.com/MmXXh9XA

I didn't have this problem when using a previous version of TL. I can't remember exactly what version it was (it should be 1.4.x) before I upgraded to the current version. 
Also, my OS is Windows 7 Professional 64-bit, Service Pack 1. 
Thanks.

**Comment by Franiac** [comment]
All you downloads end with the exact same error:

`System.Net.WebException: The remote name could not be resolved: 'usher.twitch.tv'`

This means you cannot connect to the server because of network issues. Maybe because of your internet connection, maybe because the Twitch servers have a problem currenty but this definitely has nothing to do with the Twitch Leecher version.

I recommend waiting a couple hours or a day and try again. Twitch servers are not known for being the most stable in the world. Some patience and all will be fine again.

**Comment by pooiyx** [comment]
Thanks for the fast reply. 
My ADSL internet connection is quite bad and often disconnects for short periods, but this hasn't stopped TL from being able to download multiple queued videos successfully in the past, and I've been using TL for many months already. Usually, Errors occur only when my internet is down for a prolonged period. 
I've only noticed TL downloads failing more often since I updated to the latest version. I'm thinking that even very short periods of my internet being down are causing failed downloads now.
