### ISSUE TITLE
Getting HTTP 403 error when trying to link Twitch account

### ISSUE THREAD

**Issue by ClefAria** [Franiac/TwitchLeecher#270]
I get this error message after clicking the Twitch icon, putting in my username and password, and clicking "Log In".

I'm using Twitch Leecher 1.5.2, which I have just updated to, if that makes any difference.

[Screenshot of error message](https://i.imgur.com/fTGIEMu.png)

**Comment by Franiac** [comment]
See #178

**Comment by ClefAria** [comment]
I've had Internet Explorer disabled in my Windows 7 as long as I can remember (See "Internet Explorer 9" unchecked here: https://i.imgur.com/BITaokj.png ), so I guess that's why. I ended up getting it to work by following some other user's tip that I found, that involved me getting the token and manually inserting it into the runtime.xml file, lol...

Are you able to have the program run a standalone Chromium or something for this, so that users like me don't run into problems?

**Comment by Franiac** [comment]
Chromium (CefSharp for Example) is over 120mb big. TL without ffmpeg would be <2mb, with ffmpeg 23mb. I do not jump from 23 to 143mb just because of the sub-only login screen, I think that is understandable.

What I do have in mind, though, is the re-write of the entire GUI to HTML because I hate WPF for lightwight GUIs like TL has. If that's the case I will have to introduce Chromium and the problem would solve itself automatically.

Maybe... if the APIs get a little bitte better I'll switch to Electron completely. But for now the HTTP API is not sufficient.
