### ISSUE TITLE
Improve/Change Twitch Leecher Shortcut

### ISSUE THREAD

**Issue by EpicLPer** [Franiac/TwitchLeecher#284]
Currently the Twitch Leecher installer always creates a new shortcut for each new version in the start menu with the version in the shortcut name. However this breaks shortcuts that were dragged to the desktop and the old shortcut in general.

Please make a normal shortcut which simply points to the EXE instead of the current non-standard way of launching Twitch Leecher via the shortcut to prevent it from breaking and still functioning after an update, maybe even remove the version from the name and move it to the Window title instead.

**Comment by Franiac** [comment]
I see the issue but this is easier said than done. The shortcut gets automatically created through the MSI installer. It is nothing I personally have implemented (I would have done better).

I must take a look into the installer mechanics and see if I can hook myself into it to do things properly. I am annoyed myself by this behavior.

**Comment by Franiac** [comment]
Windows Installers are a p... in the a..

Plain MSI is unusable because cool GUI's are not possible. So I use WiX Toolset and it's Burn Engine in order to launch a managed .NET GUI that handles the installer. The backend, though, is still MSI (must be on Windows). WiX has the ability to implement so called "Custom Actions" that get executed during the installation stage. This is where the money's at.

Changing the installer is not an option because a better free installer than WiX is not available. Everything else is either utter crap or available for a very high price.
