### ISSUE TITLE
full download but messed up video After convert, request option to not convert after merging

### ISSUE THREAD

**Issue by randomname42** [Franiac/TwitchLeecher#293]
https://www.twitch.tv/videos/279931567

(The vod will be automatically deleted in a little under 2 weeks. Sorry this got so long but I think the details will be helpful.)

That vod fully downloads (720p 30fps, NOT source, TwitchLeecher 1.5.3) but after the conversion to mp4 it ends up all wrong. The converted video is twice as long as the time listed for the vod. Audio desynchs quickly, gets farther off as the video goes on, and finishes long before the video playback.

While it was converting I happened to be at the pc and saw conversion was going up past 100%. I think it got to over 150%. Probably 200% (because the video is twice as long as it should be).

I got the feeling that might something would be messed up in the converting. I made a quick decision to copy the merged .ts file while it was converting, just in case. 

Fortunately I had time for that to copy completely while the conversion happened. What's really funny is that the merged .ts file plays back fine. Nothing wrong with the pre-merge .ts file, at all.

So, I do have a playable copy of the vod. But if I hadn't been at the pc and happened to catch the conversion going well over 100% (which I've never seen before) I would not have ended up with a playable video in the end.

Suggestion: A check to see if conversion does anything weird (like go over 100%, or not reach 100% before it finishes). And in that case, _don't_ delete the merged .ts video. Just move it to the location for completed downloads. Because that .ts may still be fully functional even though the converted mp4 may have gone wrong, and having a playable .ts video is infinitely better than having no playable file.

A manual option to not delete the merged .ts (in case you notice something off during conversion that TwitchLeecher doesn't) could be helpful too. That would have to be something that could be turned on/off while a download is going/processing.

Btw, I mentioned not reaching 100% in the conversion because I think that may have happened sometimes in the past. The vods are deleted now, but (too late) noticed that even though they had fully downloaded with no error, the resulting mp4 were way, way shorter than the vod lengths. And the mp4s were much, much smaller than the amount that was downloaded.

So I'm 99% sure it's possible for a vod to fully download, but then the conversion results in a massively shorter video than what was downloaded. That's very rare, of course. But that's why I mentioned the under 100% check. 

I just had another idea. Maybe there could be a size check: **downloaded amount/merged .ts file size** _vs_ **converted mp4 file size**. And if those aren't pretty close, then don't delete the merged .ts because something in the conversion probably went very wrong.

**Comment by TSLMachine** [comment]
Something like this just happened to me as well, downloading a 1080p60 source VOD with 1.5.3. I suggest having the app automatically make a copy of the .ts files after the download finishes to then be merged and converted. If the processes succeed, maybe have an option to preserve or automatically delete (as it is right now) the temporary files. If any of the processes fail, the "Retry" button should retry merging/converting by making another copy of the original .ts files then repeating the process instead of trying to download the whole thing again. I have no idea how easy/hard this would be to implement though (not to mention any possible concerns adding a feature like this could make), just throwing the idea out there. Cheers, dude!

**Comment by Franiac** [comment]
It seems to me that this issue is rather uncommon. But let's start off one by one:

If the processing stage goes above 100% FFMPEG has already failed. If FFMPEG fails there is nothing I can do about that. Either FFMPEG manages to process the video or not. There is nothing in between. 

What I surely won't do is any of the above mentioned hacks like checking if it goes above 100% or if the output is shorter/longer than the input and so on. Not only would it be super bad programming but also not consistent. Noone knows if it does the right thing in a certain situation because even the situation is unclear. For example when comparing sizes... what would a threshold be, a converted mp4 doesn't necessarily have to have the same-ish size compared to the original ts file, yadda yadda yadda. No, we can stop here, won't happen.

When I implement something it must be consistent and has to do the same thing ALWAYS, everything else results in a software that noone understands because noone knows when things happen.

My solution:

1. Wait. As stupid as it may sound, just because 2 people of >300000 users had the problem, does not mean it is a common thing. Before I change the core functionality of TL I want a good reason to do so. 2 videos that don't work are NOT a good reason. If we have e.g. a channel that is set up properly where videos are not downloadable repeatedly, that would actually get my attention (as in: Thinking about implementing a fix). Twitch videos are somewhat tricky because they depend heavily on the streamer's encoding settings and Twitch's transcoding process. That's why some videos work and others don't. We will never see TL downloading every single video without any issue, that's just impossible.

2. If I decide to implement something it would be the following:
Make an option that says "Convert video to mp4 after download". That would be enabled by default, so everything would behave the same. If you uncheck it, only the merges ts file goes straight to the output directory. If you check it, then there would be a sub-option that says something like "If the conversion fails, copy the ts file to the output directory". So let TL try to convert, if it fails, copy the ts file.
Or wen could go the "tell me what do do"-route. If the first option is checkt you can choose what to do, if the conversion fails, either copy the ts file or error out without doing anything.

But first I choose option solution 1. You can post every video url here that has an issue like @randomname42 mentioned. I keep track of it.

**Comment by Franiac** [comment]
Maybe dropping ffmpeg completely... see #311

**Comment by Franiac** [comment]
Closing -> Issue is on private waiting list
