### ISSUE TITLE
Download file is out of sync :( 

### ISSUE THREAD

**Issue by s1leviathan** [Franiac/TwitchLeecher#296]
Hello , i just wanted to mention that 4 out of 5 clips that i download no matter what resolution i choose the clip will lag for 1 second at the beginning and than the sound will be out of sync with the video .
Any ideas or solutions ?
Thanks

**Comment by JIMAO233** [comment]
Half of my VODs are out of sync too, I really need to know why :(

**Comment by Franiac** [comment]
Please be more specific when posting issues.

Read [THIS](https://github.com/Franiac/TwitchLeecher#support--issues)

In addition to all those points, what video player are you using to play back the video? My first advice is always to try VLC because a lot of players have huge trouble playing back Twitch streams.

**Comment by Franiac** [comment]
Closed because stale
