### ISSUE TITLE
More Options for Processing

### ISSUE THREAD

**Issue by shkalak51** [Franiac/TwitchLeecher#303]
Just suggestion.

As far as I know, twitchleecher uses ffmpeg for processing lots of .ts files.

For nvidia users, it can be much more faster if it is processed through nvenc, and ffmpeg can make it.

Also, mkv muxing can be helpful for faster processing.

It would be great if these were supported through selective options.

**Comment by Franiac** [comment]
I am not a ffmpeg pro but NVENC is Nvidias encoding library. Twitch Leecher does not encode anything. It takes a ts source file and packs it into a mp4 container. That is nothing NVENC can do or even speed up. The source streams and codecs are copied to the target container 1:1 without re-encoding the video (that's why TL takes minutes and not hours or days for the processing stage).

I don't understand what mkv muxing is supposed to do better compared to the current processing. We don't handle mkv files, we transform ts to mp4. What would be the advantage of using mkv as an output format?

**Comment by shkalak51** [comment]
Thanks a lot.

I knew twitchleecher was re-encodeing all files. ^^

1:1, no problem
