### ISSUE TITLE
Video audio not sync using 1.5.3 if the stream lagged too much while it's fine using 1.4.3

### ISSUE THREAD

**Issue by AlexOuO** [Franiac/TwitchLeecher#306]
Greetings developer.
I wanna thank you for making this amazing software.
I'd like to provide informations for you to address the issue.
Audio downloaded using **1.5.3 is not sync even playback using VLC player** while the video downloaded using 1.4.3 is fine.
**Audio hasn't been sync since the stream lags very much.**
For example:
https://www.twitch.tv/videos/336561039
timestamps :  00:30:51
When the streamer tried to switch to back camera,it lags very much. ( Bad internet connection)
After that point,the video downloaded using 1.5.3 is not sync and the video playback in fast speed itself.
It happened not only to this stream. If the stream lags too much , it happens using 1.5.3.
Another one:
https://www.twitch.tv/videos/322036438
timestamps :  00:47:44

OS:Win10 64 bit 1803
I hope the information is useful for u .

**Comment by Franiac** [comment]
The only difference between 1.4.3 and 1.5.3 is the ffmpeg version. 1.4.3 had version 3, 1.5.3 has version 4 now. There were absolutely no changes to the processing stage other than that. Maybe it's a fault in ffmpeg 4.
In gereral, I don't look into such lag issues. If the streamer uploads a stream in shitty quality and with framedrops it is not TL's job to fix it. FFMPEG is ultra-sensitive about framedrops and inconsistent video streams. If ffmpeg fails at processing the video, I cannot do anything about it. And I am surely not going to revert to version 3 because of it since version 4 runs much faster. So that's the compromise I guess.
I am sorry that I cannot help but the only thing to fix it is the streamer herself. She has to provide a good stream, then TL is happy and then the TL users are happy. TL is a shit in/shit out program. I am a software developer, not a magician, unfortunately 😄
