### ISSUE TITLE
Downloaded on Mac, what do I do

### ISSUE THREAD

**Issue by Fulza** [Franiac/TwitchLeecher#308]
When I downloaded the software, I got this folder and now I don't know which file to open to finish the download/turn it into an application

![screen shot 2018-12-11 at 10 47 37 pm](https://user-images.githubusercontent.com/45809949/49847652-cd888c80-fd96-11e8-9391-30cd0312b745.png)

**Comment by Franiac** [comment]
Twitch Leecher does not support Mac or Linux

**Comment by Codereaders** [comment]
On Linux / Mac there's quite a few cli applications. There are two that I know:

* [youtube-dl](https://github.com/rg3/youtube-dl/)
   Don't worry, the name is misleading. It downloads from Twitch as well.
* [concat](https://github.com/ArneVogel/concat)
   The developer used to run a limited web service to download from Twitch.  
   This application is written in go and does not have any limitations in compare to the web service.

And the list goes on.

To be fair TwitchLeecher is very comfy due to it's gui, but cli applications could also be kind of attractive.
