### ISSUE TITLE
Add in chunking to videos

### ISSUE THREAD

**Issue by RyanTheAllmighty** [Franiac/TwitchLeecher#31]
Might not be the right term for it, but I like to watch past vods for streams and this tool is great, but I like to split them up into 1 hour sections so that I can watch a single video on train to and from work.

At the moment the time settings when downloading a video is great, but would love to be able to simply set it to download an entire vod and say cut it into x minute segments and it will pop out 'Filename_{part}.mp4' for instance.

Just a suggestion that maybe some others might also find handy, regardless of if this is something you decide to add on, thanks for making a great tool :)

On a side note, is there a reason why I cannot queue up the same video? I'd like to if the above isn't added, be able to queue up all the parts myself using the existing time settings but it doesn't allow me to add the same video to the queue more than once.

Thanks

**Comment by Franiac** [comment]
I think splitting the download into chunks of a specified length is not a use case that is very common. But you should be able to queue multiple downloads of the same video. This is new, because it made no sense when cropping was not available (why should i download the same video twice when there is no time selection...).
So I added the capability to queue multiple downloads now. The temporary folder now gets a GUID instead of the Twitch video ID.

**Comment by Franiac** [comment]
Fixed!
