### ISSUE TITLE
A/V Desync on resulting mp4

### ISSUE THREAD

**Issue by Abalieno** [Franiac/TwitchLeecher#311]
I was having the same problems reported here:
https://github.com/Franiac/TwitchLeecher/issues/306

You (the developer) say the old version used an old build of ffmpeg, so I installed the Twitch Leecher 1.4.3, verified that it solved the problem, then installed 1.5.4 and overwrote the new version of ffmpeg in the program folder with the old one.

I thought this allowed me to use the new program version while retaining the fix. In fact it all works, and the chunks are indeed correct before they are merged.

But the final .mp4 still had the desync issue.

What I found out is that the download of the chunks is fine, for both the old and the new version. I've verified those chunks, they are identical for both versions of ffmpeg.

What causes the sync issue then depends on the command line you use to merge them into a single file.

And again, it cannot be ffmpeg itself because I manually overwrote it in the newer version of the program with the old one and its behavior is identical. Since it's ffmpeg (I think) that takes those chunks and merges them, and those chunks are the same (checked them with crc, they are identical), and ffmpeg itself is the same, then it's your program that triggers this problem, in some way.

Looking at the logs there seem two be two cases where the problem might be:

1- Creating local m3u8 playlist for FFMPEG... done!

2- The following command line differs, in the old version it is:
-y -i "X:\Twitch\blabla\vod.m3u8"
in the new version it is:
-y -i "X:\Twitch\blabla\filename.ts"

I think the new program essentially skips the creation of that m3u8 playlist, and so it misses some of that data when merging files.

...and this is likely where it happened:
https://github.com/Franiac/TwitchLeecher/commit/0bf97f88abeaab0a1077adaa34cd246c77335ecb

I don't know if ffmpeg is fixed and maybe the old behavior of Twitch Leecher fixes both problems, but could you patch that code back into the program and maybe give an option to toggle between one or the other?

**Comment by Abalieno** [comment]
Yes, if that's the case add an option on download before processing the file and deleting the chunks, so one could select one way or the other if the output has some problem. You don't have to rewrite anything, just keep both options enabled.

You could add an option to simply merge the file into a .ts, OR do the current conversion to mp4. Just make it optional.

I'm not an expert of video conversion but you can probably look into those tools, they usually are command line based like ffmpeg. You don't really need to convert anything, ts mp4 and mkv are only containers, so switching from one to the other usually only requires to demux the audio/video streams from the current container and then remux them into the new file. On Windows there are command line tools I usually use with some GUIs, like MKVToolNix and mp4muxer.

I just wonder if that m3u8 is required to make it work somehow. But you can try just merging the .ts and we'll see if the output is still fine?

I know the chunks are in sync but I don't know if the move into a ts format somehow alters how those files are handled. It's unlikely but it needs to be tested.

Your program is fine, we just need to figure out the best solution with this conversion. I could make a few experiments (but all my cases are fixed with the old process, so I don't know those cases where it's the old process that creates problems). 

Could you write me all the command line commands you give after all the chunks are downloaded, and till the end?
If you give me these commands I could see on my own if there's a command to give ffmpeg that fixes the desync while still using the newer conversion.

**Comment by Abalieno** [comment]
Something new.

I brutally closed the program when it finished getting the chunks so I could use them manually.

Then I gave a simple: copy /b *.ts new.ts

The output is... interesting.

If you seek the file on a media player it stays in synch until the very end. But if you actually watch a moment where there's frameskipping the video jumps right ahead and the desync happens. It gets fixed if you manually jump at a different time. 

So when you merge this output through ffmpeg it also automatically resync with the video stream (and so it breaks the timing).

This means neither works, even when simply joining those "*.ts". Only the old method gives the right output, and that's through the use of the original m3u8 (you need to give me those command lines the old version was using, so I can test it some more).

**Comment by Abalieno** [comment]
I've also tried taking the joined .ts, covert to mkv, then convert the mkv to mp4.

ffmpeg_x64.exe -i current.mkv -c copy new.mp4

It's a bit convoluted but this produces a working mp4.

**Comment by Abalieno** [comment]
Probably last update for now ;)

ffmpeg_x64.exe -i current.ts -copyts -c copy new.mp4

This produces a good mp4 from the joined ts. The option "-copyts" basically copies the video stream without adjusting the timestamps, so the result is that there's no desync.

You just have to verify if this works in all cases. Could you add that command line option to the ffmpeg command for now?

**Comment by Franiac** [comment]
Btw. I will introduce a debug option for people like you so that the downloaded files do not get deleted after the processing stage. So you do not have to kill TL via task manager and such...

**Comment by Abalieno** [comment]
That's why it's weird, I was using a test video that had frequent big drops since it was streamed from a cellphone during a convention, but the video is always complete and is processed by ffmpeg just fine. The problem is only the desync because while the audio is smooth the video instead stops. When ffmpeg processes the file those missing parts are skipped, making the video jump to the next sequence immediately, and by the end of the duration the video is already over long before the audio (because the missing frames have been entirely removed, making the video stream shorter than the audio duration).

In theory if the binary joint of those ts works even in those cases, then even the conversion to mp4 should be fine for all cases when using "-copyts". I thought the big problem might have been about the download of the source, but if that works then there's always some way to process the output properly. If it works from the browser then it has to work even in a player.

The problem of making a test list is that Twitch keeps the files only for two months. So you'll have to target some of those few that are static, if you know some of them that are problematic.

**Comment by Abalieno** [comment]
As far as I know Twitch deletes the streams after two months. I think you can manually flag them so they are archived permanently, but in general even your program only shows the last two months of a channel.

I guess you can still make a list of those few static videos.

**Comment by Franiac** [comment]
That my be related to cropping. ffmpeg uses the -ss and -t commands and I honestly don't know how these whole timestamp shenanigans work. meybe the above mentioned -copyts option solves this problem also. We have to test all this... but ey... not today, right? Now let's have some champagne and celebrate the new year!

**Comment by Franiac** [comment]
Now I digged into the closed issues and found these VODs that had problems with hickups, ffmpeg crashes or A/V desync:

https://www.twitch.tv/videos/120958751 (04:00:00 to 04:20:00)
https://www.twitch.tv/videos/118751680 (03:00.00 to 03:10:00)
https://www.twitch.tv/videos/117288629 (02:45:00 to 02:57:00)
https://www.twitch.tv/videos/336561039  00:30:51
https://www.twitch.tv/videos/322036438  00:47:44

BAD THING: They are ALL not available anymore, so we start basically at zero 😞

**Comment by Franiac** [comment]
Update:

Since I have started streaming again and I drum to various licenced songs, big parts of my broadcasts get muted. Alongside it seems that even in the Tiwtch player the parts after a muted part gets A/V desynced to hell and back again.

At the start before the first muted part everything is fine:

https://www.twitch.tv/videos/373521126?t=15m36s

After the first muted part:

https://www.twitch.tv/videos/373521126?t=25m09s

I think at the moment a video contains muted parts the whole A/V dysinc discussion is worthless. It just won't work. If not even Twitch can handle their stuff correctly, how is TL supposed to download things right?

**Comment by Abalieno** [comment]
Just change the things we discussed and we'll see.

Those sample videos look fine. There's some minor desync, but the foot drum thing seems always correct? I don't know, it might not even be an encoding problem, maybe you got it while mixing different cameras and whatnot. The big camera lags half a second later, but the small one in the corner doesn't. So if that's the case then the video itself is not the problem. In any case it seems minor.

**Comment by Franiac** [comment]
I have digged into ffmpeg some more and now understand what actually causes the A/V desync and why it is sometimes ok in the browser but not ok when downloading with TL.

If the video stream is shorter than the audio stream within the original ts file, that is most likely because the sreamer dropped frames. Missing frames are not "substituted by emty or repeating frames" like a lot of people might think. So the logical result is that over time the A/V desync gets worse and worse. The amount of how much shorter the video stream is in regards to the audio stream determines how big the A/V desync is.

Web browsers fight this issue in real time on playback by speeding up or slowing down video playback to guarantee gapless audio. ffmpeg cannot do this.

I found a very old thread where this was discussed:

https://trac.ffmpeg.org/ticket/4674

Now ffmpeg provides a parameter called "-async". The documentation says:
```
-async samples_per_second
Audio sync method. "Stretches/squeezes" the audio stream to match the timestamps, the parameter is the maximum samples per second by which the audio is changed. -async 1 is a special case where only the start of the audio stream is corrected without any later correction.
Note that the timestamps may be further modified by the muxer, after this. For example, in the case that the format option avoid_negative_ts is enabled.
This option has been deprecated. Use the aresample audio filter instead.
```
So basically this is the opposite of what browsers are doing. The audio gets rearranged, not the video stream. Now the async parameter is deprecated (but still there) and was substituted by the "aresample" filter but that's not important. Important is that the parameter didn't help at all.

I found a sample video with A/V desync:

http://samples.ffmpeg.org/ffmpeg-bugs/trac/ticket4720/

This file runs perfectly fine in browsers and VLC. First I tried to run it through ffmpeg the same way as TL does:
```
ffmpeg -y -i input.ts -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc output.mp4
```
This results in a totally out of sync mp4. Then I added the async parameter:
```
ffmpeg -y -i input.ts -async 1 -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc output.mp4
```
This did NOTHING. Now why is that? Because we are copying the audio stream with
`-c:a copy`
directly to the target, d'oh! No filters are run on the audio stream in this case.

Now I deleted the "-c:a copy":
```
ffmpeg -y -i input.ts -async 1 -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc output.mp4
```
This resulted in a perfectly synchronized mp4!!!
It takes a tad longer because the audio stream does indeed get resampled and encoded but only like half a second.

The story does not end here, though. I wanted to see if the async parameter actually did anything, so I just deleted it and ran
```
ffmpeg -y -i input.ts -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc output.mp4
``` 
And it still worked!! So the only thing different to the original ffmpeg call in TL is the missing
`-c:a copy`
I guess that internally ffmpeg stretches or shrinks the audio so that it matches the video stream by default.

It would be very nice if someone could confirm all that 😄 
If this actually works, it is a really big thing for the quality of TL.

I have to test it on various VODs on Twitch, though.

**Comment by AlexOuO** [comment]
There're many outdoor streaming that encounterd severely bad internet signal.
Although I vods I mentioned are unavialable now, you can find more.
Here's one that I download using TL 1.5.5 .Starting from 22:28, it lags too much and then the video is broken.
https://www.twitch.tv/videos/383209113
I find it for u to test. Glad to help.

**Comment by Franiac** [comment]
@AlexOuO Stream lags are a different topic. We are discussing AV sync here. FFMPEG won't process video streams with that many and heavy dropouts. There is no solution for your problem. FFMPEG cannot repair such a bad stream. Shit in => shit out 😄
