### ISSUE TITLE
Default download folder doesn't detect remapped folder

### ISSUE THREAD

**Issue by Peter92** [Franiac/TwitchLeecher#321]
I have remapped a few folders such as documents and downloads to a separate drive, the majority of software will be able to deal with it, but yours doesn't yet have the functionality.

The default location that is displayed for me is "C:/Users/Peter/Downloads", where technically it should be "D:/Peter/Downloads". Not a huge problem but I was left wondering where my download was for a minute or two.

I've only tried for the correct documents path in Python, but it was doable with the windows "SHGetFolderPath" function.

**Comment by Franiac** [comment]
I don't get what your issue is, actually...

You told TL to save the video in "C:\Users\Peter\Download"... so TL does exactly that.
It has absolutely nothing to do with how you redirect the "Downloads" folder in Windows Explorer.

If you want TL to save the video in "C:\Peter\Downloads" you should click the "..." button and select "C:\Peter\Downloads" instead of "C:\Users\Peter\Downloads" or hop into the TL preferences and change the default download folder there.

TL does exactly what you told it to 😄

**Comment by Peter92** [comment]
I didn't tell it to download there, the point I was making was that the default download location of `%USERPROFILE%/Downloads` is not always correct, such as if the download folder has been moved.

It's only a minor issue anyway, just thought I'd let you know.

**Comment by Franiac** [comment]
Now I finally get what you mean. But again, the default download folder cannot be depentent on the Windows Explorer Downloads folder redirect setting since there is no %DOWNLOADS% for example. That would actually be cool. I don't have a convinient way of reading the redirect path. I don't say there is none, but the question is if it is really necessary.

Here are the environment special folders .NET supports:

https://docs.microsoft.com/de-de/dotnet/api/system.environment.specialfolder?view=netframework-4.7.2

There is everything available EXCEPT the "Downloads" folder...

As you realized TL specifies %USERPROFILE%\Downloads as the default folder and that is ok. No matter what you redirect the Downloads folder to, TL will always use %USERPROFILE% as the base folder.

I get that this might be annoying for somebody that redirects the download folder but 99.9% of all Windows users don't do that and according to that TL hits the correct path 99.9% of the time. Most users probably don't even know about that option 😄 

And for the other 0.1%... whoever redirects the DL folder in Windows I define capable of also changing the dwonload folder in TL.

**Comment by Peter92** [comment]
I gave it a very quick google out of curiosity, it seems you can give the ID `{374DE290-123F-4565-9164-39C4925E467B}` to `SHGetKnownFolderPath` to get the correct location. Dunno how easy or not it would be to do, I only really know Python and it looks a little hacky in it :P
