### ISSUE TITLE
[Feedback]Video audio is in sync using Powerdirector or Premiere

### ISSUE THREAD

**Issue by AlexOuO** [Franiac/TwitchLeecher#326]
My OS: Windows 10 Home 64bit 1803
The streamer was using streamlabs and Samsung S10.
Stream Video info:(downloaded and check it via "Mediainfo")
Length: 3 Hrs 43 Min
Variable bitrate
Video bitrate: 2826kbps ( I guess the streamer set the bitrate to 3500kbps)
**Variable frame rate**
Video frame rate: 24.258FPS ( I guess the streamer set it to 30fps)

Downloaded using TL1.5.5 and imported to Power Director v17 64bit
-Result: Video and audio **is in sync** perfectly
Downloaded using TL1.5.5 and imported to Adobe Premiere Pro CC 2019/2018
-Result: Video and audio **is NOT in sync** , It's in sync during first 1/4 part. Getting not in sync after        1/2, the longer the video , the more desync. 
Downloaded using TL1.4.3 and imported to Power Director v17 64bit
-Result: Video and audio **is NOT in** sync . It's horrible.
Downloaded using TL1.4.3 and imported to Adobe Premiere Pro CC 2019/2018
-Result: Video and audio **is NOT in** sync. It's horrible.

Conclusion:
-For video editing,download twitch video using TL1.5.5.
-Using TL1.4.3 only when the stream was encountered serious lag and the video downloaded is broken. TL1.4.3 can fix it cuz the FFMPEG is older.
-PowerDirector is very good for editing twitch video.

My editing video solution:
I use Adobe Premiere Pro CC 2018. There's a feature called "Preserve audio sync" since v12.1.x
However,downloading using TL1.5.5, there're chances that Pr2018/2019 can't "Preserve audio sync" precisely.  Some videos CAN, some vidoes CAN'T be in sync through entire video.
I will have to re-encode the video to "Constant Frame Rate" video using Handbrake and then import it to Premiere and it's perfectly in sync.
I know TL doesn't encode the video.However the FFMPEG version is not the same so the way it merges video is not the same too so the video is not technically the same too , right ?
It's just the info feedback article. Hope it can help you guys cuz I was struggling with this mess.

**Comment by Franiac** [comment]
First of all Premiere still has serious issues with Twitch streams. Probably all of the above mentioned attempts work flawlessly in Sony Vegas. But there is something that makes the whole discussion senseless because the streamer went with a variable framerate. This is a nogo on Twitch and can even cause A/V deysnc when transcoding live. So maybe in this very special case where  it works like you say but tomorrow there's another video where it is all different. Streamers should read the Twitch how-to's on how to set up their streams properly. Then TL would have a lot fewer problems to deal with.

FFMPEG has nothing to do with the outcome. It's the way TL either merges the playlist into a single file first or not. In addition to that I experimented with ffmpeg command line arguments quite a bit. You should read my second last comment on #311 

But like I said, making conclusions on a badly set up stream doesn't mean anything 😄
