### ISSUE TITLE
main window suddenly doesn't come up

### ISSUE THREAD

**Issue by jbd64** [Franiac/TwitchLeecher#327]
Hi,

app version is 1.5.5, Windows 7 x64 SP1, NET FW 4.7.03062

App was running fine for some time, now it starts, but its window doesn't come up. Process is visible in task manager with some 30-35MB RAM & 0% CPU (at start it shows some CPU activity and goes to idle 0%), no issues etc are visible under event viewer. Windows is updating automatically, so it might have to do something with it. I've reinstalled the app, tried version 1.5.4, tried repair of NET FW, but to no avail. NVIDIA Graphic driver is 8.1.940.0, no gaming/clocking apps. AV is Symantec End Point.
Further, I found a restore point of the app, which crashes instantly with a "P9: System.IO.FileNotFoundException" message in event viewer, "Faulting module path: C:\Windows\system32\KERNELBASE.dll" and a .NET Runtime Error message "Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileNotFoundException". However this occurs only when I start the app from the restore point.
I've tried copying d3d9.dll & kernelbase.dll to TL folder, but didn't help.

Any suggestions what I could try next to fix this issue?

**Comment by Franiac** [comment]
This looks like a graphics card driver issue since TL is a .NET WPF application and WPF is rendered on the graphics card. Though, I don't have any clue what would cause your problem. Since TL did not receive any UI related changes for over a year it must be something on your machine. But that's not something I can remote-debug, unfortunately.
