### ISSUE TITLE
Feature Request - Audio Only

### ISSUE THREAD

**Issue by drderiv** [Franiac/TwitchLeecher#336]
Any chance a selection could be added to the Quality drop-down in the Download Video dialogue that facilitates Audio Only output (perhaps with the election of an encoding rate)?

I realize a similar request had been previously made, but in looking at that request, it appeared that the idea was to grab the audio stream only from Twitch.  I'm not suggesting that.  Rather, I'm suggesting doing nothing different in obtaining the source material from Twitch, but passing the "-vn" option to FFMPEG so that it does not output video (thus, it only outputs audio).  Yes, it's inefficient from a download bandwidth standpoint, but it ultimately creates a much smaller output file for those who only wish to listen to a broadcast.  And that should make it relatively easy to implement, with the only real change being to command line arguments passed to FFMPEG.

**Comment by garoto** [comment]
```
ffmpeg -i <my_wasted_4gb_of_bandwidth.mp4> -vn -c:a copy file:<finally_my_100MB_of audio.m4a>
```

**Comment by Franiac** [comment]
Ooooof.... I get the idea...

But you probably know that the VODs are super big and downloading like 10GB in order to get a 20mb mp3 or something sounds like absolute nonesense to me.
I mean implementing such a feature knowing it's shite hurts already, but here's another thing that may cause trouble:

An user chooses "Audio Only" from the dropdown and starts downloading a VOD thinking "yey, audio only" through a volume-based internet connection (and there are lots of users who do that) and at the end of the month heads hit tables....

One could implement a warning but...

1. the normal user does not read warnings -> experience in software development right here :)
2. Implementing a feature that needs a warning to use is not a good idea in the first place

I am not a fan of this to be honest. I hate implementing workarounds for stuff that should not be there anyways. I wish Twitch didn't remove the audio only option, that was a dumb move but I can understand them. They only provide video sources so why would they provide audio only downloads....

Maybe you could head to the Twitch developer forums and make a request to re-implement audio only streams into Helix again and see what they have to say.

I want to work WITH the Twitch API not against it. I hope you understand :)

**Comment by drderiv** [comment]
No worries.  Thanks for considering it, responding, and open sourcing the code.  I've already made my own version (by just editing the binary for TwitchLeecher.Services.dll, since I don't have a C# compiler already set up) that outputs an audio-only file and it works great.  Resulting file is only 15% of the size of the video-included mp4.  Fast to transfer to my phone and easily fits so I can listen on long drives.

I agree that it's unfortunate that Twitch removed the audio only option, but for those of us with AYCE bandwidth via cable modem but a limited phone plan, it's the most efficient way.  I'll try to take up your suggestion and make a post on the Twitch developer forums to address this.  With the popularity of non-gamer content on Twitch increasing, audio only is more relevant now than it may have been previously.
