### ISSUE TITLE
Audio Still Fails to Sync

### ISSUE THREAD

**Issue by PepperMint72** [Franiac/TwitchLeecher#353]
Audio still randomly fails to sync in leecher ver 1.5.6, unlike the description written in the release. Some of videos successfully sync, but the problem is unsolved yet.

**Comment by Franiac** [comment]
And it will never be fully solved since there are too many variables that can cause A/V desync. We tried everything to make TL as stable as possible in the audio department but there are no more knobs we could turn. Every new attempt would make it worse. I know it is not a satisfying answer, but there is nothing more we can do at the moment.

Most A/V desync issues are caused by the streamers themselfes. TL tries to fix most of them but cannot catch any mistake they make.
