### ISSUE TITLE
Video getting out of sync with audio.

### ISSUE THREAD

**Issue by Flondorak** [Franiac/TwitchLeecher#366]
Hi. I've recently came up to this issue, that when I'm downloading like 2hours+ long videos, the audio gets out of sync. But, this only happens after it gets converted from .ts to .mp4. If I copy the .ts file before it gets converted, everything is fine. I am using the latest version and have completely reinstalled the app.

Am I doing anything wrong? 

Thank you.

**Comment by Flondorak** [comment]
I know, there are alot of those things already closed, but I figured it gets out of sync after the app converting it.

**Comment by Franiac** [comment]
Sure, that is exactly what a lot of the closed issues say. FFMPEG does not manage to convert the video/audio properly depending on the source material. So nothing new here.

I will introduce an option where you can disable the conversion to mp4 because most video programs can handle .ts files nowadays.

**Comment by Flondorak** [comment]
Yeah, that would be great. Thank you so much for making this app possible! :)
