### ISSUE TITLE
Wrong download link

### ISSUE THREAD

**Issue by Modiseus** [Franiac/TwitchLeecher#370]
Twitch Leecher 1.5.8 informs me that the new version 1.6.0 is available.

It gives the link https://github.com/Franiac/TwitchLeecher/releases/tag/v1.6 but this link is invalid and should probably be https://github.com/Franiac/TwitchLeecher/releases/tag/v1.6.0

Screenshot:
![Twitch Leecher Screenshot](https://user-images.githubusercontent.com/6494883/62011703-16e9e880-b17c-11e9-9a53-c808506ccde6.png)

Operation system: Windows 10 64bit

**Comment by Franiac** [comment]
Fuck... thx

**Comment by BubiBalboa** [comment]
Same problem with the latest release.

**Comment by Franiac** [comment]
@BubiBalboa what?

This is fixed in 1.7.0 and since there is nothing higher than 1.7.0 you probably never saw the 1.7.0 update dialog...

**Comment by BubiBalboa** [comment]
I saw the update dialog from 1.6 to 1.7 which 404ed for me.

**Comment by Franiac** [comment]
Like I said, the bug is fixed in 1.7.0

**Comment by BubiBalboa** [comment]
Good job.  👍

**Comment by Fattony12000** [comment]
Busted for me in 1.7.0 still:

**Comment by Franiac** [comment]
Guys, how freaking difficult is this to understand???

It is fixed in 1.7.0.... That means whenever there is an update to 1.7.1 or 1.8 the update dialog of TL 1.7.0 will work correctly. I KNOW that the dialog is wrong in 1.6.0 presenting you the wrong link, but the bug was discovered AFTER 1.6 was released.

LOCKED
