### ISSUE TITLE
Download parallelism and concurrency

### ISSUE THREAD

**Issue by Kaszanas** [Franiac/TwitchLeecher#387]
I have just recently started downloading bigger batches of videos.
This resulted in couple of simple features which might be introduced to significantly improve performance of the software:

1. Downloading videos simultaneously - This might be useful due to the current processing pipeline used within the software which is Download -> convert (if I understand correctly). Instead of that if there would be a way to download 3 videos at a time it would improve the use with higher bandwidth networks.
2. Downloading next video when the one that was downloaded is processing. Currently the bottleneck within software is happening when a video has downloaded and needs to be processed which slows down the overall capability of downloading bigger batches of content.
3. Batch download all the videos added to the search section of the software with custom settings or with default settings which are the source (highest) for every added video.

Overall the software works perfectly and is state of the art. Unfortunately I am more familiar with Python than C# so I am unable to effectively help in the regards mentioned above.
I hope this helps!

**Comment by Franiac** [comment]
This will be all possible when #46 is done.

Parallel download is already implemented but not obvious. A single VOD consists out of let's say 11000 parts. All those parts are downloaded in parallel batches of 10 at a time. So downloading multiple VODs "in parallel" does not improve download speed since the count of parallel batches would stay the same.
