### ISSUE TITLE
SSL/TLS error returns

### ISSUE THREAD

**Issue by rik130** [Franiac/TwitchLeecher#389]
https://github.com/Franiac/TwitchLeecher/issues/183

This 'fixed' issue is no longer fixed as it's back again and no videos can be downloaded.  Eg. https://www.twitch.tv/videos/492320271?filter=archives&sort=time

**Comment by Franiac** [comment]
Not true on my end. I can download the given VOD without any problems.

**Comment by rik130** [comment]
I've just tried it again and it's still giving me a SSL/TLS error.  The only thing that's changed at my end is I ditched my Sky ISP landline connection and now use EE 4G mobile internet with a SIM in a Huawei B525 router.  EE use IPv6 by default, not IPv4, in case it could be relevant.  Everything else on the internet works fine, just not your downloader.

**Comment by Franiac** [comment]
How about posting the error? I cannot read minds you know. IPv6/4 is irrelevant to any kind of SSL/TLS error. I so far have no indicator that this is a general issue due to the fact no one else dropped me an email or any error on another support channel.

**Comment by rik130** [comment]
Hi Dom.  Just wanted to update you.  Despite having 'update automatically' selected in the panel, I was still running version 1.3.9.  I uninstalled that completely and then attempted to download the latest 1.7 version but I got the 'hash value' mismatch error as reported in https://github.com/Franiac/TwitchLeecher/issues/378 .  I followed your advice there and downloaded .NET 4.8 via the link and then tried to install the latest Leecher again and it installed fine.  I've just tried the VOD link again and I'm happy to report it is a success !  :-)

Thanks for all your work making this excellent little program, it is so incredibly simple and useful.  :)

**Comment by rik130** [comment]
Hi Dom, sorry I'm unable to post the exact error now as I've uninstalled and deleted the 1.3.9 version and folders where the error was logged, but it was the same one as per #183 above, word for word.

**Comment by Franiac** [comment]
Wait what??? 1.3.9? You were using 1.3.9?

**Comment by Franiac** [comment]
Oh forget it, I just read your last post...

**Comment by Railbird80** [comment]
System specifications:

Hewlett-Packard Model a6244n
Processor: Intel(R) Core(TM)2 Duo CPU E4500 @2.20GHz 2.20GHz
Memory RAM: 3GB
System type: 32-bit Operating System

Operating System: Windows Vista Home Premium - Service Pack 2

Twitch Leecher version 1.5.8

Hello, I am having an issue being able to download VODs on twitch with TL 1.5.8.  When I first installed this version of the twitch downloader it was crashing during the mp4 encoding.  However, my work around was simply to navigate to the temp folder in a command console and join all of the TS files with the command "copy /b *.ts joined_files.ts", and then I simply copied the merged TS files to my video folder before I allowed TL to delete the temp folder it had created.  I then was able to view the merged TS files with the VLC media player, and I didn't complain since I was getting the VOD segments that I wanted. With a little bit of research I found the correct ffmpeg_x86.exe that worked on my legacy system, and I was able to get the the videos to encode into mp4 format, although it did take longer to encode than to download.  I was trying to download a VOD with the VOD ID of 495043407.  Unfortunately, I've encountered a new error to me, which is shown in the following screen captures:

I was using version TL 1.5.8 as shown here in this screen capture using the IDs search:

https://snipboard.io/Uv4De8.jpg

The error I encountered:

https://snipboard.io/fMV9ro.jpg

Screen capture of the error log file:

https://snipboard.io/KWOcrR.jpg

Output of TL error log:

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at TwitchLeecher.Gui.Services.SearchService.<>c__DisplayClass9_0.<PerformSearch>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at TwitchLeecher.Gui.Services.SearchService.<>c__DisplayClass9_0.<PerformSearch>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

After reading the current thread, I decided to try and the bump TL version 1.7.0, but I discovered that it would not work on my legacy system as the required .NET 4.8 install is not compatible with Windows Vista SP2 as shown in the following screen capture:

https://snipboard.io/oGUf0e.jpg

If there is some known work around for my legacy system, I would appreciate it.

Sincerely, Railbird80

**Comment by Franiac** [comment]
@Railbird80 TL 1.5.8 does not work, that is correct. 1.7.0 does, though. I am very sorry but Windows Vista is out of scope for almost all developers in 2019, and rightfully so. The OS is 13 years old with the last update being 10 years old. At some point in time you have to make the leap forward and get something new. I cannot turn down new technology and programming patterns because of 3 people with old gear. I hope you understand 😺
