### ISSUE TITLE
Audio Drifting in Cropped video downloads

### ISSUE THREAD

**Issue by Kaszanas** [Franiac/TwitchLeecher#392]
Hello,
Recently using Twitch Leecher with the most current version of the software (1.7) I have stumbled upon a problem.
The following steps seem to be causing the program to malfunction:

1. Video I am trying to download: https://www.twitch.tv/videos/496628712
2. I am setting up a download along with custom times so that I am not downloading whole VOD along with a custom filename.
![image](https://user-images.githubusercontent.com/34846245/67169505-f365c100-f3ab-11e9-854d-a47415dc2a4e.png)
3. Downloaded video is out of sync in two out of three downloaded parts of this VOD

I've double checked the VOD itself and it seems to be correct when it comes to the audio that was recorded using Twitch.

Downloading whole video seems to be the way not to run into this problem.

**Comment by Franiac** [comment]
If you take a look at all the closed issues regarding A/V desync you will realize that we tried to fix said stuff quite a couple of times in the past with no success. ffmpeg fucks this up depending on dropped frames, lags and what not. Nobody could ever pinpoint the issues that causes such shifts.

Due to the issues I introduced the option to download the raw .ts file from the Twitch server with the obvious drawback that you cannot select timespans since cropping requires ffmpeg.

As long as nobody is able to pinpoint the issues and how they me by fixed I will not take further actions (I personally don't know much about ffmpeg so I am not the key to success). The current state is the best we have ever had so I am not going to change that. I hope this is understandable.
