### ISSUE TITLE
Are twitch videos encrypted?

### ISSUE THREAD

**Issue by mewnm** [Franiac/TwitchLeecher#396]
Why does it need to download parts then merge and finally convert?

**Comment by Codereaders** [comment]
There's no encryption, at least as for standard VoDs. Might be that 'Sub only' streams are being encrypted, but as I never stumbled across one, I'm not sure. Also this does not seem very likely for me. There's other solutions to provide a content protection as required for 'Sub only' streams.

VoDs are being provided in chunks by Twitch. That's the way HTTP-Streaming works (https://en.wikipedia.org/wiki/HTTP_Live_Streaming). 

As you usually do not want to open a playlist with ~300+ Files, TwitchLeecher merges the chunks into one single file.

The conversion is being done for portability and to minimize disk space usage.

**Comment by Franiac** [comment]
Codereaders is basically right. A 3 hour stream might consist out of 3000 parts where each one has 3mb or something. A web player loads the playlist (containing links to all 3000 files with according timestamps). So if you jump to a location in the VOD, the webplayer knows which part to load for the selected time. It then starts to play back that 3mb file. While playing back that file it loads the next few files over the net and seamlessly plays those one after another. If the player cannot load the needed parts in time, the video starts buffering (aka waiting for new files).

And yea... since you don't want to click a new file every 10s TL is nice enough to merge all those little files into a single one on a binary level. A web player is not capable of loading "a little part" of a giant VOD file and buffering from there. Would be cool, but that's not the case.
