### ISSUE TITLE
TL 1.4. download

### ISSUE THREAD

**Issue by aria90** [Franiac/TwitchLeecher#401]
Sorry for opening a new issue again, I didn't want to bringt up the A/V desync problem, I was just asking if it is possible to offer a download for the 1.4.2 or 1.4.3 TL version because it worked perfectly for me (Windows 7 64bit).
Maybe someone can give me a download link?

Thank you

**Comment by Franiac** [comment]
This is not possible since some of the current behaviors of Twitchs' API and video servers are not compatible to 1.4.x anymore. Maybe you should check out the raw download option in the preferences and read the questionmark hint carefully.

And another question would be where A/V desync occures. If you step through all teh closed issues you might realize that often the video software (especially Premiere) or the video player (especially Media Player) are the actual problem, not the video itself.
