### ISSUE TITLE
Error 410 (gone) issue happening again 

### ISSUE THREAD

**Issue by inkawf** [Franiac/TwitchLeecher#408]
Looks like it happened at 2:00 PM EST on the dot today, and it looks like the token is having issues at the remote server once again.

**Comment by wolfgangam31** [comment]
I have a Python script that uses the same url https://api.twitch.tv/api/vods for auth and I  have the same issue

**Comment by inkawf** [comment]
Yeah this seems to be a semi daily occurring issue.  Usually it fixes itself but it's still annoying.

**Comment by wolfgangam31** [comment]
It looks to me like this API isn't available anymore, I don't think it temporary thing

**Comment by inkawf** [comment]
> It looks to me like this API isn't available anymore, I don't think it temporary thing

I dont think that's the case because it was down for hours 2 days ago. Has  anyone alerted franiac?

**Comment by Franiac** [comment]
> Has anyone alerted franiac?

No, and I don't want to be alerted. This is freeware developed in my freetime. I do not provide 24/7 availability or any other "emergency" stuff.

Currently I am on the go and I am simply stuck in real life, so I can't do anything at the moment. And speaking about doing anything... as far as I know there is no applicable and tested fix for that anyways. We will see how it develops until tomorrow (again).

**Comment by inkawf** [comment]
Sorry for how I worded that. I'm thankful for all you dude. Thanks for getting back. :) hoping it returns on it's own like it usually does.

**Comment by Franiac** [comment]
@inkawf All good, dude 😄

**Comment by inkawf** [comment]
Yeah I dont think it's coming back this time....

**Comment by JackBlues1997** [comment]
I feel the same.

**Comment by darkvrover** [comment]
It seems that the issue is caused by Twitch client-id, which means that those client-ids for third party could not be used at this moment, and only the client-id obtained from twitch website is working right now. I found the 410 error this morning when I use streamlink to record a steam, then I looked up for a solution and used the method here:
https://github.com/streamlink/streamlink/issues/2680#issuecomment-550475041
https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753
So I just replaced the old client-id in streamlink with a new one generated from twitch webpage itself, and streamlink worked again for me.
Wish the information above could help.

**Comment by Vale997** [comment]
> It seems that the issue is caused by Twitch client-id, which means that those client-ids for third party could not be used at this moment, and only the client-id obtained from Twitch website is working right now. I found the 410 error this morning when I used streamlink to record a steam, then I looked up for a solution and tried the method here:
> [streamlink/streamlink#2680 (comment)](https://github.com/streamlink/streamlink/issues/2680#issuecomment-550475041)
> [streamlink/streamlink#2680 (comment)](https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753)
> So I just replaced the old client-id in streamlink with a new one generated from twitch webpage itself, and streamlink worked again for me.
> Wish the information above could help.

Thanks, but how to do it for Twitch Leecher?

**Comment by KurtBuhagiar** [comment]
Thanks for all your hard work Franiac ! I have been using your software for a long time. Let's all give him his time and let him try and fix it when he can! He has provided us with a fully working software for a long time. This is nothing compared to the up time :) Thanks once again.

**Comment by Franiac** [comment]
@darkvrover Using the Twitch Client ID is not an option (not allowed). The workaround that every user generates a new Client ID seems not applicable for me, since the ID is in TL code.

The question is, would it help to actually generate a new Client ID for TL. This would break every installation out there (kinda big deal, huh). I am really hesitating to take action at the moment because noone really knows what's wrong.

The fact that Twitch is blocking Client IDs that are 3rd party makes sense. Maybe they want to block access to their private APIs in order to "kill" tools like TL and other downloaders. As we all know, such tools are not 100% ToS compliant and I don't know if Twitch actually want to support them.

@Vale997 you can't

**Comment by Vale997** [comment]
> @darkvrover Using the Twitch Client ID is not an option (not allowed). The workaround that every user generates a new Client ID seems not applicable for me, since the ID is in TL code.
> 
> The question is, would it help to actually generate a new Client ID for TL. This would break every installation out there (kinda big deal, huh). I am really hesitating to take action at the moment because noone really knows what's wrong.
> 
> The fact that Twitch is blocking Client IDs that are 3rd party makes sense. Maybe they want to block access to their private APIs in order to "kill" tools like TL and other downloaders. As we all know, such tools are not 100% ToS compliant and I don't know if Twitch actually want to support them.
> 
> @Vale997 you can't

Thanks for the answer. You have done a lot for us. We can only wait?

**Comment by Franiac** [comment]
I found this:

https://discuss.dev.twitch.tv/t/410-gone-on-v5-games-top/22835/6

I'll check if it works

**Comment by Vale997** [comment]
> I found this:
> 
> https://discuss.dev.twitch.tv/t/410-gone-on-v5-games-top/22835/6
> 
> I'll check if it works

Okay, thank you!

**Comment by darkvrover** [comment]
> @darkvrover Using the Twitch Client ID is not an option (not allowed). The workaround that every user generates a new Client ID seems not applicable for me, since the ID is in TL code.
> 
> The question is, would it help to actually generate a new Client ID for TL. This would break every installation out there (kinda big deal, huh). I am really hesitating to take action at the moment because noone really knows what's wrong.
> 
> The fact that Twitch is blocking Client IDs that are 3rd party makes sense. Maybe they want to block access to their private APIs in order to "kill" tools like TL and other downloaders. As we all know, such tools are not 100% ToS compliant and I don't know if Twitch actually want to support them.
> 
> @Vale997 you can't

Yeah I see, that's truely sad news for us. Maybe Twitch could make some new rules for developers, and give their authentication to those brilliant softwares or tools like TL.
Also, thank you so much for your amazing work!

**Comment by KurtBuhagiar** [comment]
Do you guys know of any other temporary (hopefully this gets fixed) recording methods? Thanks

**Comment by Franiac** [comment]
I tried this:

https://discuss.dev.twitch.tv/t/410-gone-on-v5-games-top/22835/6

Does not work. The whole api namespace of Twitch is gone.

I did some research and realized that the entire Twitch website does not use https://api.twitch.tv/api/ anymore. They implemented a GraphQL API. You can see this if you use the Browser DevTools and click on a video. There are just calls to a "gql" endpoint that probably replaces the old api.

This GraphQL API is not documented since it is also for internal use only. The problem is, normal APIs can be "decoded" quite easily, but GQL cannot since noone really knows the parameters the endpoint takes.

If the situation stays like this.... well.... TL had a good time 😄

**Comment by Vale997** [comment]
> I tried this:
> 
> https://discuss.dev.twitch.tv/t/410-gone-on-v5-games-top/22835/6
> 
> Does not work. The whole api namespace of Twitch is gone.
> 
> I did some research and realized that the entire Twitch website does not use https://api.twitch.tv/api/ anymore. They implemented a GraphQL API. You can see this if you use the Browser DevTools and click on a video. There are just calls to a "gql" endpoint that probably replaces the old api.
> 
> This GraphQL API is not documented since it is also for internal use only. The problem is, normal APIs can be "decoded" quite easily, but GQL cannot since noone really knows the parameters the endpoint takes.
> 
> If the situation stays like this.... well.... TL had a good time 😄

Press F >_<

**Comment by MrDummyNL** [comment]
I like TL very much, because the download function in Twitch is VERY slow and has long preparation time. So if you have big stream video, it's almost waiting with unknown time.

So i think with many people: TL should proceed. I am even willing to donate for it, it's so good.
Hopefully there is soon solution for API problem.

**Comment by nasdalol** [comment]
Although TL is probably one of the most amazing FREE tools I have ever used, when you use it a lot every day, like I do, sometimes you tend to forget just how great it is. Yesterday I double-clicked TL's icon and insert the twitch vod link like I always do and then found out that TL didn't work anymore due to this 410 error thing. It has been almost 20 hours since TL stopped working and I have been trying to find other alternatives. So far only one of them works and it is not even close to what TL could do, which makes me realised, once again, how much TL had made my life easier. I only registered this account to say the above and how much I appreciate the work Franiac has been putting into and done for us. Hope TL will work again soon! Thank you so much, Franiac!

**Comment by KurtBuhagiar** [comment]
> Although TL is probably one of the most amazing FREE tools I have ever used, when you use it a lot every day, like I do, sometimes you tend to forget just how great it is. Yesterday I double-clicked TL's icon and insert the twitch vod link like I always do and then found out that TL didn't work anymore due to this 410 error thing. It has been almost 20 hours since TL stopped working and I have been trying to find other alternatives. So far only one of them works and it is not even close to what TL could do, which makes me realised, once again, how much TL had made my life easier. I only registered this account to say the above and how much I appreciate the work Franiac has been putting into and done for us. Hope TL will work again soon! Thank you so much, Franiac!

Definitely agree with everything you said. Which alternative are you using? Thanks

**Comment by Franiac** [comment]
Ok guys... After some intense research the API endpoint

https://api.twitch.tv/api/vods/{0}/access_token

is definitely not down since the Twitch website still uses it to retrieve an auth token. I just checked that in incognito mode in Chrome. Wehnever I request this url with my TL client ID I get the 410 gone error.

The web player uses the client ID **kimne78kx3ncx6brgo4mv6wki5h1ko**. I also found this ID in the source code of youtube-dl and some other stuff.

The thing is, with the above client ID I made TL work again! I only use the "foreign" client ID in order to retrieve the auth token. When you connect TL to your account, it still greets you as TL.

I will provide an 1.7.1 update of TL shortly.

**BUT!!! This is a change I cannot guarantee to work for very long, so don't be surprised if I crashes tomorrow again...**

**Comment by nasdalol** [comment]
> > Although TL is probably one of the most amazing FREE tools I have ever used, when you use it a lot every day, like I do, sometimes you tend to forget just how great it is. Yesterday I double-clicked TL's icon and insert the twitch vod link like I always do and then found out that TL didn't work anymore due to this 410 error thing. It has been almost 20 hours since TL stopped working and I have been trying to find other alternatives. So far only one of them works and it is not even close to what TL could do, which makes me realised, once again, how much TL had made my life easier. I only registered this account to say the above and how much I appreciate the work Franiac has been putting into and done for us. Hope TL will work again soon! Thank you so much, Franiac!
> 
> Definitely agree with everything you said. Which alternative are you using? Thanks

I tried [https://untwitch.com/](url) at first which is a website providing free downloading service. It seems to be working but sometimes the download just randomly stopped. I don't know if it's the same for everybody or just me. Maybe becos I'm living in China and using VPN so my network could be unstable from time to time. I didn't have the same problem when I was using TL tho.

And then I tried HD Video Converter Factory. It works but you can only download the entire vod which for me it's usually means downloading a 8-10 hour long vod .. Somebody might find it useful. Who knows, right? I'll use it to download youtube video tho.

For me, no softwares do better than TL at downloading Twitch vods. I still need to find a good alternative method, for the time being at least. Please let me know guys. Thanks!

**Comment by Franiac** [comment]
NEW RELEASE IS OUT!

I hope it fixes this shit for at least a couple days...

**Comment by Endureremy** [comment]
> NEW RELEASE IS OUT!
> 
> I hope it fixes this shit for at least a couple days...

Thank you for fixing this so fast, even if it's temporary. I'm going to buy you a bottle of  beer.

**Comment by KurtBuhagiar** [comment]
Hi, do I need to add something for the video to work? It still doesn't work for me.

**Comment by tgd-2134** [comment]
I do not speak English well
This is also being written using a translator
But I hope this helps.
At the moment I found out that I can download .mp4 files with 4K Video Downloader.

**Comment by nasdalol** [comment]
I can confirm that the newly released 1.7.1 version of TL works again! Make sure to uninstall the old version completely and make a clean installation. Updating from the old version didn't work for me, a clean reinstallation did. Thank you so much again, Franiac! You are my hero! Is there anyway I can donate to you for all the hard work you put in?

**Comment by MPeti1** [comment]
I've came across that error message too. Just want to add that after I restarted TL I wanted to try again downloading part of an ongoing stream before I update and now it works.

Thought that you should know the old method may not be totally broken.
A few more things to note: before the error message I last downloaded a VOD yesterday in the morning at 8:30 (UTC), and last refreshed the VOD list ~4 hours ago (15:00 CET). After restarting TL loading the VOD list takes unusually long, along with loading the VOD thumbails

**Comment by Franiac** [comment]
@nasdalol how about clicking that little $ button in the titlebar? 😄

**Comment by Franiac** [comment]
@MPeti1 yes, the old way somehow works every now and then but not really reliably. The new method should work better..... I GUESS 😄

**Comment by MPeti1** [comment]
Oh, I see :D thanks

**Comment by wolfgangam31** [comment]
Thanks @Franiac , Truly thought this was it for this API....  changed that ID on my end as well and it started working :)

**Comment by nasdalol** [comment]
> @nasdalol how about clicking that little $ button in the titlebar? 😄

@Franiac I thought I have seen it somewhere. Really hope you can keep this software updated in the future.

**Comment by loohhoo** [comment]
Working for me now! Thanks so much for your hard work and making editor's lives easier 💕

**Comment by MPeti1** [comment]
> 
> 
> Working for me now! Thanks so much for your hard work and making editor's lives easier 💕

Not just editors life. Personally I hate the twitch player, and also this way I can watch streams on my phone when I'm not at home.

**Comment by nasdalol** [comment]
Guys, if you are really appreciated for all the hard work and effort Franiac had done for us. Please feel free to let him know by hitting that donate button. I'm sure even buying him a bottle of bear will make him happy.

**Comment by Novgorod** [comment]
> I'm sure even buying him a bottle of bear will make him happy.

I wouldn't be too happy if someone bought me a bear - they eat an arm and a leg (literally) and the fur gets just in every crack.

**Comment by nasdalol** [comment]
> > I'm sure even buying him a bottle of bear will make him happy.
> 
> I wouldn't be too happy if someone bought me a bear - they eat an arm and a leg (literally) and the fur gets just in every crack.

lol I got too excited there.

**Comment by Franiac** [comment]
Ok, it seems to be quiet around this issue. Thx everyone for the support and bears (!) 😄 

Closed

**Comment by DracoDruid** [comment]
Sorry to inform that I'm having the 410 Error issue now. 
I just updated to the latest TL version 1.7.1.

**Comment by Novgorod** [comment]
> Sorry to inform that I'm having the 410 Error issue now.
> I just updated to the latest TL version 1.7.1.

Can't confirm - new searches and downloads are working fine as of now.

**Comment by Kisaragi539** [comment]
I had the same porblem again today, but only when I authorized my Twitch account.

**Comment by DracoDruid** [comment]
I thought it happened because Twitch no longer accepts login via email address, so I re-authorized the TL. But this didn't help either. I still get the 410 error.
It also doesn't matter which channel I try. Searches work fine, only the downloads are having that problem.
I am using Win10x64 and TL 1.7.1 (from Germany if that makes any difference)

**Comment by Kisaragi539** [comment]
It works normally for me when Im not authorized, maybe this hepls...

**Comment by DracoDruid** [comment]
The videos I'm trying to access are only available for subscribers, so I have to be authorized. But I'll try and see if that makes a difference.

**Comment by w4hnsinn** [comment]
> Is that an issue with TL oder with the Twitch API though?

It appears that Twitch is / has been making changes on their end which break tools like TL. Whether this is intentional to deter download tools or not is as yet unclear, I believe. But it's a fairly safe bet they don't _mind_ that people have to go to their site again.
