### ISSUE TITLE
sound sync problem

### ISSUE THREAD

**Issue by kleanins** [Franiac/TwitchLeecher#415]
twitch leecher 1.5.5 and upper versiyon (1.7.1 included) has sound sync problem. Video's sound a second behind. I thought it would be solved in 1.7.1. but it is but unsolved. therefore I have to use 1.4.2. but it has 410 error now. i hope sound sync problem will solved soon.

Does not happen everytime. but I'm having it in 2 of the 3 videos I've downloaded

**Comment by kleanins** [comment]
Does not happen everytime. but I'm having it in 2 of the 3 videos I've downloaded

**Comment by Franiac** [comment]
And what exactly made you think 1.7.1 changed something? There are no changes to be made. Please check out the 20 closed issues for this matter before posting the same.
You have also the option to disable mp4 conversion which downloads the source file without trying to convert it. Also there is no information about how you play back the video since video software and video players can also introduce A/V desync... but again, check the closed issues, please.

**Comment by kleanins** [comment]
my question was that there was no audio sync issue in previous versions. Why new releases has sound sync problem?
and did not see a closed issues with the sound sync
