### ISSUE TITLE
Error installing 1.7.2

### ISSUE THREAD

**Issue by nailz420** [Franiac/TwitchLeecher#418]
Setup fails with a non-descriptive error message. Application event log has the attached 2 messages. I assume the second one is related.

[events.zip](https://github.com/Franiac/TwitchLeecher/files/3849893/events.zip)

**Comment by Franiac** [comment]
Are you familiar with the command line in windows?

If so, you can start the installer with "TwitchLeecher_1.7.2.exe -l log.txt". Click through the installer until it fails. Post the logfile or a link to it here .

**Comment by MrDummyNL** [comment]
My upgrading process from 1.7.1 to 1.7.2 has no errors showed and it's finished.
Started program without problems and i can download it.

Make sure no other programs are in the way, also it was protected by Windows because it's not trusted immediately, i need click to proceed with install manually. And some anti virus programs can block some parts of install.

**Comment by Franiac** [comment]
Closed because stale

**Comment by nailz420** [comment]
Hi Dominik, I retried today via your command line and it completed successfully. Do you still want the logs? Thanks,Tim   From: Dominik RebitzerSent: Friday, November 15, 2019 6:53 AMTo: Franiac/TwitchLeecherCc: nailz420; AuthorSubject: Re: [Franiac/TwitchLeecher] Error installing 1.7.2 (#418) Are you familiar with the command line in windows?If so, you can start the installer with "TwitchLeecher_1.7.2.exe -l log.txt". Click through the installer until it fails. Post the logfile or a link to it here .—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
