### ISSUE TITLE
Can't use or uninstall Twitch Leecher

### ISSUE THREAD

**Issue by johnyman123** [Franiac/TwitchLeecher#423]
I can't use Twitch Leecher 1.7.3, I used the older version 1.5.3 and download the new one, so now i have both apps in my pc. When i turned on the new one it told me to uninstall the old one and when i opened or tried to uninstall the old one It tells me to update to the new one, what am I supposed to do?

**Comment by MrDummyNL** [comment]
Euh.... the title is not supposed to throw in large text. That should kept short.

**Comment by johnyman123** [comment]
@MrDummyNL Yeah, I realized that later, sorry about that

**Comment by Franiac** [comment]
@johnyman123 This only happens when the previous installer was killed forcefully and did not register it's installation in the windows system. Microsoft offers a tool called "Windows Installer CleanUp Utility" for those issues:

https://www.techspot.com/downloads/388-windows-installer-cleanup-utility.html

1. Download and install
2. Remove all TL installations with the tool
3. Restart the PC
4. Try installing TL 1.7.3 again

**Comment by johnyman123** [comment]
@Franiac I tried to download and install it now, It got rejected by the system. I got Windows 8. Any other ideas?

**Comment by johnyman123** [comment]
Solved:
1. Downloaded Revo Uninstaller
2. Tried to uninstall (closed the pop up window)
3. Scanned for leftovers and removed them
4. Installed only the new version (1.7.3)

Thank you for your help anyways Franiac <3
