### ISSUE TITLE
Feature Request: 32bit OS support

### ISSUE THREAD

**Issue by blahblahblug** [Franiac/TwitchLeecher#425]
Please support 32bit windows OS again. I use windows 10 32bit for downloads to a NAS.

**Comment by Franiac** [comment]
No, TL uses libraries that are not available in 32 bit anymore and that's a good thing. Why would you install Windows 10 32 Bit in 2019? There is no reason to do so. Apple deprecated 32 bit apps, Google does not want new apps in 32 bit, nobody needs 32 bit.

**Comment by blahblahblug** [comment]
It came with Windows 10 32 Bit pre-installed.

**Comment by Franiac** [comment]
In 2019 I call that "screwing over the customer". Should not be a thing anymore to be honest.

What NAS is that if I may ask? NAS + Windows is a very uncommon package in the prebuilt NAS world. And a NAS with a max RAM size of 3.5GB (because 32 bit) is another failure. What the hell did you buy there 😄 ???

But all the bla aside, it doesn't change the fact that TL won't come back to 32 bit, sorry.

**Comment by blahblahblug** [comment]
I bought it in 2017. 

The NAS isn't windows, it's running some flavor of linux. A WD Mycloud. I'm using a win10 2in1 for downloading.

**Comment by Franiac** [comment]
I misread your first post... you're downloading **TO** a NAS..... now I get it, sorry. But even every cheap 2in1 since 2014 or even earlier has a 64bit CPU in it. This 32 Bit OS stuff is just plain bullshit. Let me guess.... that 2in1 has 4gb of ram and you can only use 3.5gb of it because of the OS, right? 😄

But like I said... can't help... the show must go on, cannot stick to the past forever.
