### ISSUE TITLE
Audio quality has gotten worse

### ISSUE THREAD

**Issue by ghost** [Franiac/TwitchLeecher#443]
**My TwitchLeecher version:** 1.7.3
**My Windows version:** 7, 64bit
**.NET Framework** updated to 4.8.

It looks like the audio quality of downloaded clips has gotten significantly worse recently. They all have 128kbps bitrate, and the older clips that I still have on my PC have at least 192kbps audio. 
Note that this affects all VoDs of all the streamers that I've checked.

You can actually hear the sound quality being worse.

**Comment by Franiac** [comment]
2 things are very unlikely here: First off Twitch videos cannot be 192kbps since Twitch only allows a maximum bitrate of 160kbps. And secondly for at least one year straight the settings of how TL processes video and audio has not been changed.

> You can actually hear the sound quality being worse.

Speaking as an audio engineer: Unless you have some really high quality studio equipment you cannot hear the difference between 128kbps and 192kbps on a video that got encoded to death over the internet. Even on uncompressed .wav files it is very hard for "normal" ears to hear differences in bitrates.

I don't really know how you come to your conclusion since there is nothing to work with. A general "it got worse" without any clues or examples is hard to work with.

**Comment by Codereaders** [comment]
As far as I remember Franiac's code he does no audio transcoding or such. So TwitchLeecher should not be responsible for any loss in audio quality. @Franiac please correct me if I'm wrong with that.

@xNevan have you checked your own audio equipment? Have you update any drivers/ Windows itself lately? Things like that could be a cause to experience problems with audio quality.

Another possibility could be that the loss in quality already happened before download but during the upload by the content creator?

Maybe the VoD you experienced the worse audio quality on would be interesting to analyze the problem further.

**Comment by Franiac** [comment]
@Codereaders I changed the audio stream to be actually re-encoded to match the video stream's length but that change is pretty old now. But while doing that, the source audio stream's settings are not changed (as in bitrate, samplerate and such...)

**Comment by Franiac** [comment]
Closed because no response
