### ISSUE TITLE
Feature request: Default quality option

### ISSUE THREAD

**Issue by zdepav** [Franiac/TwitchLeecher#445]
Hi,
great work wit the app, but there is one thing I'm missing - some kind of default quality setting.
I download all videos in lower quality (so that the video files take up less space on my hard drive), but as currently the quality defaults to the highest possible, I have to set it manualy every time - which is very annoying when downloading multiple videos at once. Additionally I sometimes forget to set it, so I also have to check the quality in the download manager afterwards.

Therefore I would like to have a default quality option in settings, which would preset the quality for downloads (if that quality is available).

Could look somewhat like this:
![S_2019-11-27_12-53-55-0083](https://user-images.githubusercontent.com/12015515/69723123-1c9b0f00-1119-11ea-9f7a-cbf1e682f12c.png)

**Comment by Franiac** [comment]
This would be already in TL if there was not the sub-only issue going on that ate up all my available time.

It is not as easy as you might think because not every video has the same resolutions available. There will be a dropdown like your screenshot shows but with 2 more radio buttons with it saying "Choose lower quality if not availabel" and "Choose higher quality if not available".

If you choose 900p as a default for example but the transcoded video does not have 900p TL must know what to do then.

Works like this:

1. If the default quality is available TL will download that
2. If default quality is not available and "Choose lower quality if not availabel" is set, TL will try to download the next lower quality. If no lower quality is available, TL will choose the next higher quality.
3. If default quality is not available and "Choose higher quality if not availabel" is set, TL will try to download the next higher quality. If no higher quality is available, TL will choose the next lower quality.

This makes sure that TL always can select a quality.

**Comment by profucius** [comment]
I would like to request this feature as well.

The way I imagine it could happen. You set a "highest acceptable quality" from a dropdown menu like zdepav used in his screenshot above. If that resolution is not available, it drops to the next one below.

Example: I set it to 720p, if it is an available resolution then it grabs that, otherwise if the only next resolution is 480p then it grabs that instead.

Is this a possibility?

**Comment by Franiac** [comment]
@profucius Have you even read my comment?

**Comment by profucius** [comment]
> @profucius Have you even read my comment?

I have. And I do not see an option for setting a quality ceiling, which I need for my purposes. I have tested the software and I am getting 1080p when I need only 720p max. How do you suggest that I ensure that 720p is the max resolution?

**Comment by Franiac** [comment]
@profucius You can select the download quality from the dropdown when you download a video. If you select 720p, you get 720p. So what is your issue? You don't need to download at 1080p if you don't want to.

This issue is an enhancement that you can specify a preferred quality in the preferences so you don't need to select it manually every time, that's all.

> And I do not see an option for setting a quality ceiling

Yes, because it is not implemented yet, hence this issue is open and not closed.

**Comment by profucius** [comment]
Fine, how about this as a feature request: Set a "preferred" quality in settings, and every time you go to download, it pre-selects that quality. If that quality is not available, the one below it. This way it is not easy to mistake or overlook the quality setting, since it currently always defaults to the highest available.

**Comment by Franiac** [comment]
@profucius Please **READ** my first comment (because obviously you did not) 😄

**Comment by Franiac** [comment]
This is implemented for the upcoming Helix release. I chose not to implement the radio buttons. If the desired quality is not available, the next lower will be selected. if there is no lower quality, the next higher will be selected.
