### ISSUE TITLE
live capture / automated downloading

### ISSUE THREAD

**Issue by lobof** [Franiac/TwitchLeecher#446]
i was wondering if any sort of auto capture was in the works so i could have this running 247 on my pc and capture livestreams so i can watch them at my own time instead of live

this is a feature request i guess i dont know if im posting this correctly sorry if im not

**Comment by mouarflenoob** [comment]
I am also looking for a way to get livestreams while they are on.
The features I'm looking for  : schedule the live recording while using the same options I have with the V.O.D. (I can set the quality, title, etc...), the ability to keep watch on several channels at once, and also, to be able to run it with command line, and to be able to run it on linux
(my home server, which is always on and consumes very low power, is always on, and is running linux).

I know I ask a lot, but you have to aim for the stars to fall on the moon :)

**Comment by Franiac** [comment]
@mouarflenoob that's all super nice and I wish I had already implemented it... becoming a father in april, so realisticly my time I can spend on new features approximates exactly ZERO :D:D:D
But I am not sorry, sorry :P

**Comment by garoto** [comment]
[**@mouarflenoob**](https://github.com/mouarflenoob) commented on [Jan 18, 2020, 12:12 PM GMT-3](https://github.com/Franiac/TwitchLeecher/issues/446#issuecomment-575907324 "2020-01-18T15:12:50Z - Replied by Github Reply Comments"):
> [snip]

You might want to give https://github.com/streamlink/streamlink/ a try then. It's a CLI Python program, so you can use it in a script in many different ways. The only thing it sort of lacks is proper `--output` use of properties and/or formatting, so that needs to be done via shell functions.

**Comment by mlindgren** [comment]
@garoto Thanks for the suggestion. I figured out a quick and dirty way to do this using a bash script with Streamlink and ffmpeg.

```
#!/bin/bash

while :
do
    streamlink $1 best -O | ffmpeg -re -i pipe:0 -c copy -bsf:a aac_adtstoasc $2
    if [ $? -ne 1 ]
    then
        break
    fi
    sleep 30
done
```

Save the above as a script, say twitch.sh. Then run it with `twitch.sh twitch.tv/YourFavoriteStreamer output.mp4`. I did a quick test on my own stream and it seemed to work, but I haven't had the opportunity to try it on a full stream yet so I can't make any promises. Open to suggestions for improvements.

You should be able to do the same thing on Windows using a batch script or PowerShell.

**Comment by Franiac** [comment]
#803
