### ISSUE TITLE
crop feedback

### ISSUE THREAD

**Issue by kleanins** [Franiac/TwitchLeecher#449]
I think it was much more convenient when the crop part to be like this.
And "use custom filename" checkbox isn't it unnecessary?
just wanted to give feedback

![image](https://user-images.githubusercontent.com/57459418/69907874-da125480-13ee-11ea-8197-8cc4236883e2.png)

**Comment by Franiac** [comment]
Thx for your feedback, much appreciated!

I think it's a 50/50 thing. I personally don't like typing ":". I am way faster by

`click in the first box -> 3 -> tab -> 05 -> tab -> 45`

(using tab and the numblock)

instead of writing `03:05:45` because it includes using the shift key (German keyboard layout) and therefor making me take away my right hand from the numblock.

And then there are the people that prefer using the mouse and the arrow buttons.

I think there is no compromise that everybody gets it the way he wants. For the reasons above I will not change the current UI.

As for the "use custom filename" checkbox. That is very funny, because you definitely should take a look at the closed issue #413 where a user cannot get enough of this checkbox. I personally agree with you since the filename template is very versatile and easy to use.

**Comment by kleanins** [comment]
i have a youtube channel about twitch streamers videos.  i mean i upload videos like; "XXX streamer is watchin XXX" or "XXX is commenting about XXX"  and i use notepad and uptime times like this :D 
That's why I liked it the old way :D 
![image](https://user-images.githubusercontent.com/57459418/69914878-28107200-145a-11ea-9a95-6e726da5c66a.png)

and about "use custom filename" checkbox, i take a look #413  but I don't understand maybe because my English is not very good.
Wasn't there already a file name by default before it became a checkbox?
I really don't understand why the checkbox is there.

If I don't want to change the file name in the past, I'm downloading it directly.
If I wanted to change the file name in the past, change the file name and download.
Why do I click the checkbox now?

**Comment by kleanins** [comment]
@Franiac
