### ISSUE TITLE
It only downloads audio?

### ISSUE THREAD

**Issue by leaguethrows** [Franiac/TwitchLeecher#47]
Hi,

Thanks for making such a simple and easy to use interface! 

An issue that I have is that it only downloads audio even though I'm selecting "Source" or "High" quality. The file output is also a .mp4 but it always just plays audio only.

I am using updated VLC to play the downloaded video.

Help would be appreciated :)

Thanks!

**Comment by Franiac** [comment]
I discussed this issue with 2 or 3 people on reddit. Please answer the following questions so that I know it is the same issue:

1. The issue does not happen on every VOD of every channel (said differently: There are VODs you can successfully download with TL)? To test, just try my channel "FakeSmileRevolution" and download one of the Highlights. Those should work, right?

2. If you watch the "failed" VOD on Twitch in the browser, is there a black screen for like 2-3s at the beginning of the stream?

I have the feeling that this problem is due to bad encoding properties of the streamers OBS/XSplit settings, maybe related to keyframes or the usage of variable bitrate (which Twitch does not like at all)

We found out that on the "failed" VODs the first chunk that is beeing downloaded by TL from Twitch is much smaller compared to the rest. On a "good" VOD, the first chunk is exactly the same size.

And please provide the url of the VOD you are trying to download so I can investigate!

Thanks for the input!

**Comment by DarkOblivion** [comment]
@Franiac I have a slight issue aswell, i was trying to download an old vod from twitch and it only downloads a portion of the, it only downloads maybe 9-10 minutes of the stream, im not sure if its because the stream is older or something else is affecting it, but it dosent happen on any of the new streams, atleast not yet just wondering if it can be fixed in an update or something or it just has something to do with the stream, also heres the link to the stream VOD that wont fully download https://www.twitch.tv/joshimuz/v/50458662 

it plays just fine when watching the VOD though.

**Comment by Franiac** [comment]
@leaguethrows Anything new on the issue? If I do not get information, I cannot help :smiling_imp:

**Comment by Franiac** [comment]
Closed due to lack of response
