### ISSUE TITLE
Very slow download

### ISSUE THREAD

**Issue by VictoriaSarut** [Franiac/TwitchLeecher#473]
Hello, I apologize in advance for my English, it is not my native language.

So, previously, streams were downloaded quite quickly, but now one stream will be downloaded for 5 hours. There can be no problems on the Internet, it is fast and I download everything quickly using other apps.

**Comment by Franiac** [comment]
The download mechanism of TL has been unchanged since version 1.0. I highly doubt this is a TL issue. And since you have not provided any additional info or context I cannot make an edjucated guess on what could be wrong. TL uses the .NET integrated download mechanism. Even if I wanted I could not change it.

**Comment by VictoriaSarut** [comment]
> The download mechanism of TL has been unchanged since version 1.0. I highly doubt this is a TL issue. And since you have not provided any additional info or context I cannot make an edjucated guess on what could be wrong. TL uses the .NET integrated download mechanism. Even if I wanted I could not change it.
