### ISSUE TITLE
VOD download slowed down, resulting download is not merged together

### ISSUE THREAD

**Issue by kuroshima12** [Franiac/TwitchLeecher#478]
I am using Twitch Leecher 1.8 on Windows 10 64 bit. All of a sudden, any vod I try to download takes an extremely long time to download. Once it is finished downloading, the resulting download is just a folder with a bunch of incomplete ts files which I assume means there was an issue with merging the files? I have tried the same download on a laptop and did not have this issue.  I have attached below the download log. The only thing I can think of that has changed since this issue has occurred is a windows update? Would appreciate any assistance.

[leecher log.txt](https://github.com/Franiac/TwitchLeecher/files/4412296/leecher.log.txt)

**Comment by Franiac** [comment]
First off, the download time is dependent on your internet connection, that's not something TL can manage. If the download is slow, maybe your provider is choking due to everyone sitting at home.

Looking at the log file everything is perfect. There is no issue with the download or the merge process and the resulting file was copied to:

`C:\Users\Charizard\Downloads\20200331_580036412_Twitch Plays.mp4`

Are you sure you're looking at the right folder?

**Comment by kuroshima12** [comment]
Hmm, I checked the folder specified and I was indeed looking at the correct folder. I tried downloading the same vod on a different day and it worked with no problem so perhaps it was an intermittent issue? The weird thing is that when I tried the download on a different computer connected to the same network this issue didn't occur.
