### ISSUE TITLE
bump of "introduce speed limiter

### ISSUE THREAD

**Issue by mgrandi** [Franiac/TwitchLeecher#487]
its been 4 years since https://github.com/Franiac/TwitchLeecher/issues/46 , has there been any progress?

even if the new library you mention is not 100% ready yet, the program is really rough to use at the moment because it kills my internet for everything else but the program

i notice in the logs that it says `Maximum connection count: 10`, how easy it to make this be configurable? if there are less connections then less internet usage, right?

**Comment by Franiac** [comment]
I know my open issues very well. I am sorry that this takes longer than you like. I have built a house and now I have a 10 day old daughter. I am the only developer on this project and I know it sucks. Pull Requests are almost always of bad quality and I cannot just merge them in. I cannot "un-viral" Twitch Leecher. It was never planned to become what it is now.

I am glad you changed "unusable" to "really rough to use" and I get it, but this does not magically give me more time to spend on all the open issues, primarily the download manager. I also wouldn't like to use a download tool without a proper limit and pause implementation. I am not an idiot not seeing the problem, I am a good software dev without time to spend on the project. That is a different problem with the same effect.

Connection count is not related to download speed. It's not that easy, unfortunately. Even a single connection can block your wire.

**Comment by mgrandi** [comment]
Is the library you mentioned in the original ticket "ready" to useMl? If so I can try and integrate it and submit a pull request if that is acceptable?

**Comment by Franiac** [comment]
Absolutely not ready. I have many files not even commited. The library is able to download a single file without any events fired or checks done. Far from starting pull requests on it. Even the concept and class layout itself are under construction right now.

It is a completely separate project not related to TL and I am not even sure yet if it is going to be licenced under MIT or not.

I can feel you and I appreciate the will to contribute very much, but currently I am not far enough into the project.

Originally I have the plan to make TL an Electron App because I hate WPF and its bloatware XAML code makes me sick. But being a father now changed plans quite a bit 😄

**Comment by Franiac** [comment]
I think this is discussed to the end and can be closed.
