### ISSUE TITLE
VOD issue, does not fully download full stream.

### ISSUE THREAD

**Issue by DarkOblivion** [Franiac/TwitchLeecher#49]
@Franiac I have a slight issue, i was trying to download an old vod from twitch and it only downloads a portion of it, it only downloads maybe 9-10 minutes of the stream, im not sure if its because the stream is older or something else is affecting it, but it dosent happen on any of the new streams, atleast not yet just wondering if it can be fixed in an update or something or it just has something to do with the stream, also heres the link to the stream VOD that wont fully download https://www.twitch.tv/joshimuz/v/50458662      By the way thats not the only one that dosent fully download a lot of the older streams have that issue as well which is why i think it may have something to do with them being older VOD'S not sure though.

**Comment by Franiac** [comment]
@DarkOblivion This issue is very common, but I cannot do anything about it. It only happens to VODs that are older than 2014. I have never seen this related to newer VODs.
The thing is that FFMPEG throws some weird errors in the encoding process that I basically do not understand. I am not the video-audio-media-kinda-guy when it comes to software development. So if the encoder fails... well... shit :) unless you find someone that is better at all those encoders and stuff.
I will close this issue knowing that it will popup again. But the only thing I could do is restricting TL to VODs newer than 2014.

**Comment by DarkOblivion** [comment]
@Franiac ok thanks for the information, i appreciate it.
