### ISSUE TITLE
Twitch DMCA strikes - why is TL not helping?

### ISSUE THREAD

**Issue by ibex-are-goats** [Franiac/TwitchLeecher#495]
Twitch culture is being wiped out as streamers are being forced to delete all their clips to avoid new copyright strikes. The problem is of course not that EVERY clip has copyrighted music... it's that there are too many clips to check, so streamers are being forced to delete all of them.

It will be crucial to back up these clips to remember the last several years of twitch culture.

Clip leeching feature is now high priority!

**Comment by Franiac** [comment]
The only person responsible for deleted videos or clips due to copyright violations is the streamer. If the streamer does not take copyright seriously it is that person's own problem. Twitch Leecher was never and will never be a tool to bypass copyright rules.

That said... I am the one defining priorities. And there is exactly one thing that is more important than anything else right now:

My 5 week old daughter

**Comment by ibex-are-goats** [comment]
I'm sorry for the misunderstanding :)

Downloading clips does not violate copyright. It's just a missing feature in the program. The feature was never needed before the war between Amazon and the music companies began. Now everyone on Twitch must delete all clips. There could be 1 clip with music in 10 000 and they all must be deleted because there's no way to find that 1 clip. This will be a disaster for the last 5 years of Twitch culture.

**Comment by Franiac** [comment]
Let me be clear... using copyright protected stuff in streams was against the law in 1990, 2000, 2010, 2020 and will be in 2150. If the streamers had not used copyright protected music in their streams, they would not need to delete all their stuff now (including the legal clips). Just because there never happened anything does not mean it wasn't against the law 5 years ago. The DCMA strikes are valid because the copyright law is right in this case if you like it or not. Streamers shouldn't have used protected music ever, but they did, that's the mistake. Just because someone in the music industry spotted Twitch as a target now does not change the way or the priorities in which I develop TL, which again is ON HOLD because I became a father 5 weeks ago.

Streamers fucked up and now they are running around like headless chickens, that's unfortunate but nothing I can change. I can't just stop parenting my daughter, sorry. And let's be honest, all those clips where worth a KEKW when it happened but who really cares about a 5 year old clip now, let alone 10000 of them.

This all does not mean I support what the music industry is doing, but unfortunately they are in the right. As a streamer you have to be careful of what you are streaming.

**Comment by ibex-are-goats** [comment]
I appreciate that you don't care about clips or people who played music, but I think punishing clips that have no music is wrong.

**Comment by Codereaders** [comment]
> but I think punishing clips that have no music is wrong

Ask your streamer to not be careless and lazy at the same time. It's his/ her fault he/ she infringed copyright. He/ she should care about what he/ she did.

@ibex-are-goats let's clearify that a bit. If you do not have the right to use/ publish music, it's rather fair that Twitch forces you to remove those clips. But that only counts for clips in which music you haven't the license for is being used. All other clips could be kept online. So streamers who do not care about copyright and are too lazy to sort out clips they don't have the required rights for do not need to cry at all. Their lazyness and carelessness should not be supported at all.

**Comment by Franiac** [comment]
> I appreciate that you don't care about clips or people who played music, but I think punishing clips that have no music is wrong.

@ibex-are-goats I give you my honest 2ct and I ignore your personal attacks. I care a lot actually. See my avatar and the letters "FSR"? That's "Fake Smile Revolution"... google it!

I am a musician. Do I want everybody in the world to be able to use my music and my creative work however they want? Fuck no! I invested years into making my album. Do I want streamers to be able to stream my music and maybe get a liiiiiiiiittle share for it? Hell yes! Todays music industry is fucked up. They want "all or nothing" and they are killing themselves slowly with it. Basically if they succeed, we have a musicless internet.

Spotify made pirating music obsolete. Netfix made pirating movies obsolete. What we actually need is a system where streamers can subscribe to a service that allows them to stream copyright protected music. Everybody wins. The artists get their share, the music indusrty gets their share and the streamers can use copyright protected music.

As I said, I don't support what the music industry is doing right now, they are greedy fuckheads only looking for $. But I support intelectual property like my album. You can download it for free from my website! I am very open as you see. But just because you can downlaod it for free does not mean you are allowed to do whatever you want with it. It is still mine.

You have to obey current law. Streamers ignored it and now they are paying the bill. That's totally ok in my eyes. What is not ok ist the fact that they all act like "everybody did it so it's legal, poor us, fuck the industry". No, all those lazy ass titty streamers craving for subscriptions should get their shit together and contemplate about what they did and shut their mouths.

And the same goes for Twitch Leecher by the way. You can download videos from other streamers, you can watch them offline. But I dare you to upload or use them for your own good in any way, that's illegal. Twitch Leecher is not a pirating software. It's a tool for making videos available offline. That said, I don't support downloading clips with copyright protected music in them just "because otherwise they are lost". It's ok, because they're illegal anyway.

This is an unpopular opinion on the internet, hard to digest, but I know I am right.

**Comment by Franiac** [comment]
Re-opening for visibility, because my mailbox explodes...
