### ISSUE TITLE
Videos get broken after the download

### ISSUE THREAD

**Issue by Iviaca** [Franiac/TwitchLeecher#50]
Dear @Franiac , I came across some problems in the downloaded videos. 
I came across TwitchLeecher only last week and it works quite well, but after I updated it to the newest version (maybe it is after updating, I download 2 videos last week and it all went fine, but didn't try to download and check videos this week before updating), I found all 3 videos download get several missing seconds after some interval. It appears to be repeatness of broadcasted period and mosaic.

and when I download videos (of 1~2 hours) and try to check them, my computer(32x; Win10) shows that not enough memory so that I have to restart it to watch, this might be my PC's fault but I'd like to know if there's some solution to the broken videos, Thank you.

**Comment by Franiac** [comment]
@Iviaca You need to understand, how TL internally works. TL does NOT re-encode or manipulate the VOD from Twitch. This is a common misconception. TL uses FFMPEG which is a standalone .exe (in the TL directory). And this exe is only used for one single purpose:

TL downloads a VOD from Twitch in form of a lot of little video chunks (can be thousands). Those chunks are playable in VLC actually. They are already encoded and in the same format Twitch plays them back in the browser for example. Now the only thing FFMPEG does in TL is: Merging all those chunks into a single file again. There is no re-encoding whatsoever (otherwise the encoding process would last hours, not minutes). TL actually says "Encoding" but it should be changed to "Merging" in order to tell the truth.

What now happens is that FFMPEG can run into errors while merging because of various issues:

- The streamer uses a messed up config in OBS/XSplit/... (variable bitrate, no keyframes, the list is long)
- The streamer had connection issues during the stream and the video is somewhat "broken" at some points

So basically there are issues that occur in FFMPEG that does not occur in the browser on Tiwtch.tv and I cannot do anything about it. If TL receives shit from Twitch, it cannot turn it into gold no matter what.

That said, it is basically impossible that there are differences between versions of TL regarding video output because since TL 1.2.0 TL uses the exact same FFMPEG version and command line arguments for it.

And if you state that earlier videos worked fine, the possibility that the new videos have issues on Twitch is very high.

I can look into it and see what I can do if you provide the following:

- Url of the Twitch VOD you have issues with
- Download settings that you used (quality and cropping if enabled)
- Exact time of the issues in the downloaded VOD

I hope that helps understanding TL a little bit more :)

**Comment by Iviaca** [comment]
@Franiac 
Hello, I kinda know how TL works after your description but I don't quite think it's because of connection issue or something like that. I'd just take one video for an example:

- URL: https://www.twitch.tv/stonehearth/v/81821941 (source videos doesn't appear to have any problem when I watch it on Twitch)
- Video Quality: Source; cropping disabled;
- Problematic time area:
22:19-22:30
29:42-29:45
30:35-30:40
44:59-45:07
45:10-45:53
46:11-46:17

The time listed above are exact time of issues in the first downloaded video. Today I downloaded that same one once more but repeatness and mosaic in the issued time for the first video don't appear in the second video:

![su_321o _x0w8a_ tx30dn](https://cloud.githubusercontent.com/assets/10858207/17454854/49f9f9e2-5bd8-11e6-90f8-149541c8a9bd.png)

![h8fjg b3 7602_o 5h1tx](https://cloud.githubusercontent.com/assets/10858207/17454856/4ffac13c-5bd8-11e6-9ab2-978ae5cb88d5.png)

I wonder that it would be the problem caused by like computer memory as today I download the second video upon the start of PC. (don't know whether the second one is free of error, for I haven't checked it through yet)

**Comment by Franiac** [comment]
@Iviaca I downloaded the given VOD 5 times in a row now without any problems. I doublechecked everything multiple times and I cannot find any issues with the downloaded VOD. I even tried 3 different PCs.

Your PC might very well be the source or the problems. Why are you using a 32 Bit operating system? This is odd because there are no more 32 Bit processors to buy out there in 2016 (the consumer processors at least from AMD and Intel). The problem is that your 32 Bit operating system is only capable of using 3.5GB of RAM no matter how much you have installed. This could be a problem for FFMPEG when it tries to merge a 6GB VOD... but I say MAYBE... I do not really know.

Now the situation is: Your PC is the only one that seems to have a problem with the given VOD. If you have a different PC (with a 64 Bit operating system), please try downloading on that one multiple times and see how it works.

And in addition to that you finally managed to download the VOD on your computer without any problems after restarting. That is indeed weird but it is proof that it works.

 Please give some feedback on how it worked out for you now. Then I think this issue can be closed.
