### ISSUE TITLE
Error when downloading larger files

### ISSUE THREAD

**Issue by kevindecaf** [Franiac/TwitchLeecher#509]
So I’m trying to download a large file probably 8 hours and I keep getting a storage error when I have a 1tb of free storage, and it works fine on 2 or 3 hour streams, and I’ve tried uninstalling and reinstalling and it hasn’t worked, I also tried disabling all my anti virus just in case, I’m out of ideas. Any help would be much appreciated. Thank you

**Comment by Franiac** [comment]
I have another idea: What kind of file system is your storage using you are trying to download the video to?
Often external USB drives are formatted with FAT32 or other ancient file systems that connot store files larger than 4GB.
Because your description of the problem points exactly that way. Short videos work, long videos don't...

**Comment by kevindecaf** [comment]
I can download file bigger than 4GB i downloaded a one that was 6GB

**Comment by Franiac** [comment]
Well, disk space errors are thrown by the operating system. TL does not do any storage or disk checks.
Since you did not provide any log files as stated in the issue template, I cannot help you, sorry.

**Comment by kevindecaf** [comment]
I will post my log if that helps
