### ISSUE TITLE
cant login with my new twitch account to enable sub only vod downloading, help

### ISSUE THREAD

**Issue by washingleaves** [Franiac/TwitchLeecher#51]
so ive downloaded your most recent release , 1.3 x64 and started it ,and immediately went to enter my new twitch account login credentials , all i get is a >

Oops! We encountered an unexpected error logging you in. Please try again.

please help a bro out , thanks man

**Comment by Franiac** [comment]
The login dialog has nothing to do with Twitch Leecher. All you see in TL is a integrated web browser showing the Twitch login dialog. If anything there goes wrong, it is a Twitch problem. The error message is served by the Twitch servers, not from TL.

**Comment by washingleaves** [comment]
nope these guys have the same issue with another twitch app ,

here


https://github.com/bastimeyer/livestreamer-twitch-gui/issues/209


again , using my regular browser login is no issue , it your app that needs fixing , so please, id appreciate

**Comment by Franiac** [comment]
Please let me decide when my application needs fixing. The other programmer also stated exactly the same as me (since we both know exactly how the authorization process works).

The login dialogs in both of the applications (Livestreamer and TL) only react to a redirect from the Twitch server. If the login process does not succeed or the redirect does not happen, we cannot do anything about it since it is not related to source code of our programs. And if you follow the issue on Livestreamer, that following day all worked again without any actions taken.

I do not have any other complaints regarding this issue, neither on Reddit, GitHub or via my support mail. I put this on standby and see if other people encounter the same issue. Other than that there is nothing to fix for me at the moment.

**Comment by Franiac** [comment]
We have another complaint #53 about authorization. Seems to be totally different. Reopening.

**Comment by Franiac** [comment]
@washingleaves  Please contact me on contact@fakesmilerevolution.com in order to track down the issue if it still persists. I cannot reproduce the issue on my machine so I want to implement a logging mechanism to see what is happening on your PC. I would send you a experimental build of TL to test things.

**Comment by Franiac** [comment]
:tada:

**Comment by washingleaves** [comment]
nope still dont work

**Comment by MYelzhan** [comment]
Hello every one!

I have the same problem @Franiac!

I am new user, and cannot to log in your application. When I try to join there is pop up the same issue like something went wrong and please try again!

Please, can you help me?

<img width="891" alt="Screen Shot 2022-10-13 at 08 48 34" src="https://user-images.githubusercontent.com/68470544/195522406-01497727-3146-43d9-8a63-cff4ac5657c3.png">

**Comment by Franiac** [comment]
@MYelzhan You are pretty late commenting on a closed issue from 2016. And you should read #803 😄
