### ISSUE TITLE
Suggestion: Android App

### ISSUE THREAD

**Issue by ihaveabigfridge123** [Franiac/TwitchLeecher#522]
I would really like this as an Android app so I could download twitch streams whilst out and about. It would be made worth your while with occasional video and banner ads.

**Comment by Franiac** [comment]
Not the first time this comes up and I am a big fan of the idea. So far it is impossible because one cannot easily port a C# WPF application to Android (Java). In a perfect world I have the time to rewrite TL as an Electron app for Windows/Linux/Mac and be able to use the GUI part 1/1 on mobile devices as well.

I have elaborated this quite some time ago and there is only one real question: Since I had to use Cordova or Capacitor or any other HTML5 wrapper framework to get the GUI on mobile phones, what is about FFMPEG? I never came across any production-ready wrapper for any of those frameworks. Even for Electron there are only a couple ugly looking FFMPEG wrappers that I would never use in any app like TL.

What will NOT happen, though: A completely decoupled native Android project of TL that does not share source code with the other platforms. I am a big fan of WORA (write once, run everywhere) and in 2020 that means HTML, SCSS and Typescript. Personally I am a fan of the Angular Framework.

Spoiler alert: There is a private repository here under my name in order to begin the rewrite of TL as an Electron app with Angular. Wether this will eventually happen, I cannot say at this point.

I can only say that I lost interest and vigor in writing WPF apps because XAML kills my soul. Building responsive GUI's and nice themes in XAML is the worst and I proved at work that I can build the same GUI in 1/3 of the time with web technology on desktop systems. At work we transitioned to Electron in many projects and it is the perfect technology for something like TL. Only the FFMPEG issue is a thing.

I'll keep this open for discussion. If anyone has something to add or simply knows stuff we should check out, feel free to contribute.

**Comment by IVLIVS-III** [comment]
In my opinion [Flutter](https://flutter.dev) generally is a valid alternative to Electron.
Up until recently Flutter was focused on mobile app development but is expanding quickly into Web ([flutter.dev/web](https://flutter.dev/web)) and desktop apps ([flutter.dev/desktop](https://flutter.dev/desktop)). Same single-codebase concept.

I've been developing flutter apps as side projects for ~2.5 years and can recommend it.
The Windows-Platform is currently lacking behind, but might be worth it to explore that framework.

There is also an up-to-date [FFmpeg implementation for Flutter](https://pub.dev/packages/flutter_ffmpeg) apps.

**Comment by Franiac** [comment]
@IVLIVS-III Isn't Flutter Dart-only? Never put my nose into that language. I don't really know much about it, but isn't Flutter some kind of magic transpilation blackbox? Meaning you write a Flutter/Dart app and when you build it for Android it magically generates an apk or an Android Studio project? How does it work? I really don't know anything about Flutter and it's build processes.

**Comment by IVLIVS-III** [comment]
@Franiac First of all, I'm sorry for taking so long to respond, somehow I didn't get a notification.

### Is Flutter Dart-only?
Flutter in itself is a UI toolkit using the Dart language, i.e. **if you want to use Flutter you have to program in Dart**. However, I found Dart to be pretty easy to pick up and generally an intuitive programming language. Dart is a typed language and kind of resembles Kotlin/Java or TypeScript(JavaScript) and similar languages (here are some [language samples](https://dart.dev/samples)).

### Flutter build process
Dart and by extension Flutter compiles AOT directly to ARM and x64 machine code for mobile/desktop/server, i.e. creating an APK / app bundle for Android, or to JavaScript for web. This is pretty much a black box, that can only be customized by a couple of flags, which in itself are controlled by the Flutter framework. So **there is not a lot of developer control over this build process**. Here is some more info on the [dart2native](https://dart.dev/tools/dart2native) and [dart2js](https://dart.dev/tools/dart2js) tools.
However, I personally never needed to know much about the inner workings of the build process anyway.

There is also a VM for development supporting hot restart and hot reload, meaning you don't lose the state of your application when changing some code and reloading after.

### Platform control / integration
When creating a new Flutter project, Android, iOS, macOS, Windows, Linux and web-projects are created at the same time. You can change those platform specific projects however you like, e.g. adding specific launch/splash screens or app icons.
It is also possible to use so called "platform channels" to communicate with the underlying platform or implement platform specific functionality. However everything platform specific has to be implemented separately for every platform you want to release on (_not surprising_).
A lot of platform specific functionality is already available directly in Flutter through [plugins](https://pub.dev).

You could even start with platform specific projects and add a Flutter project as some sub-component. This is called [Add-to-app](https://flutter.dev/docs/development/add-to-app) and currently only supported for Android and iOS. For example to add a Flutter project to an existing Android app you have to add a `FlutterActivity` to your `AndroidManifest.xml`, which then can be launched like any other `Activity`:
```
<activity
  android:name="io.flutter.embedding.android.FlutterActivity"
  android:theme="@style/LaunchTheme"
  android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
  android:hardwareAccelerated="true"
  android:windowSoftInputMode="adjustResize"
  />
```
```
myButton.setOnClickListener {
  startActivity(
    FlutterActivity.createDefaultIntent(this)
  )
}
```
------------------------

I hope this was useful. If you have any questions, don't hesitate to ask.

**Comment by Franiac** [comment]
@IVLIVS-III Thanks a lot for the input!

> there is not a lot of developer control over this build process

That renders it unusable. I won't go down that rabbit hole again. Do you know Xamarin? The thing Microsoft bought in order to be able to program C# source and generate mobile apps? Horrific! And it's exactly the same thing. As long as you do not have special needs and your implementation always lives inside the boundries of the framework, everything is nice, easy to use and generally brilliant. Then there comes along this one feature where you are like "shit, I want to paint that control myself" or "hook up that one event natively here". That's when all those beautiful frameworks fall apart very quickly. And if you deep-dive into the utility classes of TL, you find a lot of this stuff. That's why I asked the question about the blackbox immediately. You always end up at that point where you need a plugin that doesn't exist.

I don't want to limit my creativity because of the boundries of the framework. Take Ionics Capacitor for example: They have had enough of the Apache Cordova blackbox. Basically Cordova is Flutter in HTML/JS/CSS. An Android project is generated and compiled and the only "hook" into the build process are some callbacks and a XML configuration file, uhhhghhh. Capacitor also generates the Android project a single time, but makes it
1. part of your source control (every file is under your control)
2. makes it updatable (and offers migration automation that actually works)
3. makes it syncable (if your webapp changes, you aync you Android project without generating it new every time

So whatever you do, you have 100% control over everything, the webapp, the ios project, the android project, the PWA, every build process, every little compile flag and so on. That's the way it needs to be. I have tried so many frameworks and every single one tried to throw me into a cage I could not get out of whenever I needed to and I hated it.

Sure, if you want to go native for a feature, no matter what framework you use, you have to write platform specific code in platform specific projects. But if that's the case (and it always is) I choose a framework that let's me do it properly.

Flutter/Xamarin/Cordova/Blazor or whatever blackbox framework there is are telling me "ok bro, you can go native if you want, but aaaaaaaaactually we do not reeeeaaaaaly want you to do it because we own the build process, so please behave!"

Electron and Capacitor are telling me "You need to go native? Sure, here you go, do whatever you want, if you fuck it up, it's your fault!". And that's the way it should be and how I like it.

I don't want to hate on the other frameworks, but I don't see how they are sufficient for what I want to do. Let's look at ffmpeg on Windows again. Flutter is like "here's a plugin, use it, if you need something that's not in the plugin, well... bad luck, write a complete plugin yourself for every platform, LOL". Electron just lets me run command line tools natively on every platform with inter-process communication.... job done!

So yes, I definitely see how Flutter can be a great framework for limited usecases that do not step outside of the boundries. But for me personally and Twitch Leecher... I honestly do not think so 😄

**Comment by IVLIVS-III** [comment]
@Franiac I've never looked at frameworks from that perspective, but now I can definitely see those problems coming up.
All the best with whatever further development there will be for Twitch Leecher.

**Comment by Franiac** [comment]
@IVLIVS-III Thanks a lot!

**Comment by Franiac** [comment]
I digged a little bit more on this and came to the conclusion that an Adroid app is not capable of downloading a Twitch VOD efficiently. A long VOD can easily consist of 10000 parts or more.
On a desktop machine you can implement parallel downloads of 10-20 parts quite nicely. On an Android device with the potential to go to sleep mode (pause/resume) and having to work with background processes and limited parallel downloads I don't see, how something like TL would run satisfactory for an user.

I am currently working towards Linux and Mac in a new version of TL (far future, though), that makes more sense than incorporating mobile devices.
