### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by MightyMcdonold** [Franiac/TwitchLeecher#524]
I was just doing my stuff, then my antivirus (trend micro) detected a threat and said a virus in twitch leecher was trying to attack my c: drive? ???

I haven’t updated it in a couple weeks but what the hell

**Comment by Codereaders** [comment]
First you should get a basic understanding on how Antivirus software works.
Antivirus software basically works in two ways:
1. pre defined code patterns - Many "viruses" are being detected by certain patterns within their code.
2. software behaviour - Certain patterns regarding access, privileges etc. might be classified as suspicious.

Both methods, even though they give a good first estimation are not really accurate - a thing that is often criticised by security experts.

I'd assume that this is a typical false alarm. - As I don't know the binary nor have I read the complete source code, I obviously cannot say this for sure!

**Comment by Franiac** [comment]
What @Codereaders said...

TL is 100% open source. There are people searching for such stuff, especially when a software went viral (no pun intended). Another issue is that TL is not signed. The installer is not signed and the installed application is not signed (that proves the app is from me). A certificate to do so costs a good amount of money and since I don't make money out of TL other than a few generous donations from amazing people I simply can't buy one, or at least I don't want to spend my own money on it, to be honest.

Just make sure you download from GitHub and not from some shady website. I cannot guarantee that noone distributes a TL installer that has a virus but I can guarantee that the installer here on GitHub is 100% the code from the repo and with that 100% free from any malicious code.
