### ISSUE TITLE
Login keeps giving me error - pic included

### ISSUE THREAD

**Issue by prabhraj** [Franiac/TwitchLeecher#53]
Keep getting this error every time I click login try to authorize my account.

![twitchleecherprob](https://cloud.githubusercontent.com/assets/20963062/17579104/5c2d80e0-5f46-11e6-8d4f-0d53413f6e15.png)
![twitchleecherprob2](https://cloud.githubusercontent.com/assets/20963062/17579102/5c2af41a-5f46-11e6-821b-c0eec3bdde05.png)

**Comment by prabhraj** [comment]
Update: no longer gives the message (at least for now) but now gives me this dialog box to open a a file called new565yadayadayada 

![twitchleecherprob3](https://cloud.githubusercontent.com/assets/20963062/17579838/16ddd2d0-5f4e-11e6-8d98-cb91403843a9.png)

**Comment by Franiac** [comment]
As I already stated in issue #51 Twitch seems to have problems in the authorization progress. Threads on the developer forum are active. I do not have any means in order to fix those errors because it all runs on the Twitch servers (all you see in TL is a integrated web browser).

One curious thing remains still: My 3 main Twitch accounts are working perfectly so I cannot reproduce the error on my site (Germany)

**Comment by Franiac** [comment]
@prabhraj Please contact me on contact@fakesmilerevolution.com in order to track down the issue if it still persists. I cannot reproduce the issue on my machine so I want to implement a logging mechanism to see what is happening on your PC. I would send you a experimental build of TL to test things.

**Comment by Franiac** [comment]
:tada:
