### ISSUE TITLE
Feature Request: Download sub only vods

### ISSUE THREAD

**Issue by antonioExpositoRodriguez** [Franiac/TwitchLeecher#531]
Hi, first of all, thank you for this wonderful piece of software. I would love to see implemented in the future a way link our twitch accounts to download sub only vods of those channels we are subscribers.
  
  I don't know how complex/hard is the issue so maybe I am asking for something not possible, but after the DMCA wave most channels putting their vods behind closed doors and this feature would be truly helpful. 

  Anyway, thank you for your hard work and sorry for my bad English.

**Comment by Codereaders** [comment]
It's quite straight forward in case you submit the user's credentials (username, token) in certain requests.

**Comment by Franiac** [comment]
I recommend both of you reading through #419 😄 

There is a reason why TL 1.8 happened and why sub-only downloads were removed from it.

@Codereaders If you know something I don't know, let me know 😄

**Comment by Franiac** [comment]
@antonioExpositoRodriguez And just for your info: The whole DMCA thing is because lazy Twitch streamers do not give a shit about copyright laws. If they don't play copyright protected music, there's no problem.  I have no intention of helping people thinking stealing copyright protected music is ok. Context: I am also a musician with an album out in the world, so I am a little bit biased here 😄

**Comment by Codereaders** [comment]
@Franiac I'm fully aware of that thread.

However, I personally use the same code base to download VoDs for a long time now:

(1) lookup the channel's vods (kraken/ helix)  
(2) request an access token (api)  
(3) download the playlist (usher)  
(4) download the video chunks (from the mirror specified in the playlist)

The only changes I did over time:

1. I moved from kraken to helix. kraken should still work fine but helix is way more convenient.  
   Your requests look more standardized and you have to do less normalization on the results too.
2. I had to update my token. `OAuth ...` now is called `Bearer ...` at some places.  
   I'm not exactly sure anymore why Twitch did that change, but you can even read about it on the Twitch developer pages.
3. I had to slightly modify some regexes to properly extract the mirrors mentioned above.

Of course Sub-Only VoDs still only can be downloaded in case the auth refers to a channel that's eligible to see the VoD.

**Comment by Franiac** [comment]
@Codereaders That is very interesting since we were trying everything possible to get it working again and failed. Helix is definitely better but lacking a lot of stuff still. You still cannot get the resolutions and framerates for example. That is one giant clusterfuck in Kraken that need a lot of edgy normalization.

Do you have your code open source or is it just a private project? Because if it works I would not have to re-validate every little step in case I re-introduced sub-only downloads to TL. Do you have anything on GitHub?

**Comment by Codereaders** [comment]
No, I haven't published my code yet. It's basically a containerized php application.  
So not necessarily what end users expect to deal with. However, I can put the relevant parts online for you soon.

What information exactly are you missing? The resolution and the frame rates can be extract from the playlist provided by usher.
There should definitely be a better way, to get those information via a proper api, but for now it works fine.

**Comment by Franiac** [comment]
Maybe you could just upload the entire code to a private repo an give me access? Your project stays hidden this way. I used to program PHP, so I surely can dig out the relevant parts. I am interested in how you get the access tokens, how you determine if the VOD is sub-only and what the requests are in order to retrieve the playlist array.

**Comment by T0BiD** [comment]
Any updates on this?

**Comment by Tanerax** [comment]
I was actually able to get this to work in the latest version with out any issue... 

I added a single line to TwitchService.CreatePrivateApiWebClient

wc.Headers.Add("Authorization", "OAuth <my_token>");

I got my token from looking at a gql request my browser performed when loading a "sub-only" broadcast. I can't see why it wouldn't be possible for the app to be able to authenticate for the local user and access the broadcasts?

**Comment by Franiac** [comment]
@Tanerax We have to verify. I removed sub-only downloads from TL because the token that came back from the auth API was not accepted. Sure the token from the browser works as you say but if TL authenticates for the user, the token will be different and that was the primary issue. The API did not accept the token as a subscriber regardless of actually being one or not. So for a valid test you would actually have to authenticate via the API and get a completely new token from there. The browser token does not verify anything, unfortunately.

**Comment by Franiac** [comment]
Ok guys, I need some help. There is a new [BRANCH](https://github.com/Franiac/TwitchLeecher/tree/subonly) in which I have re-implemented sub-only video downloads.

I cannot really test this because I don't know any channels that hide their videos behind the paywall.

If you're a dev, you can compile the branch and test/debug it directly.

For all others: There is [THIS](https://franiac.com/TL_SubOnly.zip) file. Unzip it and run TwitchLeecher.exe. Don't overwrite any installed TL, that will brick the installer in the future. The test version will show up as 1.8.4. That will change on a real release.

**Comment by sdynam0** [comment]
Hey! Just tried it, I'm subbed, but I get this message:
"This video is sub-only but you are not subscribed to 'streamer'!"

**Comment by Franiac** [comment]
@sdynam0 Can you tell the channel name please. Maybe I just use my Prime to sub for testing purposes.

**Comment by Franiac** [comment]
@sdynam0 Or would you be so kind to test another version with logging enabled (TL will write a file with some non personal logging information to track, what's going on)

**Comment by Franiac** [comment]
I made a new version with logging:

[TL with logging](https://franiac.com/TL_SubOnly.zip)

As soon as you click on "Download" on a video, a file named "tl.log" should get written the the TL directory (where the .exe is).

**Comment by m4ryou5h** [comment]
Hi guys,

I just gave it a go on my machine, log below.

I'm a sub of: "markettraderstv"

{"data":{"videoPlaybackAccessToken":{"value":"{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p60\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1632810980,\"https_required\":true,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":1058435233}","signature":"c6933fa01933b59b4d848b52773a33cb0f71c553","__typename":"PlaybackAccessToken"}},"extensions":{"durationMilliseconds":89,"operationName":"PlaybackAccessToken","requestID":"01FGKD7CNEJPFKNDJ0GPKE8ZWT"}}

**Comment by Franiac** [comment]
@m4ryou5h Did you authorize TL via the Twitch icon in the titlebar?

**Comment by m4ryou5h** [comment]
> @m4ryou5h Did you authorize TL via the Twitch icon in the titlebar?

Yes, I did.

I just revoked the authorisation and re-authorised again and got the same errore message. 
TL below. I hope that helps

{"data":{"videoPlaybackAccessToken":{"value":"{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p60\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1632814165,\"https_required\":true,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":1058435233}","signature":"ea736a39611866b6dea5a13df389591b344c1b12","__typename":"PlaybackAccessToken"}},"extensions":{"durationMilliseconds":79,"operationName":"PlaybackAccessToken","requestID":"01FGKG8JFPA4WYBHY94PTDD9R0"}}

**Comment by Franiac** [comment]
Again a new version:

[TL with logging](https://franiac.com/TL_SubOnly.zip)

The problem is, the "privileged" flag in that JSON mess should be `true` and not `false` if TL is authorized.

**Comment by Codereaders** [comment]
@Franiac yes, you're correct, the flag should be true.

What endpoint do you use to request token and signature? Any of the old ones or the gql API endpoint?
Could you show the request you do?

**Comment by Franiac** [comment]
@Codereaders Check [here](https://github.com/Franiac/TwitchLeecher/blob/subonly/TwitchLeecher/TwitchLeecher.Services/Services/TwitchService.cs) line 213

We had an issue in the past with this, I remember very clearly. We needed to add the query parameter. But then the Authorization header was `OAuth` but that does not work anymore. `Bearer` works but then `privileged` ist false. I don't really know, what the problem is.

**Comment by Codereaders** [comment]
I use both the OAuth as well as the Bearer token in my application. For some endpoints I ended up setting the Bearer token for others (such as the gql endpoints) I use the OAuth token. Which for my cases is the same token just having it prefixed differently.

Pretty much simplified it comes down to this:
```php
$request_url = "https://gql.twitch.tv/gql";
$request_method = "POST";
$request_headers = [
    'Accept' => "application/json",
    'Client-ID' => $client_id,
    'Authorization' => $oauth
];

$request_body = (object)[
    "operationName" => "PlaybackAccessToken",
    "variables" => (object)[
        "isLive" => false,
        "login" => "",
        "isVod" => true,
        "vodID" => "{$video_id}",
        "playerType" => "channel_home_live"
    ],
    "extensions" => (object)[
        "persistedQuery" => (object)[
            "version" => 1,
            "sha256Hash" => "0828119ded1c13477966434e15800ff57ddacf13ba1911c129dc2200705b0712"
        ]
    ]
];
```

For the response I simply extract the signature and the token, no matter what else is being set:
```php
return (object)[
    "sig" => $response->data->videoPlaybackAccessToken->signature,
    "token" => str_replace("\\", "", $response->data->videoPlaybackAccessToken->value)
];
```

**Comment by Franiac** [comment]
In addition, I also extract the `sig` and `token` but so far I could judge if the video is sub-only or not and provide a message according to the outcome.

There were 2 possibilities in TL 1.7.3:

1. privileged is true => sub-only video
2. restricted_bitrates array is filled => sub-only video

Question: If you run your software, what is `privileged` saying? Because if you get `true`, something different must be off.

**Comment by Codereaders** [comment]
So, I finally found a sub only VoD on a channel that I was subscribed to.

I discovered something interesting:

non-subonly + Bearer token
```json
{"authorization":{"forbidden":false,"reason":""},"chansub":{"restricted_bitrates":[]},"device_id":null,"expires":TIMESTAMP,"https_required":true,"privileged":false,"user_id":null,"version":2,"vod_id":VOD_ID}
```

non-subonly + OAuth token
```json
{"authorization":{"forbidden":false,"reason":""},"chansub":{"restricted_bitrates":[]},"device_id":null,"expires":TIMESTAMP,"https_required":true,"privileged":false,"user_id":USER_ID,"version":2,"vod_id":VOD_ID}
```

subonly + Bearer token
```json
{"authorization":{"forbidden":false,"reason":""},"chansub":{"restricted_bitrates":["160p30","360p30","480p30","720p30","audio_only","chunked"]},"device_id":null,"expires":TIMESTAMP,"https_required":true,"privileged":false,"user_id":null,"version":2,"vod_id":VOD_ID}
```

subonly + OAuth
```json
{"authorization":{"forbidden":false,"reason":""},"chansub":{"restricted_bitrates":[]},"device_id":null,"expires":TIMESTAMP,"https_required":true,"privileged":true,"user_id":USER_ID,"version":2,"vod_id":VOD_ID}
```

For some of the responses the USER_ID and the restricted bitrates haven't even been set.
I removed some information of course and put in placeholders (TIMESTAMP, USER_ID, VOD_ID).


The scopes.. well, I'm sure not all of them are required:
```
"scopes":["chat_login","user_presence_friends_read","user_read","user_subscriptions","channel_commercial","channel_editor","channel_feed_edit","channel_feed_read","channel_feed_report","channel_read","collections_edit","communities_edit","communities_moderate","user_edit","user_entitlements_read","user_follows_edit","user_friends_edit","user_friends_read","user_presence_edit","user_subscriptions_edit"]
```

**Comment by Franiac** [comment]
@Codereaders That makes no sense, if I use `OAuth` on non-sub-only videos, I get a 401 WebException. What do you do differently than me?

But your test shows exactly my previous implementation: Either privileged is `true` or the array is filled.

**Comment by Franiac** [comment]
@Codereaders Important question: Do you use the token from the browser or do you also get the token from the API? Becasue that also seems to make a big difference.

**Comment by Codereaders** [comment]
This is the exact code I ran for my previous tests:

```python3
import requests

class GQL(object):

    _base_url = "https://gql.twitch.tv/gql"
    
    def __init__(self, client_id, authorization):
        self._client_id = client_id
        self._authorization = authorization
    
    def get_video_access(self, video_id):
        endpoint = f"{self._base_url}"
        method = "POST"
        params = {}
        data = {
            'operationName': 'PlaybackAccessToken',
            'variables': {
                'isLive': False,
                'login': '',
                'isVod': True,
                'vodID': f"{video_id}",
                'playerType': 'channel_home_live'
            },
            'extensions': {
                'persistedQuery': {
                    'version': 1,
                    'sha256Hash': '0828119ded1c13477966434e15800ff57ddacf13ba1911c129dc2200705b0712'
                }
            }
        }
        headers = {
            'Client-Id': self._client_id,
            'Authorization': self._authorization
        }
    
        response = requests.post(endpoint, json=data, params=params, headers=headers)
        
        if 200 <= response.status_code and response.status_code < 300:
            result = response.json()
            signature = result['data']['videoPlaybackAccessToken']['signature']
            token = result['data']['videoPlaybackAccessToken']['value'].replace("\\", "")
            return signature, token
        raise Exception("cannot query the gql api")
```

The token I used for testing was the one from the website. But for certain applications I use the client id + token you can request from the API.

**Comment by Franiac** [comment]
I do this:

Call this url the integrated browser in TL:

```
https://id.twitch.tv/oauth2/authorize?client_id=37v97169hnj8kaoq8fs3hzz8v6jezdj&redirect_uri=http://www.tl.com&response_type=token&scope=user:read:subscriptions&force_verify=true
```

The Client-ID is my TL CLient ID.
The response gives me a token. With that token I call:

```
https://gql.twitch.tv/gql
```

with headers:

```
Client-ID -> 37v97169hnj8kaoq8fs3hzz8v6jezdj
Authorization -> Bearer <token>
```

This results in:

```json
{
    "error": "Bad Request",
    "status": 400,
    "message": "The \"Client-ID\" header is invalid."
}
```

The same request with OAuth results in:

```json
{
    "error": "Unauthorized",
    "status": 401,
    "message": "The \"Authorization\" token is invalid."
}
```

Ok, the nI tried Client-ID from the website:

```
Client-ID -> kimne78kx3ncx6brgo4mv6wki5h1ko
Authorization -> Bearer <token>
```

This actually works... BUT... then I call the following in oder to receive the playlist:

```
https://usher.ttvnw.net/vod/{0}.m3u8?nauthsig={1}&nauth={2}&allow_source=true&player=twitchweb&allow_spectre=true&allow_audio_only=true
```

{0} -> vodID
{1} -> sig
{2} -> token

And that results in:

```json
[
    {
        "url": <STRIPPED>,
        "error": "Manifest is restricted",
        "error_code": "vod_manifest_restricted",
        "type": "error"
    }
]
```

So no matter what I do, I cannot get it to work 😞

**Comment by Codereaders** [comment]
Wait you're using your app's client id to request the access token+sig?
You have to use both the user's client id + token.

If you just have their token you can perform a validation request:


```bash
curl -X GET 'https://id.twitch.tv/oauth2/validate' -H 'Authorization: Bearer <access token goes here>'
```

```json
{
  "client_id": "wbmytr93xzw8zbg0p1izqyzzc5mbiz",
  "login": "twitchdev",
  "scopes": [
    "channel:read:subscriptions"
  ],
  "user_id": "141981764",
  "expires_in": 5520838
}
```

**Comment by Franiac** [comment]
Yes, you HAVE to use the app Client-ID because if you open up the url in a browser with their website CLient-ID, the redirect does not work and you don't receive a token + sig.

The validation works for the received token. But still the gql endpoint won't work after that

**Comment by Codereaders** [comment]
I'm not familiar with all the different authorization flows but in case you receive the users' (auth) tokens, it seem to be fine.

For the authorization flow you have to use your app's token, of course, but later on, when you switch to actions performed in the name of the user (requesting the token+sig for the VoD), for my understanding you have to use the user's client id and token. I mean it's still your app that requests (technically) the VoD but the behalf of the user.

By the way naming all tokens "token" makes it a bit odd to read. x)

**Comment by Franiac** [comment]
```
https://id.twitch.tv/oauth2/authorize?client_id=37v97169hnj8kaoq8fs3hzz8v6jezdj&redirect_uri=http://www.tl.com&response_type=token&scope=user:read:subscriptions&force_verify=true
```

I understand what you are saying. The above flow results in a user token, not an app token. There is no Client-ID for a user.
The Client-ID (in my case 37v97169hnj8kaoq8fs3hzz8v6jezdj) is the ID given by Twitch for your app (Twitch Lececher). You need this Client-ID in order to actually do the authorization workflow. With the CLient-ID you then retrieve the user auth token in order to make requests on befalf of the user. There are also App tokens in oder to make requests on behalf of the app. But this is never the case in TL. User or app tokens have nothing to do with the Client-ID. Whenever I use a token in TL, it is a user token.

**Comment by Codereaders** [comment]
> The above flow results in a user token, not an app token. There is no Client-ID for a user.

Correct, and that's the next call to do:

```bash
curl -X GET 'https://id.twitch.tv/oauth2/validate' -H 'Authorization: Bearer <user access token goes here>'
```

It's response contains the user's client id which then can be used together with their token to request token+sig.

**Comment by Franiac** [comment]
The Client-ID will be the exact same (37v97169hnj8kaoq8fs3hzz8v6jezdj)

Like I said, there is no "user client id". It's the Client-ID of TL... so the validate call will also respond with `37v97169hnj8kaoq8fs3hzz8v6jezdj`.

**Comment by Franiac** [comment]
```json
{
  "client_id": "37v97169hnj8kaoq8fs3hzz8v6jezdj",
  "login": "fakesmilerevolution",
  "scopes": [
    "user:read:subscriptions"
  ],
  "user_id": "106811228",
  "expires_in": 0
}
```

This is what a validate responds... the CLient-ID matches...

**Comment by Franiac** [comment]
Wait a minute.... you use `channel:read:subscriptions` and I use `user:read:subscriptions`...

And why is my `expires_in` set to `0`???

**Comment by Franiac** [comment]
Problem is, I actually don't know what to do.

**Comment by spencerhuang** [comment]
> Problem is, I actually don't know what to do.

Just want to say I appreciate your hard work and this feature is definitely a must-have. I'll see what I can contribute on the technical side. If you have new builds, I'm willing to try it out.

**Comment by Franiac** [comment]
@spencerhuang Appreciate it. We are at the exact same spot where we were at the end of #419.

I am thinking about just putting a textfield in the "Authorize" where you actually can copy the browser cookie token. This would be the same workaround as the original pull request but I currently see another way.

I cannot get a token via API that allows me to download anything sub-only from usher.

So basically I could roll out a new sub-only TL version that would come along with a little documentation on how to get the token from the browser devtools. That sucks solid dick because average Joe doesn't know any of this and question issues with "I cannot find token pls help" will be a thing. That's actually what I did NOT want (and therefor declined the original PR).

Me not happy... 😞

**Comment by m4ryou5h** [comment]
I'm not sure if this is helpful, but I'm using "**Get cookies.txt**" chrome extension to export twitch cookies and then I pass it as an argument to download sub-only videos via youtube-dl

https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid

**Comment by HeyMika** [comment]
There is also this extention here (also for multiple browsers) that is even open source: [https://www.editthiscookie.com/](Edit This Cookie). Really easy to get the auth token from there. Might be helpful to look at the source code for a possible implementation into TL?

**Comment by Franiac** [comment]
@HeyMika You cannot get cookies from a browser "from the outside". That would be a serious security issue. Extentions also need the permission to read cookies. I think, a general documentation would be the best since noone really wants to go through the hassle installing an extention in order to get a little token.

**Comment by davepusey** [comment]
I have just got sub-only downloads working again in 1.8.4 and have submitted Pull Request #647 containing the code changes.

**Comment by HeyMika** [comment]
> @HeyMika You cannot get cookies from a browser "from the outside". That would be a serious security issue. Extentions also need the permission to read cookies. I think, a general documentation would be the best since noone really wants to go through the hassle installing an extention in order to get a little token.

Oh okay, didn't thought about that and yes a documentation would be acutally more useful. Would it be smart to do it on the wiki tab here on Github and link it then in TL?

**Comment by Franiac** [comment]
Ok, here's what we can do:

**Solution 1:**

Make the user copy the auth token from the browser into TL and use it for downloading sub-only videos (tested and it works).

\+ No login in TL necessary
\+ No Chromium browser integration in TL
\- The actual website token is used in TL. If something goes wrong, the website login in the browser (outside of TL) could be affected
\- Token cannot be revoked (would log user out from the browser as well)
\- Average Joe (inexperienced users) could run into trouble getting the token from the browser devtools

**Solution 2:**

Instead of just showing the authorization page provided by twitch, we show the entire website (https://www.twitch.tv) within TL. So TL shows the website as if one would open it in Firefox or Chrome. If the user logs in, we can read the auth token cookie set by the Twitch website (HA, GOTCHA!!!).

\+ User can "normally" sign in
\+ Different token from the user's browser login
\+ Token can be revoked
\- Showing the entire website in order to log in looks "unproffesional"

So both solutions are tested and work. What do you guys think?

**Comment by tiripon** [comment]
Hi, I am personally okay with both solutions. I need your brilliant app. It's so useful.
I would be more tempted with solution 1 but solution 2 is very acceptable.

Thanks for all the effort :)

**Comment by HeyMika** [comment]
@Franiac I think going for the second solution is a more user friendly way. About the professionalism, both solution aren't really. The first one requires to do everything yourself what is in my opinion not professionally either so going for the second one is from those two solutions the best. There has to be some indicator that the token and any login detail is not send anywhere if this would be integrated.

**Comment by Franiac** [comment]
I got this working now in the "helix" branch. will be released soon with TL 2.0

**Comment by Franiac** [comment]
If someone wants to check it out, the helix branch is compilable and should run without problems.

**Comment by Liz-chan** [comment]
Thanks! It seems I was able to compile it and log into my Twitch account but unfortunately you have to be subbed to the person to download their sub-only vids. I archive a lot of different streamers so this doesn't really work for me but I'm sure a lot of people will be happy they have the option of downloading VODs from the streamers they support now 😄 In the meanwhile I'll continue using Dave's fork since it still has the option of downloading sub-only VODs without a subscription.

**Comment by Franiac** [comment]
You can use that fork until February 18th. Twitch will start shutting down API V5 then.

Sidenote:

Downloading publicly available videos is an accepted grey area. Twitch does not really hunt down such programs. Downloading videos behind a paywall, though, is 100% illegal. So even if it works and there is something in the future that would TL enable to download such videos, I would not implement it. Streamers have a reason why they want their videos behind a paywall and that should be respected in all cases. So actually I am glad, Twitch removes that option. I myself would be pissed if someone could just download my sub-only videos without even logging in.

**Comment by Liz-chan** [comment]
Yeah that's totally understandable, if you have moral reasons for not wanting to implement it then it's perfectly fine since it it your program after all ^^ I did see that the Helix API and GQL API both support getting the sub-only VODs as well though, so hopefully Dave comes back to implement that and fix the issue with muted VODs.

**Comment by Franiac** [comment]
Not without authentication...

**Comment by Liz-chan** [comment]
> Not without authentication...

Oh, I'm not really sure how they did it, but they use the GQL API here for getting sub-only VODs.

https://github.com/Alissonsleal/TwitchSubVod/pull/131
