### ISSUE TITLE
Question: Where does this key come from

### ISSUE THREAD

**Issue by peavers** [Franiac/TwitchLeecher#536]
Hi, 

Just a random development-based question - You've got a key committed in the repository `kimne78kx3ncx6brgo4mv6wki5h1ko` where did you generate this? 

I've tried to replace this key with my own, but no matter which key/secret combination I use I always get back either a 400 or 410 from twitch. 

The only way to make it work seems to be with that specific key... 

Sorry for the random question!

**Comment by garoto** [comment]
That's [twitch webplayer](https://github.com/search?p=3&q=kimne78kx3ncx6brgo4mv6wki5h1ko&type=Code) own `client-id`, but my memory is fuzzy, so don't quote me on that.

>I've tried to replace this key with my own, but no matter which key/secret combination I use I always get back either a 400 or 410 from twitch

Make sure you're not using your `client_secret` key instead, because that and the `client_id` one are both 30 chars long and look very similar.

**Comment by peavers** [comment]
Ah, that makes sense, cheers. 

Yeah, I was trying to generate my own app client/secret to use but guess I'll just keep using this random one. Thanks for the response.
