### ISSUE TITLE
 Audio out of sync for clips over 15 min

### ISSUE THREAD

**Issue by Giangagamer** [Franiac/TwitchLeecher#545]
Hi, I would like to add another program that creates a desicronism. and it's SONY VEGAS PRO, every time I have to restore audio with video.

**Comment by Franiac** [comment]
That's weird since I remember Vegas Pro working perfectly at least up to version 16. And audio desync has nothing to do with a certain length. It gets worse over time since the audio shifts more and more. Maybe you don't realize it until 15 min.
That said, no matter if it's Premiere, Windows Media Player or Vegas... it's not a TL issue.

**Comment by Giangagamer** [comment]
are you sure iknprobkema is not TL? because downloading a clip of 2 min
does not go out of sync.

Il Lun 4 Gen 2021, 01:35 Dominik Rebitzer <notifications@github.com> ha
scritto:

**Comment by Franiac** [comment]
Like I said, A/V desync increases over time... 2min is short enough to not realize it. And yes I am sure since all TL does is downloading the stream and optionally packing it into a mp4 container. It is the original stream from Twitch. If there is no A/V desync on Twitch and there is A/V desync in your video program, it's the programs fault.

**Comment by Giangagamer** [comment]
but when I download it from the twitch site it doesn't give me this problem
.... that's why I say that the problem is your program .... cmq if you have
already tested ok.

Il Lun 4 Gen 2021, 15:16 Dominik Rebitzer <notifications@github.com> ha
scritto:

**Comment by Franiac** [comment]
You could also try to disable mp4-conversion in the preferences and work with the original .ts file directly. Vegas Pro supports that. This whole issue was discussed multiple times before. TL does not re-encode the downloaded stream, it only concatinates files. Video and audio streams are 1:1 copied from the source. There is no "process" or anything in place that could introduce A/V desync.
