### ISSUE TITLE
Cannot install or upgrade from 1.8.1 to 1.8.2

### ISSUE THREAD

**Issue by EnergyDrink16000** [Franiac/TwitchLeecher#555]
Hello there

I'm new to GitHub and I wanted to write a feedback because I use TwitchLeecher almost daily for streaming saving purposes and I love it.
Today I wanted to download a friend's stream, but I wasn't able to due to an error message but I've noticed there's a new version. I had 1.8.1 installed so I wanted to upgrade, as always.
Upgrading didn't work at all, I clicked on the download button, donwloaded the installer, clicked on the upgrade button, then it started updating... and nothing happened. After a few seconds it just exited the installer without saying anything.
After that I started running TwitchLeecher, but it was still on verison 1.8.1.
Huh. So I uninstalled the program, and started a fresh install. Same thing happened! Clicked on install, the installer waited then terminate ditself without saying anything. 
Then I re-downloaded the 1.8.1 installer, and I was able to install it without any problems. Only the 1.8.2. version is not working, I cannot install it, I cannot upgrade my previous verison either and I can't send any logs because it doesn't make any when this occurs.
I'm in huge need to save some streams right now. I'm not a coder just a casual user. Please help. I'm on Win7.

**Comment by Franiac** [comment]
Please follow these steps:

1. Uninstall TL 1.8.1
2. Make sure C:\Program Files\Twitch Leecher does NOT exist
3. Copy TwitchLeecher_1.8.2.exe to Desktop
4. Run cmd.exe (Windows console)
5. Type `C:\Users\[YourUsernameHere]\Desktop\TwitchLeecher_1.8.2.exe -l log.txt` and hit Enter
6. The installer comes up. Step through the wizard and try to install normally.
7. When the installer crashes or errors out, there will be 2 logfiles on your desktop
8. Post both logfiles here

**Comment by EnergyDrink16000** [comment]
Hello!
I did the same, but the log files did not materialize on my Desktop... :( But I did found a new "log.txt" in here: C:\Users\[YourUsernameHere] and it does say something about installing TwitchLeecher. I hope it helps.
[log.txt](https://github.com/Franiac/TwitchLeecher/files/5824938/log.txt)

**Comment by Franiac** [comment]
The problem is that the Windows Install System cannot pause the automatic Windows Update service.

`[29A4:229C][2021-01-16T20:37:01]w308: Automatic updates could not be paused due to error: 0x80070422. Continuing...`

If you google the error code `0x80070422` there are multiple potential reasons. The most obvious one would be that you manually deactivated the Windows Update Service. Other than that this error has nothing to do with the TL installer. It's Windows' own installing system that fails because of the configuration of your machine. I can't give you more hints. You can try solving the issue by googling the error code and see what solutions there are. It's nothing that I can change by fixing a bug in the TL installer or something like that.

**Comment by EnergyDrink16000** [comment]
I see...
It's weird because I'm using TwitchLeecher since forever (I guess my first was 1.3 or maybe even older, I don't remember exactly) and this never happened before, nor with any other program. Especially that Windows Update is running just fine right now as I'm writing this... I want to cry like now.
