### ISSUE TITLE
Download Error 404

### ISSUE THREAD

**Issue by eva35** [Franiac/TwitchLeecher#556]
I know this fixed and 1.8.2 had been released but I am a 1.7.3 user like most people to download sub-only vods. Is there any change to change this version's API? I know you do not want to continue with the cracked program but please... 

(Or if anyone else knows how to download sub-only vods please answer.)

**Comment by Franiac** [comment]
That won't happen. 1.7.3 suffers from other issues that have been resolved over time and honestly I am surprised that it somehow works again because 1.7.3 was dead for a very long time in the past. The only way for a software is forward. I need to catch up to the ever changing system that is called Twitch.tv and it's nothing that I decide personally. Twitch changes their API's constantly and so I have to "keep up" constantly.

As a little mood boost: I have information that I can **POTENTIALLY** make sub-only downloads working again. But don't ask for an estimate...
