### ISSUE TITLE
VirusTotal shows 1 false assertion

### ISSUE THREAD

**Issue by Nexen23** [Franiac/TwitchLeecher#56]
Guess, scanning [results](https://virustotal.com/ru/file/4961161fa65e94fe1228b8aea89545f6de3a1b00d41a326e2a618c25af56478c/analysis/) might be investigated to prevent assertion. I don't have knowledge to do this by myself though.

**Comment by Franiac** [comment]
I cannot tell you why "Jiangmin" throws a false positive here. I mean... we are on GitHub here and everybody can see the source code of the program and even build an installer himself, so it is very difficult to implement a virus or a trojan even if I wanted to. I cannot do anything about this result because I have nothing to change on my end. You cannot fix a false positive because the anti virus software is the one not working correctly, not my program.

After a little research about "Jiangmin" I found out that this anti virus software seems to be pretty bad. Jiangmin is a chinese company and the software is often rated 1/5. And isn't "chinese anti virus software" a contradiction in itself :P
