### ISSUE TITLE
Installing to hidden folders won't work.

### ISSUE THREAD

**Issue by omfganimal** [Franiac/TwitchLeecher#564]
Windows 10 64 bit. Latest Windows update.
Minor issue and there's a workaround for it. Would be cool if it was fixed since I was wondering what was going on for thirty minutes, but I doubt any other people will even have this specific issue.
Just went to use the app since 1.8 and it wanted me to update. I have it on my external drive and I have my programs folder hidden on the drive. I went to update and it just said error while updating. It's not on my SSDs, C and D drives, and might've not known how to crawl for hidden folder installations. 
Workaround: I had to uninstall (uninstalled with iObitUninstaller since I couldn't even uninstall normally) and choose a folder not hidden to install to, then dragged the newly-installed application into the hidden folder and it works again.

**Comment by Franiac** [comment]
There are so many things wrong with your post:

> but I doubt any other people will even have this specific issue

Exactly, because noone should ever do what you are doing 😄 

> I have it on my external drive

Installing programs on external drives is a very very bad idea. Installers write registry values and remember the path a program is installed to. If you detach the drive or give it another drive letter, everything falls apart. This works with so called portable programs, but Twitch Leecher is not one of them.

> I have my programs folder hidden on the drive

There are no hidden folders. "Hidden folders" just have a "." infront of the name that tells Windows to "hide" it in the Explorer for example. It's just a marker but it does not actually hide anything. If someone wants to see it, they can.

> uninstalled with iObitUninstaller since I couldn't even uninstall normally

Yes, because you moved the installation folder manually to a different folder, what do you expect?? The uninstall routine cannot find the files to uninstall anymore.

With all dear respect, you should read about program installations on Windows and how they work, what they are for and how an installation is tied to its installation folder. Stop installing non-portable programs on external drives (why would you do that anyway???).

So, there is nothing to "fix" here. You are definitely using Windows programs the wrong way, I'm afraid.

**Comment by omfganimal** [comment]
All right, well sorry for completely wasting your time. Just trying to improve your product.

**Comment by Franiac** [comment]
All good, but didn't you also have massive problems with other software you installed on that external drive? It is not that TL has a "special" installer or something, so I suppose other software would have the same problems in your context.

**Comment by omfganimal** [comment]
I was aware of a pathing issue due to removing my external drive as icons on my start menu would turn into blank page icons, along with other obvious things like seeding torrents from a non-existing drive, then plugging it back in and it still not seeding until I restart my PC (even though the program I used got fixed to where all you have to do is restart the program to register the drive). I actually don't put many programs on my external drive and the ones that _are_ on it are even more rarely touched, so I guess I wouldn't really think much of it, but put TL on my external because that's where I keep all my TL downloads. I don't exactly want dozens of gigs worth of vods on my main drives and I already don't use TL that often since I don't get on Twitch much. I don't feel like testing it, but I'm going to assume restarting my PC while having my external drive plugged in would register it, as that has solved other issues relating to stuff like this, like torrents.
