### ISSUE TITLE
Vods over 24 hours fail to show correct time. Processing fails. End proccess required.

### ISSUE THREAD

**Issue by deathdragon1987** [Franiac/TwitchLeecher#57]
Vods over 24 hours show length starting at 1.xx (maybe meaning 1 day?). The video downloads, however processing never completes. Processing only fails on Vods where the streamer is still live and adding to the vod.

url for vod: https://www.twitch.tv/dansgaming/v/93062533

![tlbug](https://cloud.githubusercontent.com/assets/6306835/19160293/3f12727c-8be7-11e6-96d5-0c7c2ae7d3d7.png)

**Comment by Franiac** [comment]
How can it be that Twitch stores a VOD where the streamer is still live? Normally the COD pops up on the streamers video section, when he is done streaming. In your case I think DansGaming went offline, maybe to start another playlist. So the "live" part has probably nothing to do with the issue unless I missed some new features of Twitch where viewers can already view a VOD while it is not completely processed by Twitch.

And in general I do not know what is the exact purpose of downloading a 38 hour VOD. The processing probably fails because of the size/length (maybe a ffmpeg issue). Why not cropping shorter parts? Like downloading 0-2hrs, then 2-4 and so on? Way more managable on the disk or to share or process with a video software.

As for the issue itself, I cannot do anything without the download log. do you have it? i am not an oracle that can guess what the problem is and be always right, you know :P

**Comment by deathdragon1987** [comment]
Vods aren't published at the end of streams in one go. The Vods are updated every 15 minutes (ish) reflecting an updated time (where a vod would be at 30 minutes it would then show 45 minutes etc). Twitch is processing 15 minute chunks and adding them to the vod untill the streamer stops the stream.

I'm not trying to download the entire vod but a 2 hour part, it still fails the processing ( even if you download a minute of it it still fails to process. (The vod length is now 40 hours now as it's updating.)

This is as far as Twitch Leecher gets

![tlbug1](https://cloud.githubusercontent.com/assets/6306835/19163887/b052fda4-8bf5-11e6-8606-982556cc1a69.png)

Here is the log:

[log.txt](https://github.com/Franiac/TwitchLeecher/files/514462/log.txt)

**Comment by Franiac** [comment]
Weird... I can see the DansGameing VOD getting longer, but no other streamer has this! Every streamer in my follow list who's streaming right now does not have a part of the VOD available and neither do i. i only get my latest stream as a VOD when i am finished. Is this some specialty for the really big streamers?

Well, the log tells me ffmpeg is playing asshole again... i hate this tool, really. such a bad black box. i have to debug and view the console output...

**Comment by deathdragon1987** [comment]
It must be a perk to streamers with 'x' amount of subs I guess. A streamer I follow that currently has 400 viewers has it. Another with 150 viewers doesn't.

I wouldn't worry too much about it as this only seems to happen in the rare circumstance where a VOD is over 24 hours and still being updated. I've used TL for months and never run into any problems, I love it.

**Comment by Franiac** [comment]
WOHOOO, OMG!!! I discovered a major fuckup in the playlist parsing method that is responsible for exactly this problem and it also solves a bunch of other issues i received via the contact mail...

how could this be undiscovered that long? software development is amazing sometimes :D

basically what happens is the following:

whenever the stream quality or settings changes there is a line in the VOD playlist called "#EXT-X-DISCONTINUITY"... due to a parsing bug, this tag gets appended to the end of every playlist that i generate in TL. but only in case the tag really exists in the playlist. VODs that do not change settings do not have this tag in the playlist.

now this tag is responsible for making ffmpeg stop encoding. so every stream containing the tag probably  cannot be downloaded correctly... the encoding stops whenever the tag shows up (can be in the middle of the stream for example).

some people wrote that they wanted to download an entire VOD but it stops after the first half. this is exactly what we are talking about here.

Conclusion: It is time for a new version of TL!

**Comment by deathdragon1987** [comment]
Well I love the enthusiasm! Hopefully it wont be too hard to fix. Good luck!

**Comment by Franiac** [comment]
🎉
