### ISSUE TITLE
Request: do not delete temp data on error

### ISSUE THREAD

**Issue by ConnorKrammer** [Franiac/TwitchLeecher#585]
TwitchLeecher appears to delete the successfully downloaded portions of a stream when it encounters an error. This is bad for two reasons:

1. It forces users to download from scratch, using up extra bandwidth.
2. It can cause permanent data loss.

The latter has happened to me several times. If you download a stream and are nearly finished but Twitch mutes a portion of the audio, then it will fail to download and the entire stream is lost. Likewise if you are downloading a stream but the uploader deletes it during the download. I suspect the same would happen as well if downloading a stream that, during download, went past the archive duration and was removed from Twitch (though this depends in part on how long it stays up on the cloudfront CDN after it's removed from Twitch's frontend and if there are any interposing APIs that TwitchLeecher depends on and would error out due to).

I assume the same thing happens as well if internet connectivity is temporarily lost mid-download.

This doesn't need to be particularly fancy; just give users the *chance* to try to recover from errors manually, and if they're not recoverable, salvage at least partial data.

**Comment by Franiac** [comment]
TL does not support resuming downloads. The very simple download manager can't do this. I have already implemented a new one capable of pause/resume/reconnect and such but it is not compatible with the .NET technology runiing TL. So if TL cannot resume downloads, there is not reason why it would not delete the corrupted ones.

Regarding permanent data loss:

> The latter has happened to me several times. If you download a stream and are nearly finished but Twitch mutes a portion of the audio, then it will fail to download and the entire stream is lost

It is not TL's business to deal with muted audio this way. If Twitch changes the currently downloading stream, even the download playlist can change (which needs a restart of the entire download anyway). TL or any other software cannot react in a error-prone way to this. Furthermore, if you got a stream with muted audio, this means there is copyright protected/unlicensed music in there. That should not be since it is illegal. The way to deal with this is not using copyright protected music. I am a musician and I will not implement anything to work around muted streams.

> I suspect the same would happen as well if downloading a stream that, during download, went past the archive duration and was removed from Twitch

Yes, if Twitch delets a video, you cannot download it anymore. You cannot download a file that's not on the internet 😄 

> I assume the same thing happens as well if internet connectivity is temporarily lost mid-download.

If the internet connection or the connection to the server drops out, there are multiple retries with a good amount of wainting time in between the retries. So this is more error-prone than the other cases. Sure, if there is no internet connection for a longer period of time, TL aborts with an error. This can be improved by implementing pause/resume for the download manager but again, that's not going to happen in the current version of TL anymore. There will be something new in the future (cannot tell you anything more about it, currently).

**Comment by ConnorKrammer** [comment]
To be clear, I don't think TwitchLeecher should attempt to circumvent copyright measures, download removed content, or magically recover from unreasonable changes that occur while it is operating. (I imagine you *do* get lots of requests along those lines, so I won't be too offended if that's how you were interpreting what I said. But to be clear: that's not what I'm asking for.)

But I do get frustrated when I start a download on my relatively slow, very low bandwidth-cap internet plan, and 2 gigabytes into a download an act of god causes TwitchLeecher to throw an error. At that point I would really rather attempt manual triage, and I'm not grateful to TwitchLeecher for saving me the disk space that I don't need right now, and certainly need less than the bandwidth and time wasted.

The simplest form of address is very simple indeed: TwitchLeecher just needs to hold on to temp files, for errored downloads only, until it is closed or the download is retried successfully. The only time this would be a problem is if the user:
- keeps TwitchLeecher open indefinitely, and
- encounters many download errors, and
- never retries failed downloads, and
- is very short on disk space.

You'd know more than me about TwitchLeecher's users, but I would guess that's a very rare intersection.

**Comment by Franiac** [comment]
> The simplest form of address is very simple indeed: TwitchLeecher just needs to hold on to temp files, for errored downloads only, until it is closed or the download is retried successfully

Like I said, it's not simple. You can't just error out, keep the files and go on with them later. You need a sophisticated mechanism that checks the attributes of each downloaded file separately before proceeding with the missing parts.

Let's say a video has 10000 files and after 9000 downloaded TL errors out, you cannot just go like "well, download the remaining 1000 and there you go". In the meantime the playlist could have changed, and therefor the filesizes, chucksizes or other file attributes of the already downloaded parts. You need to check each of the previously downloaded files if it is still relevant/up 2 date and if it even downloaded entirely and not only a part of it. That is a massive thing to do and not trivial.

In the end it does not matter anyway because I cannot implement all this effectively into the current (quite shitty) download manager. It's not that I don't want it, it is because I cannot implement it. It makes no sense to implement an error recovery-system into the current download manager, that's all.

This is the reason why I am working on a next version of TL that has all of this on board, but that's a long way to go.
