### ISSUE TITLE
Feature Request: Download Full Twitch chapter as part

### ISSUE THREAD

**Issue by TizianTitus** [Franiac/TwitchLeecher#590]
Hey,

if a streamer is changing his/her game/categorie on twitch, the vod will be seperated in chapter.
Would be aweseome if that chapter will be shown at the download options to only download that part of the vod that game i needed. 

![Screenshot_4](https://user-images.githubusercontent.com/25871509/112731534-37151080-8f38-11eb-85d0-cf4fdc168ce5.png)

Thanks again! 
-Titus

**Comment by jgottula** [comment]
I'm a long-time user of TwitchLeecher, and I'm going to basically agree here.

The ability to break up videos by "chapter marker" (i.e. when the streamer changes the game and/or title) is one of the few things that has always bothered me as a sort of glaring omission.

Because if I download a 6-hour VOD where the streamer plays three different games, I end up with a 6-hour video file that only has the game and stream title from the first game, and that makes it difficult to identify what other games (if any!) were played in that stream by any means other than manually scrubbing through the entire video.

So yeah, assuming it's not a tremendous amount of work, I think it would be neat if there was, say, a checkbox in the UI to enable splitting the output video into separate files: one for each "segment" of the VOD, if you will, with the filename formatting placeholders adjusted according to the game and title for each segment.

Personally I'm less interested in necessarily filtering to just one segment as the OP here described. But, similar core idea, I guess.

**Comment by Franiac** [comment]
I don't know if the Tiwtch API provides that info, but the feature would be nice.

**Comment by jgottula** [comment]
Assuming [this discussion](https://twitch.uservoice.com/forums/310213-developers/suggestions/38155990-return-tags-and-game-id-in-get-videos-in-helix) isn't outdated, it does indeed sound like Twitch simply hasn't bothered to make this... rather relevant... information available via their API. And doesn't give a shit about developers wanting it either, because reasons.

It's frankly kind of mind-boggling. Apparently on prior API versions you could basically accomplish this functionality via an "undocumented"/"unsupported" feature; but then Twitch helpfully decided to just remove that feature in their newer API, since clearly nobody would ever want it. It's not as if they've literally had employees responding to devs who were saying "hey where did the ability to do that go? undocumented?! well why not just, like, make it a feature?" 🙄

Their own VOD listing pages have the game-category-change "chapter markers" prominently listed and available for easy use, and have for a long time. And the VOD playback UI too. But, god forbid they ever make that precious secret information API-accessible...

(It's usually around this sort of time that I start angrily and unapologetically using dirty scraping methods on a website rather than their actual API, because their API is a useless pile of garbage lorded over by employees whose job description seems to be "stamp NOTABUG/WONTFIX on everything".)

**Comment by TizianTitus** [comment]
i just saw this, i think somehow its working but i dont know :D 

![Screenshot_4](https://user-images.githubusercontent.com/25871509/112770200-d532d480-9025-11eb-8fca-04f49af56ca6.png)

**Comment by Franiac** [comment]
The API does not provide the chapter info. Twitch is using their own GQL API for this purpose which is not public.

@TizianTitus Sure you can get the game of the stream, but it will always be the first game that you started the stream with. So that bot is only viable when you don't change games in a running stream.

Twitch and their APIs are terrible. It seems to me that they either  don't understand what they are doing or they just don't give a shit about their users. I have the feeling that they don't want too much API usage because they are sraced of other people writing better software than theirs. I don't know. Try receiving the quality options for a video via Helix API, LOL, another thing that raises the question wtf they are doing. In V5 it's all there and in Helix it's gone. Guess why TL is using V5 still....

I am closing this, since there is no hope that Twitch will ever provide a good API.

**Comment by jgottula** [comment]
> The API does not provide the chapter info. Twitch is using their own GQL API for this purpose which is not public.

Wow, you're totally right. I can see the `"VideoPreviewCard__VideoMoments"` requests and responses via `POST https://gql.twitch.tv/gql` right in the browser dev tools. Has all the information you'd ever want: the position and duration of the segment in milliseconds; the type (`GAME_CHANGE`); the game ID and corresponding details... it even nicely tells me the typenames of all these things (`VideoMomentConnection`, `VideoMomentEdge`, `VideoMoment`, `GameChangeMomentDetails`, etc etc etc).

(Oh yeah, and I just violated the main Twitch ToS and the developer Twitch ToS by opening my browser dev tools and willfully exposing my eyes to that chunk of sacred, highly proprietary JSON being sent and received by a web page that they served to me. 🙄)

Apparently they've been using this GraphQL API since like 2017 for the actual operations by the website itself. Must be pretty spiffy for them.

But fuck third-party developers. _"Here, have this shitty subset API instead that's missing huge chunks of functionality! Also, if you use the real API that can actually do things, we'll ban you! 🙂"_

This whole Twitter thread (from literally 2018) is pretty telling, in terms of how people feel about Twitch's wimpy-ass API efforts.
https://twitter.com/CBenni_O/status/1058151552857374720

Also I swear, this "BarryCarlyon" guy on the Twitch Dev Forums pops up over and over again... His job description must be something like _"main dude in charge of telling people to go fuck themselves when they ask about anything remotely API-related"_. The number of man-hours he's spent telling third-party devs to fuck off would probably be more than enough to just write a competent API.
https://discuss.dev.twitch.tv/t/is-it-legal-to-use-https-gql-twitch-tv-gql-endpoint/21811/5

> Twitch and their APIs are terrible. It seems to me that they either don't understand what they are doing or they just don't give a shit about their users. [...]
> 
> I am closing this, since there is no hope that Twitch will ever provide a good API.

Up until now, I'd never looked into the details of Twitch's various APIs. But now I have a real appreciation for the steaming pile of shit you have to deal with just to do basic things. And I must say, I am truly so sorry you have to deal with such a clusterfuck; I can only imagine the mental anguish and permanent psychological trauma that you've undoubtedly endured in creating this program.

Maybe one day, Twitch will get sued on the basis that the mere existence of their jumbled mess of API garbage represents an intentional infliction of emotional distress on all third party developers, just by virtue of existing. One can hope...
