### ISSUE TITLE
Framerates Options to Solve Converting Errors

### ISSUE THREAD

**Issue by vincent-accion** [Franiac/TwitchLeecher#591]
Hello,
I have had an error when I wanted to download a stream in 60fps as it was the only framerate available in the resolution I wanted. An error occurred during the converting process.
However, after a few tries, I tried with 30fps in a lower resolution and no error occurred.
After reading the threads on github about twicthleecher, I read a response by the developer that said that if there is a drop in frames during the stream, the error in converting using Fmpeg is not fixable since it doesn't depend on the software but on twitch.

Wouldn't it be possible to propose more framerate options at every resolutions to counter-balance the issue ?

It worked for me and maybe it could improve the usability.

**Comment by Franiac** [comment]
TL gets resolutions and framerates from Twitch. You have to understand that TL does not re-encode downloaded videos. The original container for a Twitch video is a .ts file. If you choose the option to convert the .ts file into an mp4 file, TL copies the video and audio streams into the mp4 container 1:1. This is extremely fast since it is only a container change. There is no processing to the video itself.

If you want to change a 1080p@60fps stram to a 1080p@30fps stream for example, you would need to re-encode the entire video stream. Depending on the length of the video and the pc you're on this can take hours and hours of intense processing. I don't want TL to be a video encoding/muxing tool. There are better tools out there like Handbrake or Avidemux. So TL will always work with what Twitch provides.

The fact that sometimes ffmpeg errors out of dropped frames and such is not great, but it is not TL's job to fix anything like this. What you surely can do is disable the mp4 conversion and download the original .ts file. Then you could run this through Handbrake and choose the target format and container you want with the downside of immense waiting time due to re-encoding.

So no, I won't introduce more resolution/framerate options than Twitch provides. In future TL versions the mp4 container copy option will probably disappear completely because then TL works entirely without ffmpeg. Nearly all GitHub issues regarding errors of downloaded streams is due to ffmpeg failing to copy the source stream for whatever reason. I want TL to be a clean downloading tool. If you download a Twitch video, you'll get the original .ts file. After that it's the users choice of what he wants to do with it. Most video softwares can handle .ts files out of the box, so mp4 is not necessary at all anyways.
