### ISSUE TITLE
TwitchLeecher sound slippage

### ISSUE THREAD

**Issue by Floraytings** [Franiac/TwitchLeecher#596]
I noticed a sound slippage when I downloaded the broadcast I wanted to watch on the Twitch Leecher app. Please help me fix your problem

**Comment by Franiac** [comment]
Since you successfully ignored the entire issue template, here it is again:

READ THIS FIRST!!!

Help me beeing efficient, please! I am developing Twitch Leecher in my free time for no money. Contribute to the project by posting complete, structured and helpful issues which I can reproduce quickly without asking for missing information.

When creating a new issue please make sure you follow the below checklist:

- Take a look at the latest closed issues. Maybe yours has already been solved.
- If you have a problem with a download, provide the download log created by Twitch Leecher
- Provide the version of Twitch Leecher you are using
- Provide information about the video (Url, Channel, ID)
- Provide information about your operating system (e.g. Windows 10 64 Bit)
- Try to describe the problem as detailed as possible, I cannot read your mind
- Windows Insider Builds are NOT supported!

About Audio/Video Desync Issues:

Make sure to check for desync issues with VLC Media Player. A lot of video tools have immense trouble playing back downloaded Twitch streams correctly. Especially the following products introduce A/V desync:

- Windows Media Player
- Adobe Premiere (no joke, Adobe just does not care)

So if you are about to post a desync issue and you are using one of the above programs, please check the video in VLC first!
