### ISSUE TITLE
Inability to download over 26 hours of video.

### ISSUE THREAD

**Issue by Rigel88** [Franiac/TwitchLeecher#61]
When trying to download 30+ hour long videos, the resulting video after processing is only the first 26 hours chunk. Tested on different VODs.

**Comment by Franiac** [comment]
Whenever posting a new issue, please provide as much information as possible. VOD url, download log and so on...

**Comment by Rigel88** [comment]
https://www.twitch.tv/etozhemad/v/62781003
https://www.twitch.tv/etozhemad/v/62781210
Unfortunately I no longer have the logs, but I've looked at them and don't remember any errors in there.

**Comment by Franiac** [comment]
I tried to run ffmpeg in th the windows console and after about 26 hours and 30 minutes, it throws weird DTS and timestamp errors. so probably a bugin the source material.
but what you can do is downloading the fist 26 hours part and then the rest in a second run just by cropping. if ffmpeg throws errors like this on the source material, I cannot do anything about it basically because it has nothing to do with Twitch Leecher.
