### ISSUE TITLE
Ignore "access denied" on sporadic chunks

### ISSUE THREAD

**Issue by monolied** [Franiac/TwitchLeecher#615]
Twitch Leecher 1.8.4
https://www.twitch.tv/videos/1052270103

The above video has issues, once at about minute 16:00 (might be fixed, couldn't reproduce), once at about h 6:33:00. Some of the Chunks get an "access denied", and the Twitch player doesn't handle that well, either. So this is, essentially, not Twitch Leecher's problem.

Here are example URLS:

https://d2vjef5jvl6bfs.cloudfront.net/500039acf6d8d9fa4c64_rainbow6de_51101121667_1058232355/chunked/2080-unmuted.ts
https://d2vjef5jvl6bfs.cloudfront.net/500039acf6d8d9fa4c64_rainbow6de_51101121667_1058232355/chunked/2083-unmuted.ts

However, it would be nice if Twitch Leecher would handle situations like that more gracefully, with a "best effort". The same does apply for situations, where network issues break the download. It would help me if there was an option so Twitch Leecher would download what ever it gets, "keep broken". With network issues, it could keep and convert what it has up untiul this point; with an issue like the one above, it could download the parts where access isn't denied. It could store the chunks with Timestamps if it wanted to be helpful or just glue everything; all would be better than nothing.

(The way it is, I download the playlist, locate the issues, try to cut around these, which works, but is cumbersome. With network issues, I meanwhile download parts only. It's just too painful to lose an 8h download. Twitch Leecher does a fantastic job; it could do it even better in these scenarios I believe.)

Regards and thanks, nemo

**Comment by Franiac** [comment]
> It would help me if there was an option so Twitch Leecher would download what ever it gets

That is your point of view, but I already see the new issues "TL messes up my downloads, missing parts and jumping videos". That's not better than before if you do have a download at the end but half of it skips around and makes no sense. It would be ok if these chunks failed once or twice in a 6hr VOD, but there are VOD's missing 30%. That's not a fix.

I feel the pain but I olny really see 2 solutions for this mess:

1. Twitch stops implementing absolute garbage software and stops messing up their stupid access rights and playlists (probably won't be happening anytime soon)
2. Streamers should get their shit together already and stop streaming copyright protected music, resulting in muted parts on VOD's

I (as a musician) am in favor of the second solution, because what's going on on Twitch is awful. Everybody thinks they can do whatever they want with music. And if they get DMCA'd they cry like little babies. I am more and more annoyed by issues resulting from illegal usage of music.

Do not take it personal, I see it is annoying for TL users as well, but the source of the problem is not my software.

**Comment by monolied** [comment]
I'd think a prompt like "Encountered a problem with the download, do you want me to keep the working parts?" would mitigate the users complaining, but you certainly know better what users are capable of when it comes to complaining. ;)
I didn't even know this was the issue here. The "unmuted" probably gave it away... should offer "muted"... whatever. (I'm a musician myself. That's why I buy my records preferrably on gigs.) I'll work around the issue. Thanks for your time.

**Comment by Franiac** [comment]
> but you certainly know better what users are capable of when it comes to complaining

You become hesitant of changes on GitHub with an viral open source software, not gonna lie...

"unmuted"... "muted"... you can even see how weird Twitch is right there. What does this "unmuted" even mean? Usually it's a muted chunk... but not always... ... ... ... WHAT?

Sometimes I am trying really hard to understand even the dumbest stuff, but Twitch is a whole new level.
