### ISSUE TITLE
UI Glitch when hover with Mouse over it

### ISSUE THREAD

**Issue by missiah** [Franiac/TwitchLeecher#633]
Hello,

Apparently the UI glitches complete out when move the mouse over it, it makes it very hard but not impossiblem to use TwitchLeecher.

https://i.imgur.com/xlphVGm.gif

**Comment by JohnGrivez** [comment]
Same here

**Comment by Franiac** [comment]
**Here's the issue template again that you ignored:**

READ THIS FIRST!!!

Help me beeing efficient, please! I am developing Twitch Leecher in my free time for no money. Contribute to the project by posting complete, structured and helpful issues which I can reproduce quickly without asking for missing information.

When creating a new issue please make sure you follow the below checklist:

- Take a look at the latest closed issues. Maybe yours has already been solved.
- If you have a problem with a download, provide the download log created by Twitch Leecher
- Provide the version of Twitch Leecher you are using
- Provide information about the video (Url, Channel, ID)
- Provide information about your operating system (e.g. Windows 10 64 Bit)
- Try to describe the problem as detailed as possible, I cannot read your mind
- Windows Insider Builds are NOT supported!

About Audio/Video Desync Issues:

Make sure to check for desync issues with VLC Media Player. A lot of video tools have immense trouble playing back downloaded Twitch streams correctly. Especially the following products introduce A/V desync:

- Windows Media Player
- Adobe Premiere (no joke, Adobe just does not care)

So if you are about to post a desync issue and you are using one of the above programs, please check the video in VLC first!

**Comment by missiah** [comment]
**I'm sorry, I didn't mean to ignore anything**

Take a look at the latest closed issues. Maybe yours has already been solved.
**When my Kids asleep i will go trough the 578 closed issues**
If you have a problem with a download, provide the download log created by Twitch Leecher
**Not part of the problem**
Provide the version of Twitch Leecher you are using
**1.8.4 probably it was visible in the GIF**
Provide information about the video (Url, Channel, ID)
**Not part of the problem**
Provide information about your operating system (e.g. Windows 10 64 Bit)
**Windows 10 Pro 64 Bit**
Try to describe the problem as detailed as possible, I cannot read your mind
**Apparently the UI glitches complete out when move the mouse over it, it makes it very hard but not impossiblem to use TwitchLeecher.
https://i.imgur.com/xlphVGm.gif**
Windows Insider Builds are NOT supported!
**Not using it**


Sincerely

Missiah

**Comment by Franiac** [comment]
This is obviously a render error. Even the text and icon after the start are completely cut off. It would be interesting to know what kind of graphics card, driver version, resolution, display refresh rate and so on you are using. Perhaps Freesync/G-Sync?
The thing is, I am using plain WPF and I do not do anything special regarding rendering or something, so I suppose it must be some issue on your machine with that exact setup since I cannot reproduce any of this on my 4 different pc's.

Did you update anything and it stopped working or has TL never ever worked on your pc?

**Comment by missiah** [comment]
Here is your desired information

Graphics Card

- NVIDIA GeForce GTX 1080

Driver Version

- 471.68

Resolution

- Full HD 1080p

Display Refresh Rate

- 60Hz

Freesync/G-Sync

- None

I do not use Twitch Leecher on a regular bases but I am pretty sure some versions ago the problem did not exist for me.
A few months ago I upgraded my system (new CPU / RAM / motherboard and freshly installed Windows 10).

I didn't notice this problem anywhere else, programs and games run without issues. Only Twitch Leecher has this strange behavior, even during installation and uninstallation (see here https://i.imgur.com/2ntZBI6.gif).

**Comment by Franiac** [comment]
The fact that even the installer has the problem is an indicator that your system has a problem with .NET applications in general. The Installer of TL has nothing to do with the actual program but also uses a WPF GUI. That's why other installers work because the use a native GUI.

I don't know what the hell ASUS is doing there but my edjucated guess is that they have some little "wE EnHAnCe yOUr gaMInG eXPeRiEnCE" thing going on that does more harm than good.

Thanks for letting me know.
