### ISSUE TITLE
Don't delete .ts files option

### ISSUE THREAD

**Issue by bissquitt** [Franiac/TwitchLeecher#654]
I've had issues, but rather than open an issue here I would rather just solve it myself. 
All the .ts files are downloaded correctly and there is an error on merging. 
It would be extremely helpful and simple to just add a check mark to not delete them so that I can manually merge them myself.

Thanks for your time

**Comment by Franiac** [comment]
Instead of fixing issues yourself you might point out what the issues were so I could maybe fix them in a future TL update so not only you but everyone else also benefits from it.

Do think about all the average Joes out there who don't even know what a .ts file is (and they should not need to know).

TL will not provide such an option because 99.9% of the users don't know what it means. They just want a video... and that should just work. If it doesn't, we should work on how to make it work again and not provide weird workarounds only IT professionals and rocket engineers can use.

**Comment by bissquitt** [comment]
It's not an issue with TL its an issue with Twitch. If you download a stream that is live, and it ends, or the chunks get moved on the server (such as when twitch processes and mutes VODs), if it hits one of those files that it can't access for whatever reason, it just instantly fails and deletes everything you DID download. You could have all but a single 10sec chunk from a 5hr VOD, but it instantly deletes it and has to redownload it ALL when you click retry.

Simply changing the "clear temp folder" action to when the VOD is removed from the download list would allow retry actions to not waste everyones bandwidth because you only need to download the missing parts. If you have it set to auto clear the download when done, this then effectively changes nothing. It just makes zero sense to delete everything.
