### ISSUE TITLE
[Request] Download sizes

### ISSUE THREAD

**Issue by scottismyname** [Franiac/TwitchLeecher#655]
I know this wouldn't be completely accurate, but it might be really cool to get an estimate of total file sizes for each respective quality.

This could be done by downloading either a fixed file size, or maybe a percentage of the total file, or maybe even another way, and do this for each quality profile (or a subset of qualities selected by the user).  The user could then choose which version they want based on file size.

**Comment by Franiac** [comment]
The size info is part of the playlist. The playlist then again depends on the quality. In order to get the playlist, one needs an auth token and a lot of other stuff. That'S too much just for displaying the size. What would be possible is showing the total size while downloading. Because when a download is actually started, the playlist gets downloaded and could be interpreted. That's part of #46 though anyway
