### ISSUE TITLE
Fake TwitchLeecher site!

### ISSUE THREAD

**Issue by HeyMika** [Franiac/TwitchLeecher#665]
Yeah, I know this is no issue to the software directly, but I think this is important to address.

There is a fake TwitchLeecher site that claims to be the official download site!

Here: https://tleecher.com/

There is absolutely no link to the GitHub page and further contact whatsoever.
The download redirects to a mediafile upload with a "twitchleecher.zip" download that is with 200% certainty malware.

I also searched the domain up on WhoIs: https://www.whois.com/whois/tleecher.com

We need to take this down asap, as probably a lot of people will think that this is the official download site for TwitchLeecher.

**Comment by Franiac** [comment]
Wow, this is some real bullshit. I'll write an e-mail to sav.com and hope they take it down. They have an explicit abuse e-mail address. Thx for the heads up.

**Comment by Franiac** [comment]
I have sent an e-mail... let's hope it has any effect.

**Comment by HeyMika** [comment]
Okay, let's hope they do something about it.

**Comment by Franiac** [comment]
I also made a post on Reddit warning about the site. Some asshat maoderator thought it was a good idea to remove the post because he got mad about me posting the actual website name, which is the most important part in my opinion.

So... post deleted for posting malware while trying to protect people from malware... Reddit seems like a nice place to be...

**Comment by HeyMika** [comment]
Wow really? Reddit really can be an asshole sometimes.

**Comment by Franiac** [comment]
Obviously Sav.com does not care about their abuse e-mail address. I replied to the automated support request in order to push it one more time and this is what I got:

> NOTE: THIS EMAIL WILL NOT BE RESPONDED TO. PLEASE VISIT.....

They don't give a shit about questions of non-customers. So I declare this issue resolved. There's nothing more I can do.

**Comment by daylamtayari** [comment]
Just came across that website and wanted to offer a couple other routes you could take:
- UDRP proceeding: Will cost $750-$1000 depending on which provider you use but will allow you to obtain the `tleecher.com` domain. UDRP proceedings are in short copyright domain take overs, if you have a copyright (registered AND unregistered) that is confusingly similar and it is being used in bad faith (super easy to do) , you can have the domain either cancelled or transferred to your ownership.
- Cloudflare abuse report: It uses Cloudflare for its name servers so you can file an abuse and copyright (I'd do both if I was you) report to Cloudflare which will force him to change name servers but will have it down for a bit.
- Contact SAV: I see you tried their abuse email but I do see they have a abuse form that is locked behind having an account which you could try AND they do have a copyright dispute process which is another avenue you could pursue.

Best of luck getting it shut down!

**Comment by daylamtayari** [comment]
Also I looked into the website and at best it is farming ad revenue.  
The download link points to a fake MediaFire clone which doesn't actually point to any file, when you click download it just sends you to one of those 'Install this ad to go to your download' which doesnt ever do anything.

**Comment by Franiac** [comment]
@daylamtayari Thx for the heads up! UDRP is not an option. I do not let others make me spend money if you know what I mean...
Cloudflare is a good point, could try that (and will). It is kinda shitty SAV only responds to customer accounts. I'll see what I can do.

**Comment by daylamtayari** [comment]
@Franiac no problem, I totally understand, just wanted to present every option I could think of.  
I hope Cloudflare will do their job and remove it and also want to mention, if Cloudflare decides to take some action and removes his account, I'd monitor the DNS records often because if whoever runs it isn't careful and is more interested in getting the site back up, you could view their full DNS records and see where they are being hosted. Because if they are being hosted by a cloud provider, you could also contact them asking for them to shut that user down/ban them.  
And definitely agree its very shitty by SAV but you could try sending emails to their legal contact points though that will be taking some of your time.  
Hopefully it works out!
