### ISSUE TITLE
Questions about Twitch Leecher 2.0

### ISSUE THREAD

**Issue by MPeti1** [Franiac/TwitchLeecher#673]
According to the changelog a lot of features got removed because it is not available in the new API.

The web twitch client and others like the Android can app still show these, no?
If so, would it be an option to try using the hidden APIs used by those clients to obtain these things?

I think hidden APIs were also used previously, which were found by examining the web client.

**Comment by Franiac** [comment]
You need to see it from a different point of view:

The game API is there in Helix. But the game ID is not part of the video response anymore. So in order to get the game, one would need to do a request to get the stream the video originated from, extract the game ID and make another request to get the actual game info. This would cause 2 additional requests for each video in the search result view. Now lets assume, you have 100 videos in the search result array, you would need 200 requests for the game info (and another 100 for the thumbnails). This is not acceptable.

As for the FPS: Twitch also does not show the FPS for source quality

**Comment by Franiac** [comment]
Btw. the same goes for the video resolution in the search result view. The resolutions get parsed from the playlist summary. We cannot do this for every video in the result array.

The only thing I see coming back soon ist the {game} wildcard for the filename template. This only would be needed in the download dialog and there we could make some additional requests in order to get the game info. But I spent enough time of my vacation for Twitch Leecher for now 😄

**Comment by MPeti1** [comment]
I see, no problem.

How much do you want to stay with the Helix API? I mean, in case someone else would implement the support for it in TL.
AFAIK the GraphQL API can give you much more information, even in one request, by specifying what do you want. The web twitch client uses this. It is an unofficial API, but yt-dlp uses it too (it transitioned to that from Kraken, instead of Helix), and it seems to be stable enough.
In the browser devtools requests like this can be identified by being sent to `https://gql.twitch.tv/gql`.

**Comment by cpenick28** [comment]
So the new twitchleecher cannot download the live broadcast? You need to wait to end the broadcast before you can download the video?

**Comment by Franiac** [comment]
Let me try to get all the information about the API's compressed in a single post for future reference 😄 

### There are 2 types of access tokens:

1. The "Bearer" token generated by the Helix authentication endpoint
2. THe "OAuth" token generated by the website login form

### There are 2 ways how to get metadata (videos, games, streams, clips, users and so on):

1. The Helix API
2. The "public" GQL API

### There is only one way to get video playlist access tokens (in order to download anything):

The "private" GQL endpoint that generates the access token.

### Now we need to put it all together

1. Helix needs Bearer tokens
2. "public" GQL doesn't need a token
3. "private" GQL needs Bearer OR OAuth tokens for non-sub-only videos
4. "private" GQL needs OAuth tokens for sub-only videos

So here's the catch: You cannot get video access tokens from the "private" GQL with Bearer tokens. You need to have an OAuth token. That's the reason why TL has to login again for sub-only video download. The initial login generated the Bearer token, the sub-only login generates the OAuth token.

### Now what you can do (and what many other tools like youtube-dl do) is:

1. Use the "public" GQL for metadata and totally scrap Helix
2. Use the "private" GQL with OAuth for video download (sob-only or not).

### This looks promising at first but I have my reasons why I opted out:

1. You're playing cat & mouse with Twitch. Every day something can change
2. Helix is stable, you know what you get, everything is documented

### Now here comes the whacky part:

You can actually download videos without a token at all by using a hacky GQL endpoint giving you the live preview url of a video. That's used for the "stepping through the video" when you hover your mouse over it. So far I think you cannot choose the quality, though.

### But another thing is the following:

Even if I can download all sub-only videos without a token, I don't want to. From a legal standpoint Twitch Leecher is in an (accepted) grey area. Twitch does not request to take down applications like this. Downloading sub-only videos from channels you are not subscribed to is 100% illegal. There's a reason why there is a paywall infront of it. And as a streamer I would be pissed if anyone can just download my stuff, even if I said "NO". I honestly think, Twitch should fix this loophole in their GQL API. Just because you need the live preview feature on your website, does not mean opening up the door for everyone. I don't even know if Twitch is aware of it.

### Conclusion:

I use Helix because it is convenient and stable. I don't want to make Twitch Leecher releases every 3 days because something changes. I have a life. I use the "private" GQL part for sub-only downloads with OAuth and for non-sub-only videos with Bearer tokens.

So even if someone would contribute the GQL stuff, I wouldn't really want it. Other than that (no offense)... The contributions usually are bad. I think I rarely merged anything more complex than a typo. I don't know why that is, but on GitHub the average contribution quality is atrocious. Hate me for that comment or not, but I am 3 times faster if I do it by myself in most cases. Implementing it right from the beginning is more efficient than cleaning up the dirt. There are exceptions for sure, so I don't want to sound egoistic or "better than the rest". But that's my experience so far.

**Comment by Franiac** [comment]
@cpenick28 Nope, downloading live streams never worked. Let's say a streamer is 1hr into the stream and you start the download with TL 1.8.4, you get the playlist up to that point. So yes... in theory you could say "it kinda worked", but actually no, because you would not get the rest of the stream. In addition to that, playlist changes happen during the stream all the time that can mess up your download entirely. So no, you did not lose any functionality in TL 2.0 regarding that. TL just stops you from using a feature that doesn't work right anyway.

**Comment by qinoux** [comment]
> @cpenick28 Nope, downloading live streams never worked. Let's say a streamer is 1hr into the stream and you start the download with TL 1.8.4, you get the playlist up to that point. So yes... in theory you could say "it kinda worked", but actually no, because you would not get the rest of the stream. In addition to that, playlist changes happen during the stream all the time that can mess up your download entirely. So no, you did not lose any functionality in TL 2.0 regarding that. TL just stops you from using a feature that doesn't work right anyway.

I'm also sad to see this feature discontinued. I’m not sure if the primary reason was to prevent users from mistakenly downloading incomplete VODs, or the technical problems you mentioned. If it’s the technical issues, then I understand that it was unfortunately necessary. But if it’s the former, then I’d like to offer some perspective on how I use Twitch Leecher and why those incomplete VODs were actually not a problem for me.

For context: I use Twitch Leecher primarily to crop parts of streams that I find particularly interesting. I rarely download whole VODs.

So with that in mind, I’m not asking for and I never expected the download of a currently ongoing broadcast to be able to “catch up” to the rest of the stream as it’s downloading. I understand that if I start the download while the stream is at 2 hours, I will only be able to download those first 2 hours. That is fine. I only ever want to download what has already been broadcasted at the time of me starting the download.

There are two cases in which it would be very useful, if not crucial, to download broadcasts that are still currently being streamed.

1. Many of the streamers I watch stream for 10+ hours. If I’m watching the beginning of their stream and there’s a part I’d like to download, it is very inconvenient if I have to wait 9 more hours for them to end their stream to be able to download that part.
2. Some streamers are notorious for deleting their VODs after they end the stream. If there’s a part I want to save before it is inevitably lost forever, I’d like to be able to quickly do that before they stop streaming and delete the VOD.

**Comment by Franiac** [comment]
@quinoux As I stated before, the playlist of the stream is not consistent until it is finished. That's a hard fact. So it happens that you start downloading the stream. The playlist gets downloaded and all the parts are extracted and sheduled for download. Now the playlist could change and Twitch can suddenly delete parts of the playlist or substitute them with others that have a different filename. The original playlist ist outdated and fails on certain parts rendering the video unusable. What I will definitely not start doing is checking every 5s if something changed and fiddle it together again somehow, because there is no definitive way where you can be sure you did it correctly.

So yes, the technical part is an issue. I see that for some people it may have worked, but for many others not. And as a software developer I don't keep half-functioning "features". It's like Windows 11 in a way 😄 ... the taskbar works 50% of the time how you need it, but 50% it won't... what does MS do? Keep it that way and 50% of their users are unhappy. I don't want to be Microsoft.

As for the "streamers delete their stuff": See my maybe somewhat emotional but legit answer [HERE](https://github.com/Franiac/TwitchLeecher/issues/676#issuecomment-1024514727)

**Comment by Franiac** [comment]
@quinoux And in addition to my last comment: If it worked like you said and only the first part of the stream gets downloaded, I would not have removed the "feature". It does not work for 100% of the userbase, so it gets removed.

**Comment by BubiBalboa** [comment]
The live broadcast download feature worked fine.  Maybe it could go wrong or technically wasn't perfect but it worked well enough that multiple people ask you to please keep it. 

The reasons you linked I don't find very convincing to be honest. 

In the previous versions the feature worked like this: The second a streamer deletes a VOD it is gone and TL aborts the download. This is a good solution to prevent self-doxx or embarrassing situations to be preserved against the streamer's wishes.  Which is what we want, yes? 

And the part about "Illegal Streams"? Having Spotify run in the background of a stream is such a big issue for you? Truly?

Please reconsider removing this feature.

**Comment by quinoux** [comment]
@Franiac Personally, I hadn't noticed any issues with it so you'll probably understand my disappointment. Comparing Twitch Leecher to Microsoft doesn't seem quite fair because I'm well aware that this is a passion project run by one dedicated developer whereas Microsoft is a billion dollar company that should be held to much higher standards. I don't expect Twitch Leecher to be perfect and I'd rather have a feature than only works sometimes than not having it at all.

As for morality, that is not a can of worms I want to open. At the end of the day, this is your software product and you're free to apply whatever moral code you believe in.

Nonetheless, thank you for explaining your decisions and continuing to improve this software.

**Comment by Franiac** [comment]
### Technical Issues

There are technical issues, that's a fact. What you guys don't have is perspective on the matter. You see 4 or 5 people complaining that the feature is gone despite working correctly. There are only 2 or something comments from way back having issues with the feature (precisely complaining about not receiving the rest of the live stream). Here's what you guys don't see: >30 mails in my inbox also complaining about the "feature" not working correctly aka failing downloads (the first being from 2016). You have to understand that GitHub is by far not the main source of issue data. Only a fraction of the users actually create an account in order to create an issue. It is way easier for most of the users to just click the "Help" button in TL and shoot an e-mail my way. This is issue 673, my inbox counts > 8500 e-mails from 2015 onwards. So if you like it or not, the truth is, 4 or 5 people complaining that the feature is gone is the minority.

> I don't expect Twitch Leecher to be perfect....

But I do. Why should I not persue a 100% functional software because I am not a multi-billion corporation? It is not ok to have half functioning features in my software. Am am already annoyed that I don't have enough time to fix the flawed download manager, rebuild a proper GUI and use fresh C# coding styles like async/await. But at least the available features work properly. I am a professional software developer and I don't like to be unprofessional just because it is a side project.

### The Law

Twitch mutes their videos after the stream because unlike YouTube they don't pay millions of dollars for copyright contracts. Twich fails hard at this. Remember the DMCA incident? Rightfully so, because they were called out for illegal actions. Playing copyright protected music on Twitch is illegal, period. There is no "everybody does it, so it's ok". That is the greatest nonsense I hear people say. The law states it is illegal. Everyone starts beating up their gilrfriend... that's ok then, too, right? No, it's called domestic violence, you can go to jail for it. Here on Twitch it's called copyright infringement... it's also illegal, you can go to jail for it. So it's not about how accepted some action may be, it's about if it violates the law or not.

The problem I have now is that in the country I am from one actually can get sued for providing the tools capable of downloading illegal streams aka unmuted live strams with copyright protected music in them. And guess what, I don't want to get sued. So if you don't like the law, complain about the law, not me removing an illegal feature.

### The Morality

I like to open up that box because it seems like morality is something that got lost on the way to the internet and the comments of some of you really annoy me in that regard.

If the streamer does not want you to have any of his content for download, he should be able to enforce this. People use content of streamers without permission nowadays as if it's normal. Kinda like the copyright protected music thing. Nobody actually cares, and that's wrong. You can download a stream with TL, watch is locally, download your own stream, do something with it. That's what TL was developed for. It was never developed towards ripping content of streamers you don't have permission for and upload your copyright infringed version to your YouTube channel collecting the clicks.

Another thing is privacy. Streamer forgets to shut down his stream and gets undressed on camera. He definitely should be able to shut down and delete everything before some asshole with Twitch Leecher "catches" him live, makes a clip and uploads it to YouTube and thereby shaming the streamer forever.

> And the part about "Illegal Streams"? Having Spotify run in the background of a stream is such a big issue for you? Truly? Game publishers pay good money to be featured by streamers. I personally have found multiple artists I like through Twitch. And it's not like having your song played to 1000 people watching "steals" 1000 plays from you.

This mindset is not ok!

### Conclusion

I understand the disappointment of you guys. I am with you on that. But I presented solid facts and some morality issues that made me remove the "feature" anyways. I am not trolling you, I have searious issues with TL beeing able to download live streams as stated above. "But it worked for me and I need it so bad" is not a valid argument against that. If Twitch fixes their technical stuff (which they won't, because they suck at developing an API) and if the law changes for the better, we can re-visit this "feature".

**Comment by martint12snv** [comment]
@Franiac first issue is that streamer can delete record
second isssue is that twich deleting audio track and the end of the stream, hence is better download live stream

**Comment by Franiac** [comment]
@quinoux

> Nonetheless, thank you for explaining your decisions and continuing to improve this software.

Thanks a lot. I invested 1 week of my 2 week vacation to develop this update. A little appreciation is very nice to see 😄 

Releasing a massive update with hunderets of hours of work put into it and receiving only disappointment because of a little removed feature really pisses me off right now to be honest.

**Comment by Franiac** [comment]
@mwagnerEE you didn't fucking get what I wrote, did you?? Holy crap!

**Comment by martint12snv** [comment]
@Franiac sorry for me it's an important feature . thank you for your hard work

**Comment by BubiBalboa** [comment]
> Technical Issues

It would be easy enough to have a popup explain the limitations of this feature so users don't bother you with unnecessary bug reports. Or to hide it behind a setting like you did with the subscriber downloads. 

> The Law

You seem to misunderstand German law.  Your tool doesn't crack DRM so you're completely in the clear. If Twitch would have some sort of protection on the downloads and your software would circumvent this, that would be problematic. But they don't so you are fine.  If I'm missing something please let me know. I don't like breaking the law either. 

> Morality

Maybe the streamer decides to delete the VOD after an hour or a day. Should TL then delete the VOD from my hard drive? It's probably against the streamer's wishes for me to have the video. 

It's on the streamer first and foremost not to do something stupid or illegal on stream. And there are already many different other ways to record and download live broadcasts. You removing this feature does not protect the streamers from anything. The only thing it achieves is making your software more frustrating to use and less powerful. 

Regarding the music. You put your own music on Soundcloud and Youtube for free and without ads from what I can tell. So you obviously understand how visibility is important for artists even if they don't get paid every time.  A lot of artists give permission for streamers to play their music on stream. This is NOT a black or white issue.

**Comment by ar1ow** [comment]
The worst solution is to remove the ability to download live broadcasts that have not yet been completed. It is important for me to download the moment from the stream instantly, in version 1.8.4 this function worked perfectly.

**Comment by ar1ow** [comment]
Maybe someone can advise analogue programs where this function is still available?

**Comment by MPeti1** [comment]
Well, whatever anyone says, I think it is still better to have TL this way, compared to it becoming unusable in februrary. Seeing @Franiac 's arguments I can agree with him, and also I want to thank you for your continued support for this tool!

As you also said, downloading of live streams was a feature that didn't work well and was also misunderstood by a lot of people regarding how does it work. That kind of means it is an advanced feature, and it should at least be hidden (or removed, as it is now) to only be used by those who can understand it's flaws.
The feature is still available with advanced download tools, like yt-dlp, and I think it is also somewhat easier to extend/modify, so I don't think this is the end of the world in any perspective. And also, it has plugin support so it effortlessly can use features that cannot be held in the public repository.

**Comment by MPeti1** [comment]
Also I want to say sorry that this issue got to be used to shame you for the changes, I didn't intend it that way :/

**Comment by Franiac** [comment]
We are running cirles here... so this is my last response on the topic.

> It would be easy enough to have a popup explain the limitations of this feature so users don't bother you with unnecessary bug reports. Or to hide it behind a setting like you did with the subscriber downloads.

Which part of "I don't want flawed features in my software" was unclear? It does not work, so I don't want it in my software, it's that easy.

> You seem to misunderstand German law. Your tool doesn't crack DRM so you're completely in the clear. If Twitch would have some sort of protection on the downloads and your software would circumvent this, that would be problematic. But they don't so you are fine. If I'm missing something please let me know. I don't like breaking the law either.

Not really... Twitch breaks the law by allowing live streams to use copyright protected music and only mute it afterwards. They don't have licenses and I don't understand why they are still allowed to do it. If YouTube detects music in your live stream that does not fall under their license, they straight up shut your stream down, INSTANTLY. How do I know? Because I accidentally streamsed a song during a drum stream that was not ok. So again, I don't care who breaks the law, I don't want to support it in any way whatsoever.

> It's on the streamer first and foremost not to do something stupid or illegal on stream. And there are already many different other ways to record and download live broadcasts. You removing this feature does not protect the streamers from anything. The only thing it achieves is making your software more frustrating to use and less powerful.

Exactly, the streamers should stop this shit, too. And just because there are other developers giving a shit about any of this stuff does not mean I also don't give a shit. I am true to myself and very happy with it. This again is the basic "everyone does it, so you need to do it, too" kinda crap.

> The only thing it achieves is making your software more frustrating to use and less powerful.

Because I didn't rob a bank, I am still poor... well... that kinda sucks...

> Regarding the music. You put your own music on Soundcloud and Youtube for free and without ads from what I can tell. So you obviously understand how visibility is important for artists even if they don't get paid every time. A lot of artists give permission for streamers to play their music on stream. This is NOT a black or white issue.

Please don't try to bring up stuff into this dicussion you absolutely don't have a clue about. My music is fully monatized on YouTube. SoundCloud versions are 128kbit mp3's, so that's an unenjoyable experience and works as a teaser. I understand what you are saying but SoundCloud does absolutely nothing for me. Spotify, iTunes and all the sreaming portals pay me, YouTube pays me monthly. Basically 98% of all platforms I am on pay me so your argument is kinda invalidated. I can tell you very unfunny stories about how my music got stolen for band contests where the YouTube content ID helped me a lot.

> The worst solution is to remove the ability to download live broadcasts that have not yet been completed. It is important for me to download the moment from the stream instantly, in version 1.8.4 this function worked perfectly.

See? Another perfect example of how everyone just doesn't give a shit. Internet 2022... "I need it so bad..." what a great discussion... I think I am too old for this.

**Comment by quinoux** [comment]
> @quinoux
> 
> > Nonetheless, thank you for explaining your decisions and continuing to improve this software.
> 
> Thanks a lot. I invested 1 week of my 2 week vacation to develop this update. A little appreciation is very nice to see 😄
> 
> Releasing a massive update with hunderets of hours of work put into it and receiving only disappointment because of a little removed feature really pisses me off right now to be honest.

Completely understandable. The fact that I only focused on one negative aspect in my previous comments does not reflect how I feel about the software as a whole. There are plenty of reasons why I prefer Twitch Leecher over all the other download tools I’ve tried, and I appreciate your continued efforts. An “issue” board just didn’t feel like the right place to bring up things that aren’t an issue to me 😉

**Comment by Franiac** [comment]
@MPeti1 

> Also I want to say sorry that this issue got to be used to shame you for the changes, I didn't intend it that way :/

This one is definitely not on you, no worries 😄

**Comment by Franiac** [comment]
> > @quinoux
> > > Nonetheless, thank you for explaining your decisions and continuing to improve this software.
> > 
> > 
> > Thanks a lot. I invested 1 week of my 2 week vacation to develop this update. A little appreciation is very nice to see 😄
> > Releasing a massive update with hunderets of hours of work put into it and receiving only disappointment because of a little removed feature really pisses me off right now to be honest.
> 
> Completely understandable. The fact that I only focused on one negative aspect in my previous comments does not reflect how I feel about the software as a whole. There are plenty of reasons why I prefer Twitch Leecher over all the other download tools I’ve tried, and I appreciate your continued efforts. An “issue” board just didn’t feel like the right place to bring up things that aren’t an issue to me 😉

Well, it's nice of you that you do it now, thanks!

**Comment by ar1ow** [comment]
> See? Another perfect example of how everyone just doesn't give a shit. Internet 2022... "I need it so bad..." what a great discussion... I think I am too old for this.

Do you need explanations? Okay, I'll try. I use a translator, so sorry for the wrong words if there are any.

I used Twitch Leecher to download the last moment from the broadcast as quickly as possible. I repeat: as soon as possible! And he allowed it. 3-5 minute moments were always downloaded quickly and without delay, in 90% of cases there were no problems. Twitch Leecher made it possible to do this as quickly as possible, since you could specify the time and download the broadcast that had not yet ended, while there were no problems with sound, like other programs. In version 2.0, this is simply impossible for me, since you removed this feature, it turns out that Twitch Leecher is now useless for me.

I signed up on Git Hub to write about this, thought you could easily revert this feature back as it's really needed, but you totally refuse, even though this feature worked great!

The simplest solution would be to simply add a button to download the unfinished broadcast in the settings, for those who need it. But now I have to look for a new program in which this function is available and works in much the same way as in Twitch Leecher.

**Comment by Zurlon** [comment]
Thank you for updating TL! I have a question; in the changelog, under removed features, the removal of the view count in the download screen doesn't have the "not available in new API" explainer. Could I ask why this feature was removed? I often found it useful.

**Comment by Franiac** [comment]
@Zurlon Nope, it does not say "not available in the API" next to that point. My thought behind this is "why do we need the view count in the download department?". It made no sense to me because it is not a download related information, so I removed it. It is still available in the search result, where it should be. Can you explain why you need it in the download view? I have no reason to not add it in again, but I kinda miss the point why 😄 
I also hope we are talking about the same view... If you perform a search, the search result view has the view count still. it is missing in the view when you click "Downloads" in the header. Just to make sure we talk about the same thing.

**Comment by Franiac** [comment]
Oh, I misread your comment, sorry... RIIIIGHT it does not say "not available". That is correct, it is available in the API, and I removed it anyway.. also correct. Still my last comment applies. The view count is still there on the search result just not in the downlaod view.

**Comment by Zurlon** [comment]
My bad, even though I know the difference between the download screen and the search screen I still conflated them in my mind :/
Obviously this decision you've made makes complete sense; the info is not needed on the download screen. Again, thanks for updating!

**Comment by Franiac** [comment]
@Zurlon Aha, kinda second-guessed my decision there 😄 ... then we are all good, thanks!

**Comment by mwagnerEE** [comment]
> @mwagnerEE you didn't fucking get what I wrote, did you?? Holy crap!

Umm, no I didn't? What's up?

**Comment by minerva1993** [comment]
Hello,
Thanks for all your hard works and I sincerely agree with your points. And, in the mean time, I also understand other people saying "I need that feature". As a non-expert of these kind of program, I have a very naive question; is it difficult to provide portable version of TL 1.8? If possible, we don't need to argue on downloading live streams which seems just repeating their words...

**Comment by Franiac** [comment]
@minerva1993 TL 1.8.4 will stop working on Februray 18th when Twitch shuts down their V5 API. That's the whole point of releasing TL 2.0. So no, there will not be another version of TL 1.8.

**Comment by skyfox1977** [comment]
> Releasing a massive update with hunderets of hours of work put into it and receiving only disappointment because of a little removed feature really pisses me off right now to be honest.

Well, if you see it from the users part that uses that feature 95% of the time, as I have done, then you should also understand the  frustration we have, I love the other features and work you put in, but It doesnt matter when I cant do the thing I am using the software for. So I will have to stick with the older version. I STILL appreciate your work and the explanation on why the feature It is removed, But non the less,, the new version is almost totally useless for my use and I have to use the old version.

**Comment by minerva1993** [comment]
> > Releasing a massive update with hunderets of hours of work put into it and receiving only disappointment because of a little removed feature really pisses me off right now to be honest.
> 
> Well, if you see it from the users part that uses that feature 95% of the time, as I have done, then you should also understand the frustration we have, I love the other features and work you put in, but It doesnt matter when I cant do the thing I am using the software for. So I will have to stick with the older version. I STILL appreciate your work and the explanation on why the feature It is removed, But non the less,, the new version is almost totally useless for my use and I have to use the old version.

Please read the comment just above yours

**Comment by Franiac** [comment]
> > Releasing a massive update with hunderets of hours of work put into it and receiving only disappointment because of a little removed feature really pisses me off right now to be honest.
> 
> Well, if you see it from the users part that uses that feature 95% of the time, as I have done, then you should also understand the frustration we have, I love the other features and work you put in, but It doesnt matter when I cant do the thing I am using the software for. So I will have to stick with the older version. I STILL appreciate your work and the explanation on why the feature It is removed, But non the less,, the new version is almost totally useless for my use and I have to use the old version.

I totally understand the frustration, I am not an idiot (not saying you called me that...). But what bugs me is that nobody seems to understand my issues with the feature. I don't support illegal stuff... nobody cares because their beloved feature is gone... there a multiple technical issues... nobody cares about it because their beloved feature is gone... there are moral decisions... nobody cares because their beloved feature is gone. I said I understand your frustration but everyone else just seems to be hammering on my arguments trying to invalidate them without showing any empathy whatsoever. I do not discuss this again, I expect everyone to grow a pair and think what the words "illegal", "technical issues" and "moral" mean and maybe let it sink in for a second before posting the next "I need it so bad..." comment.

**Comment by Franiac** [comment]
> I STILL appreciate your work

Thank you!

**Comment by Franiac** [comment]
> the new version is almost totally useless for my use and I have to use the old version

I understand but then you need to find another tool from another developer with less empathy for streamers and legal stuff. TL 1.8.4 will stop working on February 18th, unfortunately.

**Comment by BubiBalboa** [comment]
I wasn't going to comment again but I can't help myself.  

There is **nothing** illegal about anything here. You are just wrong about that.  That's a fact. Please accept this. 

The technical issues aren't really issues either. As I said, put it behind a setting with an explanation of the limitations and you're fine. You do the same thing with the subscriber-only vods. I understand you don't want broken features in the software but it just worked fine. 

The morality is the only argument where you kind of have a point. Kind of. Because you punish all users and streamers who do the right thing just because a few streamers break DMCA. Most streamers today have the music on a different audio channel that doesn't get recorded by Twitch. So when you download the stream there's no "illegal" music anywhere.  A lot of streamers don't play copyrighted music at all anymore. Why shouldn't we be able to download their streams? 

And finally the example of the streamer who forgets to turn off stream and does something embarrassing is such and edge case that I don't see it as a valid argument either. People could simply record their screen with a phone if they really wanted to capture this moment. You want to do the right thing - that's admirable - but are not saving anybody here. 

And because you apparently need to hear this and I forgot to write this further up: Thanks for the software and the update. 

But please put the feature back in. 

/back to lurking

**Comment by Franiac** [comment]
> There is nothing illegal about anything here. You are just wrong about that. That's a fact. Please accept this.

[https://www.streamscheme.com/spotify-music-for-twitch/](https://www.streamscheme.com/spotify-music-for-twitch/)

> Can You Use Spotify Music On Twitch?
The broad answer to this question is no, you cannot use Spotify music on Twitch. Spotify music is only licensed for personal use and streaming it out to a community not only breaks the law, it breaks their terms and conditions. 

> There is a loophole, however, when it comes to royalty-free playlists (of which there are a few). It is still your responsibility to ensure that the music is truly royalty-free. You must also take a slight risk that the owner of the music may change their mind in the future. 

> The DMCA bots are becoming more intelligent and soon they will be able to find music while it is currently being played. Under Twitch’s new guidelines, you will be banned from the platform after three DMCA strikes.

> Just because you rent music or even purchase it on a program like iTunes, you don’t have the rights to play the music on your content. You would need to go through legal steps in order to secure those copyrights in order to legally use copyrighted songs on your stream. 

I throw 50 more of these from law firms, music labels and Twitch themselves at you if you want, so I ask you politely to stop spreading your misinformation and get your alternative facts somewhere else than Fox News!

> The technical issues aren't really issues either

That's and observation combined with your own opinion straight derived from the sentence "it works for me, so it works for everyone". It is invalidated by facts I presented and therefor a wrong statement.

> And because you apparently need to hear this and I forgot to write this further up: Thanks for the software and the update.

I read so much sarcasm in that sentence it makes me sick.

> But please put the feature back in.

No

> /back to lurking

Please stay there because you are very close to receive the legendary achievement "Pissed off Franiac so hard he banned me from his repository".

**Comment by BubiBalboa** [comment]
My dude, I'm talking about recording and downloading streams. You know, what your program is about. That's the same thing as recording music from the radio for personal use.  And this is completely legal. I'm not saying streaming Naruto on Twitch is legal. But funnily enough, recording someone streaming Naruto on Twitch is 100% legal as long as you don't upload it anywhere else. You understand? I think you do but you are too stubborn to admit this.

**Comment by Franiac** [comment]
Again misinformation. Spotify music is personally licensed by a monthly fee or be contributing in the software by listening to advertisements. Radio is "free for all". Somebody streaming unlicensed music does not grant you a personal license if you download it, period.
