### ISSUE TITLE
Visual C++ Runtime Merge Module breaks the installer

### ISSUE THREAD

**Issue by eXaltedDope** [Franiac/TwitchLeecher#674]

**Comment by eXaltedDope** [comment]
It says i have 15 processes that need to be closed first.  I cant close them fast enough before they automatically reopen.  Ive never had this issue before.  Typically Nvidia and adobe stuff with some JS as well

**Comment by Franiac** [comment]
TL 2.0 has 0 changes on the installer regarding open processes... so that is probably not something I can fix. What processes are those? 15 is a lot of stuff... that is very very weird.

**Comment by eXaltedDope** [comment]
Thanks for the quick response.  The actual error says "files in use" if that helps.  Most of the Adobe processes stayed closed.  These ones I cant close fast enough before they start up again.  

NVIDIA Container
NVIDIA ShadowPLay Helper
NVIDIA Share
Creative Cloud Helper
Node.js
Creative Cloud Helper (again for some reason)
voicemodplugin
NVIDIA LocalSystem Container

**Comment by DudeShift** [comment]
Have basically the same problem but with other files in use when trying to upgrade from 1.8.4:

AMD User Experience Program Master
Windows Explorer
ARMORY CRATE
LG HUB Agent
Firefox
Radeon Software (couple of different ones)
C++ Application Development Framework
Radeon Settings (couple of different ones)
EABackgroundService

Really don't think I should have to close CPU/GPU driver software, Firefox, or even Windows Explorer because those files are in use to install the newest TwitchLeecher. 

Please let me know if there are any thing I can provide to help with a fix.

**Comment by alex-wazovskiy** [comment]
During the upgrade Avast! Antivirus blocked the installer twice. In addition, the installer asked me to close CorelDraw and its child processes. I decided to reinstall Twitch Leecher with disabled antivirus, and this time the installer asked me to close almost all applications opened on the computer at that moment. After installation, I turned on the antivirus back and launched the already installed Twitch Leecher, the antivirus scanned it and allowed it to run. However, after clicking the "Connect" button, Twitch Leecher gave me a blank window and nothing happens. As I understand it, the Twitch authorization page should have appeared in the window, but it does not appear, the window is just empty.

I hope my report helps you.

**Comment by chechuasdf** [comment]
Have you tried disabling Adobe services on Task manager>Startup, then restarting the pc and then installing again?

**Comment by Franiac** [comment]
OK, sorry for that. I canceled TL 2.0 for now.

**Can you guys please all provide the Windows versions you are on?**

The issue seems to be the included Visual C++ Runtime merge module in the installer (I have no control over that module). It seems that this module causes all those file warnings since all processes you guys list above are indeed C++ runtime dependent applications. Since TL now needs an integrated web browser (CefSharp Chromium), it also needs the C++ runtime. I will integrate the runtime differently and release TL 2.0.1 shortly.

But remember: On WIndows 8.1 and lower you need to manually install the runtime separately as stated [HERE](https://github.com/Franiac/TwitchLeecher#download--requirements)

**Comment by eXaltedDope** [comment]
> OK, sorry for that. I canceled TL 2.0 for now.
> 
> **Can you guys please all provide the Windows versions you are on?**
> 
> The issue seems to be the included Visual C++ Runtime merge module in the installer (I have no control over that module). It seems that this module causes all those file warnings since all processes you guys list above are indeed C++ runtime dependent applications. Since TL now needs an integrated web browser (CefSharp Chromium), it also needs the C++ runtime. I will integrate the runtime differently and release TL 2.0.1 shortly.
> 
> But remember: On WIndows 8.1 and lower you need to manually install the runtime separately as stated [HERE](https://github.com/Franiac/TwitchLeecher#download--requirements)

Windows 11 Home 
Version 21H2

**Comment by Franiac** [comment]
Just a funny sidenote:

Microsoft states officially: "If your application needs the C++ Runtime, just include the merge module in you installer"

Microsoft also states officially: "C++ Runtime merge modules have so many problems that they should not be used in an installer"

Oh Microsoft you little idiot 😄

**Comment by Franiac** [comment]
I have uploaded a new installer for Twitch Leecher 2.0.1 [HERE](https://franiac.com/TwitchLeecher_2.0.1.exe)

Before I create an official release again I want to be sure it works properly.

Can you guys test the installer please and see if everything looks ok? Would be a great help!

**Comment by eXaltedDope** [comment]
Worked. Thanks brother!

**Comment by Franiac** [comment]
2.0.1 is out officially...
