### ISSUE TITLE
Downloading Sub only videos without sub

### ISSUE THREAD

**Issue by xalyy** [Franiac/TwitchLeecher#685]
Hey, can you add downloading Sub only videos without subbing?
This other program already does it, it can download Sub-only VODS without account or sub but its abandoned since a long time and it doesnt have a nice UI like yours. So I guess you could take a look at the code how he did it maybe?
Thanks.

https://github.com/TwitchRecover/TwitchRecover

**Comment by Norinoku** [comment]
(it's doesn't relate to your idea xalyy, but I just don't want to create a new topic for this thing, so this is addressed to Franiac)

Can you please bring back the download button if the video is currently streamed live? I just need to download some streams, which, unfortunately, are deleted by the streamer after they are ended. So I need to download them while they are still going live. I hope it's not related to the new API, so can you please return this feature? Thanks in advance if you will do!

**Comment by Franiac** [comment]
@xalyy How can you even think about something like this? Why do you think you should be able to watch or even download videos that others pay for and the content creator deliberately put behind a paywall? This is actually some criminal energy and straight up illegal. I know the private Twitch API can be "hacked" in order to download this stuff, but it does not make things more legal or smack paying/honest users less in the face. I strongly urge you to rethink your decisions and never post an issue about this again. Rightfully earned the "WTF" label...

**Comment by xalyy** [comment]
> @xalyy How can you even think about something like this? Why do you think you should be able to watch or even download videos that others pay for and the content creator deliberately put behind a paywall? This is actually some criminal energy and straight up illegal. I know the private Twitch API can be "hacked" in order to download this stuff, but it does not make things more legal or smack paying/honest users less in the face. I strongly urge you to rethink your decisions and never post an issue about this again. Rightfully earned the "WTF" label...

Yeah no thanks, not going to pay for twitch thots if I can get it for free.
Piracy FTW brother.

**Comment by Franiac** [comment]
And that's a ban...
