### ISSUE TITLE
Can't download vod from stream that is live

### ISSUE THREAD

**Issue by IKeroNI** [Franiac/TwitchLeecher#686]
Hello,
With new version 2.0.2 I can't download vods from stream that is still live. On earlier versions I had no problems with that.
Did something change?

**Comment by mdeutschmann** [comment]
Multiple people have reported this, including myself.  It only looks like you are first because the author considers this a "WONTFIX" and has been rapidly closing the bug reports   His line is that it is only an accident that this sometimes works in 1.x versions, and he won't put it back in unless he can make it work perfectly, which he doesn't see a way to do.

However, in my experience it works a *lot* better than "sometimes" in the old version.  I can't remember the last time a download failed on me that wasn't explained by a failure of my overall internet connection.

**Comment by Franiac** [comment]
Yes, part of it are the technical issues but not the main reason. Please read the pinned issue #687 now to get the full picture without distracting hate comments of the other discussions. I hope you will better understand my position then, thanks
