### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Taemal-D** [Franiac/TwitchLeecher#688]
I've tried to download a new VOD a couple times using the latest version of Twitch Leecher (2.0.2), but whenever I do I get permission denied as an error, I've checked you old issue brought up about this, but I've checked and the what was stopping them (Not having write permissions in the folder) and that I do have Write permissions for the folder.

https://www.twitch.tv/suiren_vt

I am using Windows 10

I don't have a log, but I'll try it again soon and if it fails post a log from there if it is the same issue

**Comment by Franiac** [comment]
This happens sometimes and I still don't know why. A long time ago I had implemented a permission check for the temporaty folder and the download folder. This did not work at all. So currently TL does not have any permission checks at all. That brings us to the bad news: I cannot do anything. I do not have code that I could change in order to work around permission issues because all file save operation TL does are calls to the integrated Microsoft .NET Framework. If that tells TL it has no permission, it usually does not lie.

> and that I do have Write permissions for the folder

You say that but as a developer I cannot trust you on that 😄 
How do you know TL runs with the same access permissions your logon user does? Meaning, just because you can create a folder in that folder in Explorer does not mean TL has write permissions when executed.
What would be insteresting,though: You could run TL as administrator and see if it works then. That would be a good check.

Another thing is that TL is an unsigned application. Sometimes anti virus software does not like such applications and denies them write permissions on the system. Do you have any of such installed (other than Windows Defender).

What I can say, too, is the fact that this permission thingy does not happeny often. So it is not a general problem but seems to be related to the users machine.

In addition to the above, please post the download log

**Comment by Taemal-D** [comment]
Just tried it again and its worked fine this time, so I don't have a error log to give... Thank your for your time though, guess it was just my laptop being annoying, if I do end up having the problem again I'll be sure to bring a log that time!
