### ISSUE TITLE
No Videos Found!

### ISSUE THREAD

**Issue by MikeDillon120** [Franiac/TwitchLeecher#691]
This only started happening today but I can't download any videos. It just gives me an error on any link (triple checked to make sure they're right) saying "No videos found!"

I need to figure out how to get these vods downloaded as it's my job to get videos edited for the client

**Comment by joparebr** [comment]
Also, the newest version does not work. It just open the link on chrome.

**Comment by yonut32** [comment]
Any other alternatives? my client need to have videos done by tomorrow

**Comment by Abalieno** [comment]
Kraken API v5 being removed.

Lots of Twitch extensions stopped working. Until everything isn't updated to the new API nothing will work.

**Comment by Franiac** [comment]
@Abalieno What are you talking about? TL 2.0.2 was released exactly for that. There are no V5 dependencies. And since TL 2.0.2 works perfectly I must assume that you are on an old version of TL.

[https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/](https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/)

> February 7, 2022 – 1-hour shutdown starting at 11:00am PDT
> February 9, 2022 – 2-hour shutdown starting at 11:00am PDT
> February 14, 2022 – 4-hour shutdown starting at 11:00am PDT
> February 16, 2022 – 6-hour shutdown starting at 11:00am PDT
> February 21, 2022 – 24-hour shutdown starting at 11:00am PDT
> February 28, 2022 – v5 permanent shutdown

This is what's going on right now 😄

**Comment by Abalieno** [comment]
My bad then, I haven't checked a new version. But I started seeing problems on other things and here too it was being reported for the same timeframe, so I thought it was related.

Good to now it's not affecting newer TL

**Comment by Franiac** [comment]
At least they are consequent and on time. I honestly did not expect that 😄
