### ISSUE TITLE
Option for rounding up instead of down with default quality

### ISSUE THREAD

**Issue by Liz-chan** [Franiac/TwitchLeecher#695]
Currently with the new default quality feature, if the quality isn't available it defaults to 'Audio Only'. This is a bit annoying since I have to change it every time to Source quality in order to download the stream correctly. I know that some people might prefer that, but it'd be good to have a choice, so I think an option to round up to 'Source' quality instead of rounding down to 'Audio Only' would be a nice thing to have, and would save me some time as well.

**Comment by Franiac** [comment]
A rounding is already in place. If the quality is not found, the next lower vertical resolution gets selected. If that's not available, the next higher vertical resolution gets selected. Could it be that the video you are trying to download was not transcoded and has only "Source" and "Audio Only"? Because that would make sense. If you select 480p as default, thats not there so it pre-selects 0px vertical resolution (Audio Only).

If this is the case we need an exception for videos with only Source and Audio Only and need to add Audio Only to the default dropdown even. Some users only download audio with TL.

**Comment by Liz-chan** [comment]
Yeah that's what I meant; on videos that only have 'Source' and 'Audio Only', it rounds down to 'AO', but there should be an option to round up to download the 'Source' quality by default instead of having to select it in the dropdown.

**Comment by Franiac** [comment]
@Liz-chan Can you please provide a link with your non-transcoded video? All my favourites have transcode and I need a video to test.

**Comment by Liz-chan** [comment]
Here you go @Franiac https://www.twitch.tv/videos/1287104388
