### ISSUE TITLE
Laggy Search/Temp Non-responsive

### ISSUE THREAD

**Issue by Xyrexus** [Franiac/TwitchLeecher#699]
I was using an older version until recently, 1.8.4 I think, upgraded to 2.0.2 this week, linked my twitch account and such, compared to the older version the channel search is laggy, it eventually comes up with the videos to select, but it is considerably slower than before, and immediately does that thing where the cursor turns to a blue loading circle and the program basically freezes until it finishes.

Updating to 2.0.3 didn't fix it. Also I uninstalled and did a clean install just to see if that was causing it, no dice.

I'm on Windows 10 64 bit, this happened with all the usual channels I grab from, (temmies ProtonJon Kazeugma)

This happens whether I'm searching by a date range or X amount of videos, it seems like this is when using the Channel search specifically, I just tried putting a single video URL into the URL tab and it didn't lag or freeze up.

**Comment by Franiac** [comment]
Yep, welcome to the new Twitch API, where "new" means "slow" and includes rate limits per application and user in order to "not overload the servers". You feel the result right there 😄 

Searching for dates is the most intense search you can make, it needs a lot of requests, especially if you search for old videos.

That's not on me, sry

**Comment by Xyrexus** [comment]
Ahh, damn, that's a shame, oh well, thanks for letting me know, I'm sure I can put up with it if it's not something that's fixable. ^_^ Cheers!
