### ISSUE TITLE
why is my anti virus stopping TL from converting

### ISSUE THREAD

**Issue by nocoel** [Franiac/TwitchLeecher#706]
hello,

so i haven't used the program for a few month now (i didn't have this issue before) and now with the latest version i noticed my antivirus has been denying permission to TL when the the converting phase happen and the download ends up in an error

i was able to make it work by making TL as an exception in my AV, but i have to say i'm a little paranoid about it, i don't like giving exception to softwares or anything cuz i don't have the knowledge to tell what they might be capable of doing behind the scenes

with that said i've been using TL since 3 years ago, and i trust it not to be malicious, i just want to have a clear idea about this

**Comment by Franiac** [comment]
With TL 2.x.x there are some changes that might be "suspicious" to AV software.

But first let me make one thing clear: TL is open source and a lot of eyes are on this source code. If I ever implemented something fishy, people would notice very very quickly and ring all alarm bells on the internet.

Here are 3 things that throw off AV software:

1. TL is not signed with a certificate. Such a certificate costs quite a lot of money and I simply do not want to spend hundereds of dollars of my own money a year for a tool which I do not earn anything with (except some very appreciated donations). Such a certificate tells Windows basically "look, this software was published by someone legit". Some AV tools do not like unsigned software and that is ok, because the AV tool cannot verify the authenticity of that program. Some AV tools let that just go, others warn you.

2. TL 2.x.x includes a Chromium browser. Yea, that's right, TL uses CefSharp in order to display the login form of Twitch. This in-app browser is the exact same Chromium engine that the actual Google Chrome browser uses (just the open source part). The Chromium engine makes calls directly to the C++ API of Windows. Now put it all together: An unsigned application uses an in-app browser that makes direct calls to the Windows system???? THAT'S SUS AF!!! That the tought process of your AV tool basically. And again... it's not wrong.

3. Twitch Leecher calls ffmpeg.exe in order to convert .ts files to mp4 (if enabled in the preferences). Again: An unsigned application opens a process of another open source application and tries to communicate with it??? SUS AF!!!

So here's the conclusion: As long as you download TL from this repository you can be 100% sure that you do not get any fishy software that sends your private data to Donald Trump or implements any kind of malware because people would notice and I would be an asshole (which I am not, I promise).
