### ISSUE TITLE
Constant Framerate/Not Having to use Handbrake

### ISSUE THREAD

**Issue by pandaBear7109** [Franiac/TwitchLeecher#72]
Hey man, so I'm an editor that edits for a couple of different streamers and while I love how easy to use TL is there's only one grip I have with it: I have to constantly handbrake every download because I get audio/video out of sync issues when I bring raw downloads in from TL. I use Premiere Pro CC and it's pretty heavily detailed how Premiere Pro can't handle variable frame rates. 
Every solution I search for on the internet is basically "just run it through handbrake" and while that's certainly helped me so far, it pretty much triples my edit time as I have to wait for the download (which is usually pretty fast) and then wait for handbrake to finish (which takes FOREVER).

So my question is, do you have a solution for this on TL's end? Is there a way to implement constant framerate so people like me don't have to use another program on top of what we already use?

Also, apologies if I put this on the wrong place. Kinda new to Github and the reddit post was closed from making new comments!

Thanks for making such great program!

**Comment by Franiac** [comment]
Nope, TL does not encode anything. it only merges the VOD parts. if i started to encode and convert to CBR, you would wait for hours after downloading because the whole VOD would get re-encoded (with possible quality loss). TL downloads and merges... that's it. if the streamers don't manage to get their shit together (don't get me wrong, but twitch clearly states that VBR is the wrong way to stream in every how-to available), I cannot help them or the unlucky people like you trying to work with the mess ;)
And what's up with Premiere support for this issue? I mean a professional video software that cannot handle VBR A/V sync? This sounds pretty unreal to me, but I am not a Adobe user. so I am sorry, but TL is the wrong place to fix this.

**Comment by pandaBear7109** [comment]
Damn that sucks, I'll probably look to just get the edit permissions from the streamers and download it that way, hopefully that way there won't be this VBR/CFR bullshit.

Dude, literally EVERY post about VBR and Premiere ask that exact question. It's so crazy that the most common answer to this particular problem on the Adobe forums is "run it through handbrake" instead of "maybe we should make our program that costs money to do some basic level shit that iMovie can handle".

Ah well, thanks for your help. TL is still the best option for me right now so I'll just have to put up with the encode times.

Thanks!

**Comment by pandaBear7109** [comment]
So I talked to the streamer and he said he was using CFR in OBS, so is there something I'm missing from TL or is it still in my editing program? Because if CFR is enabled shouldn't that keep everything constant for me to edit without A/V sync issues?
