### ISSUE TITLE
Conversion Error in Long Streams

### ISSUE THREAD

**Issue by nameless01234567** [Franiac/TwitchLeecher#721]
I don't have any logs and the videos I encountered this issue are deleted from Twitch, if it happens again I'll add a log and a video with the problem.
Twitch Leecher 2.0.3.
Multiple videos.
Windows 10 and 11 64 Bit.
Whenever I try to download a video over 40 hours (don't know the exact time but its over 19 hours that the problem begins) the video comes out corrupted, I could do it with older versions, but can't since the obligatory update. The problem is in the conversion because if I download without it, there are no issues, but I'm left with the .ts file.

**Comment by Franiac** [comment]
Downloading such long streams in one piece with mp4 conversion enabled is almost always a bad idea. Not because of TL, but FFMPEG. Long streams tend to have a huge probability of containing some hickups, frame drops and what not. FFMPEG does not like that. Without a log I cannot tell you whats going on, but I assume that it is nothing I could fix anyway.

Workarounds:

* Try downloading .ts files and transcode them manually by using Handbrake or something else
* Use the crop feature and download smaller parts of the video (not longer than 8 hours is a good start)
