### ISSUE TITLE
Livestream Clipping / Download - Idea for mods 

### ISSUE THREAD

**Issue by Dschogo** [Franiac/TwitchLeecher#735]
Hey I've just read #733 and got an idea which should be able through the Api (got a little knowledge myself by coding a bot).

So basically If you are a mod of the specific channel, let them download/clip whatever. A mod (should be/) is a trustful user and does basically all in the name of the streamer and/or is in direct contact. (Otherwise one wouldn't be a mod)

Shouldn't be that hard to implement, login is already build in for sub only vods now, and the endpoint is here ([Twitch docs](https://dev.twitch.tv/docs/api/reference#get-moderators)) . Login gives the Oauth and the scope is indirectly given due to the fact of being a mod.

Think that would be a pretty neat compromise for the "good" mods just wanna doing their work to support the streamer (cuz lets be honest, twitchts integrated tools are pretty limited, either download the whole vod afterwards or create a highlight then download that - just a mess, You've done a fantastic job filling that hole :D )

**Comment by Franiac** [comment]
Thank you for the first ever productive reply on the matter. But it is not about the moderators and that they are trusted members of a channel. It is about the streamers. If the stramer streams illegal crap, the moderators of that channel can be trusted employees or not... doesn't help making the stream less illegal, or do I miss something?

**Comment by Dschogo** [comment]
Well no, an illegal stream will ever stay illegal. In that regards it would only reduce the probability of "spreading" the DMCA content by large, because i think mods are kind of aware of DMCA/TOS so wouldn't spread. (At least that my point of view, where im mod, we deeply care about that and even avoid games which could potentially include copyrighted material)

So no it wouldn't eliminate the possibility of still capturing crap, just reducing it to a very minimal. Capturing stuff today is fairly easy (every idiot can basically do it, as seen in issues all by "normal guys" - non productive, absolutely not questioning why smt changed, nor reading Changelogs). That said, they will find their way to capture such with other tools like obs/ or inbuild screen cap of phones and even win nowadays. But none the less, i can understand that you probably dont wanna be the guy "providing" such tool to someone, or even being sued afterwards for it. 

I think TL is more or less only used by mods in bigger channels and not smaller ones/ such who dont really care about the stream. They probably dont bother with keeping clips/vods, but yeah would only narrow the problem to a minimum.

**Comment by Dschogo** [comment]
But on the other hand Twitchs detecting crap and muting feature is also far from perfect. And those remain in the Vods, so there is also that possibility, which is probably higher than smt from live only by mods. (Good thats not your fault cuz their system failed)

tl:dr there is no perfect solution for it, there will always be undetected shit out there. I think that slight increase by just letting mods and streamer clipping live is worth the feature.

**Comment by Franiac** [comment]
> we deeply care about that and even avoid games which could potentially include copyrighted material

You have all my respect, but that is not at all the majority.

>  That said, they will find their way to capture such with other tools like obs/ or inbuild screen cap of phones and even win nowadays

Absolutely, but not with my software then. Just because my neighbor robs a bank, I am still not doing it.

> I think TL is more or less only used by mods in bigger channels and not smaller ones/ such who dont really care about the stream

\>400000 downloads last year and the amount of hate I receive at the moment tell a different story

> But on the other hand Twitchs detecting crap and muting feature is also far from perfect

It's absolute bullshit, because they don't care, it's that simple. Twitch does not care. Nobody forces them to make drastic changes, so they won't do anything. That little DMCA strike thingy... LOL... does nothing obviously. If channels with 50k viewers can play copyright protected music as long and loud as they like without getting shut down, Twitch does not fucking care, period.

> there is no perfect solution for it, there will always be undetected shit out there

Correct, but that does not change my position.

Here's my totally honest opinion (not targeted at you, so we are clear on this one):

Twitch has become an irresponsible shit pit for irresponsible dipshits. Uhhhh, I like that last sentence, holy crap! Writing an opinion after a horrible day at work really puts things to the next level, heh. But really, I am so close to just quitting. I put a fuck ton of time (>100hrs) into TL 2.0 and the response is pure hate because dipshits cannot be dipshits anymore. People don't get, I am working for free it seems. Once I was doing this for fun. Now it feels more like a job working for a boss you cannot stand and who does not like you either. And the platform you're working on is also aging like milk in the sun. So if this bullshit debate goes on any longer I will make myself a very happy man with a couple of clicks here on GitHub. I can only win, everybody else loses. In addition to all that, there a multiple forks of this reopository that just removed the live detection feature again. Wow, thanks for nothing. I will never ever start another open source project.

**Comment by Dschogo** [comment]
> 400000 downloads last year

damn, never though at this scale, though more niche

> amount of hate I receive at the moment

> put a fuck ton of time (>100hrs) into TL 2.0 and the response is pure hate because dipshits cannot be dipshits anymore. People don't get, I am working for free it seems.

Thats often so sad to see ppl doing stuff in free time as an hobby and some random takes it for granted to offer 24/7 live support and every feature without understanding anything. I mean no one can except deeper knowledge about smt and is just the average user, but still no right to spam issues or being disrespectful more even trying to miss use stuff. 
They should be glad that stuff is opensource and can be freely used. Sadly i've seen such on more ghub issues / opensource discords for help.

> Correct, but that does not change my position.

> but not with my software then

Ight, makes totally sense, that ppl just fork and patch it back in shows good enough how "evil" ppl can be and dont respect a no / basically TOS.

Maybe somewhen in the future if stuff settles with "idiots" and the whole DMCA shit gets clearer on Twitchs end (if that ever happens), you can revisit my idea, if there is no better way then.

Keep up the good work mate 👍
