### ISSUE TITLE
Remember last download folder / change folder from text field

### ISSUE THREAD

**Issue by 1upCAD** [Franiac/TwitchLeecher#746]
When downloading multiple clips, it would be helpful if the software would remember the last chosen folder instead of needing to choose the destination folder every time.

It would also be nice to have the ability to change the folder via the text field provided. Pasting or typing should be available rather than just the limitation of the folder selection button.

Very useful tool and has helped me tremendously. Thank you for your hard work and time put into TwitchLeecher.

**Comment by Franiac** [comment]
Usually users do not select the folder every time because it is inefficient. Therefor there is the default download folder in the preferences along with the option to create subfolders for favourited channels. So maybe that already solves your issue?

For your second point... again, it is inefficient and therefor most users don't do it that way. If at some point multi-selection and downloading are a thing the whole download and quality selection will go away anyway and solely rely on the preferences.

I do not say you are wrong, absolutely not, but you are definitely not representing the average user in the way you are using TL obviously. Remembering the last chosen download folder of the session is not difficult to implement, I'll put it on the list. But also if you need to change the folder every time you donwload a video, you are making your life more difficult than it has to be, I think.

**Comment by Franiac** [comment]
It is a little bit late for me.... so I did not realize that saving the last used folder in the download dialog totally destroys the default download folder thing from the preferences.... so that's not going to happen.

**Comment by 1upCAD** [comment]
I think you misunderstood how I use the software, so I will try to explain again in more detail.

I don't download multiple videos from a single channel. I download one video at a time from different streamers for the purpose of creating my own content. I play games with fellow streamers whom have given me permission to use their videos. So I need to download each video from each streamer separately.

When I click "Search", I use the URLs tab, add the URL of the video and then click Search at the bottom.

When the video is found, I click download, decide "start" and "end", then I need to choose the folder I'm downloading to because I don't want to download to the default folder and then have to move the video to the folder I want.

After each downloaded video, you need to search again, which resets the folder back to default. This is very annoying.

I understand your comments, but suggesting that my use is "inefficient", is like saying Google Chrome is inefficient for remembering the last used folder to download multiple files.

If the ability to remember that last used folder is too complicated and conflicts with other features, then why not allow the ability to paste into the folder text box? Allowing the ability to replace the default folder path when needed instead of needing to click the button with the 3 dots? That I believe would be very helpful for any type of user.

It just seems like a very simple ask, which is super common in other download software.
