### ISSUE TITLE
[bug] oauth seems to be buggy if not properly saved

### ISSUE THREAD

**Issue by makedir** [Franiac/TwitchLeecher#749]
I think there is some bug in the app, if the oauth process didnt finish properly. There seems to be no or broken try and catch mechanism in the app for this or other cases too.

Following problem:

I updated twitch leecher becaue twitch new api / shutdown of old api and now you need an oauth for search. I let twitch leecher get an oauth token, but then it redirected me to a broken url, mostly because my firewall blocked the connection. Yet twitch leecher processed it as "done". I can search for a weird reason actually and get results, but the search takes unusual long, like 20 seconds, mostly a time out happens. Yet I get results. This is really weird. How does it work if the oauth didnt process successfully.

You should implement a mechanism for this to check if the oauth process was finished properly.

Also would be handy if you could add a button under settings, to get a new token / reset token.

**Comment by Franiac** [comment]
> I think there is some bug in the app, if the oauth process didnt finish properly. There seems to be no or broken try and catch mechanism in the app for this or other cases too.

I don't think so 😄 

> I let twitch leecher get an oauth token, but then it redirected me to a broken url, mostly because my firewall blocked the connection

Also don't think so 😄 

> Yet twitch leecher processed it as "done". I can search for a weird reason actually and get results

The OAuth workflow redirects to a specified url that is defined by me in the Twitch account for the application itself. This url is `http://www.tl.com` This url does not exist on the web but has the sole purpose of telling TL when the workflow is complete and an OAuth result has returned (success or failure).

So if your TL says it's done, it IS done. Without an auth token you cannot search anything. Since you obviously can and TL let you into the application and therefor completed the login process, the auth token has been received and properly validated by Twitch. TL does not only receive the token. Immediately after receiving it, TL then validates it against the API. Only if that process is successful, the token gets saved and TL let's you proceed to the main application and let's you do stuff (search and so on).

So the simple fact that you can search for videos is proof that the OAuth workflow was successfully completed. Now regarding you firewall and timeouts... That's not TL's problem. I cannot implement a proper internet connection for you, unfortunately. Fact is, a search can consist of multiple requests to the API. If some of them fail due to bad internet, still the successfull search results get presented.

I don't see any issue here other than your internet connection to be totally honest.

**Comment by Franiac** [comment]
> You should implement a mechanism for this to check if the oauth process was finished properly.

As I said, it's all there...

> Also would be handy if you could add a button under settings, to get a new token / reset token.

Just click the logout button in the header? 😄

**Comment by makedir** [comment]
Please dont answer in a typical "I am the dev "I know better" way. This is a bug report, for a reason. Do you think I reported this for no reason!??

I have 3 pcs I use twitchleecher with. On one PC, there was a firewall in use, which blocked the oauth process. I got a redirect error, YET YOUR SOFTWARE thought it was successful, and now twitch leecher is IN A BUGGY STATE.

I can produce this buggy state with 100% chance on this pc, doing a simple search, it takes 20 seconds loading, doing nothing, then showing search result.

On the other PCs it works normally, where the ouah was successfully.

**Comment by Franiac** [comment]
The only one sitting on the high horse is you. I explained to you in detail how the OAuth workflow in TL works but obviously you still know better. There is no such thing like a "buggy OAuth state". This is something you just made up, because you THINK you know how stuff works. But let me open your eyes a little bit more.

There is an auth token or there is none. If there is one it is either valid or invalid. If you can search, you have a valid auth token, period, no matter how often Twitch tells you the redirect failed or how hard you insist on a "buggy OAuth state". You HAVE a valid auth token, and if you think you don't have one, then you must be really stubborn and know the TL source code better than I do. And I doubt that.

The screenshot again points to an connection issue. This kind of behavior happens if the program does something (in this case retrieving search results FROM THE INTERNET) and it is blocked or slowed down by the OS (or connection). Windows catches that and shows the given dialog. And as you state, TL comes back after a while and presents the search results it got (because it took so long due to a slow connection). So TL acts exactly like I said it would, what a surprise... And do you know why? Because I implemented the freakin' program and know what it does in certain situations.

So spare me with your "expertise" and start providing valuable information (you did not even read the issue template) instead of making blatant assumptions about stuff you don't see through.

EVERYTHING you provided so far points to a slow/broke internet connection on this PC and you did not provide any other reasons or hints that tell differently. Basically nothing changed and your second comment only manifested my suspicion that this single PC has connection issues.

**Comment by makedir** [comment]
There IS NO CONNECTION PROBLEM ON MY SIDE OR ON THIS PC. I have 1gbit fiber connection. No packet loss, perfect connection. Twitch up. API up. No API issues. My connection is crystal clear and youre seriously coming up with this "it is my connection"!? Where everything works perfectly, except this one bug in your app?

Everything IS WORKING FINE ON THIS PC, NORMAL INTERNET. Working Twitch. EXCEPT OF THIS ONE PROBLEM AKA BUG IN YOUR APP and just since the oauth change.

After the freeze and long wait, the download of VODs works normally in TwitchLeecher with high speed up to 800mbit/s.

1. bad coding on your side, never let GUI freeze, this is the first issue here
2. bug, some broken state leads to freezing PLUS long wait time after unfreeze, TWO ISSUES HERE
3. this issue just started after new version with oauth, AND just on this one pc which had broken oauth routine

What kind of reasoning is that that I didnt provide "any useful information"? How should I do that if there is no way to get debug information.

Screencast:
https://we.tl/t-TMlOfW22zC

This is a bug in your app, period. It is just since the oauth change. It is just on one test PCs of mine, all over the same connection, just on the one, where I got a oauth error, but your app still went through with the process, regardless of Twitch gave an error back. 

Tell me if or how I get useful debug logs and I will provide them, if they show anything useful.

**Comment by Franiac** [comment]
Since all you do is ignoring what I have to say and downvoting every comment I write I don't feel like helping you anymore. Since you obviously know everything better.... you know where the source code is... have fun.
