### ISSUE TITLE
Ambiguous Errors When Full Hard Disk

### ISSUE THREAD

**Issue by dsnvwlmnt** [Franiac/TwitchLeecher#75]
I didn't notice that my HD filled up. I got an ambiguous error on several of the video downloads. Took me a while to figure out what was going on. The program doesn't handle a full hard disk with graceful clear error messages. Example: http://pastebin.com/8CGFiVQy

Would also be nice if there was a Retry button, instead of me painstakingly having to go through and write down which files i need to redownload.

**Comment by Franiac** [comment]
If your HDD gets filled up during video processing, I cannot provide a intuitive error messag because ffmpeg does not provide one. basically anytime ffmpeg fails, i do not know why, it just fails. If TL runs into filled up HDD while downloading it surely will provide you an exception in the log stating that the HDD is full because it is my code that fails, not ffmpeg.

I don't get the part about the rety button, though. If a download failed, there is a retry button to start over....

**Comment by dsnvwlmnt** [comment]
I checked for a retry button but maybe it was in an unintuitive location. There was Log and Delete for the small squares in top right. Or perhaps when it fails from an ffmpeg error there's no retry button (unlikely). I'll see next time.
