### ISSUE TITLE
request : making "search on start" option to simultaneously search on all listed favourite channels.

### ISSUE THREAD

**Issue by FBI4ever** [Franiac/TwitchLeecher#755]
hello . 
first of all, i appreciate your dedication toward making and improving TwitchLeecher. timezone sucks and most of my time i only watch vods of my favourite streamers.

quite obvious from the title. it would be great to save some clicks while searching for favourite streamer vods/highlight/clips.
currently it will only search for the streamer on the top list of favourite channels. 

thank you in advance

**Comment by Franiac** [comment]
Good point, but due to the burst rate restrictions of the new (and terrible) Twitch API, this could potentially cause trouble. The request count for the search (depending of the type) could make TL exceed the limit and then make it being stuck for 30s while the burst rate limit "refills". I don't think that would be such a great experience.
