### ISSUE TITLE
Converting to MP4 causes Variable Frame Rate

### ISSUE THREAD

**Issue by WaveSmashies** [Franiac/TwitchLeecher#780]
I noticed Twitch Leecher downloads vods as a .ts file before converting them to .mp4. For most people that works fine, but for some reason this conversion introduces Variable Frame Rate which is HELL on editing software. I downloaded a vod and copied the .ts before it was deleted, and it works perfectly in editing software like Premiere Pro, and it doesn't have Variable Frame Rate. Plus it saves a little time. I flipped through the settings and didn't see any option to leave it as a TS, so I'm submitting a request here.

I guess this is also a bug report. Converting to MP4 causes a Variable Frame Rate for some reason and that's a very bad thing.

Thank you for your time.

EDIT: I guess I'm fucking retarded because I noticed the setting shortly after opening this. God dammit. But the Variable Frame Rate issue still stands

**Comment by Franiac** [comment]
I am not going to comment on how "fucking retarted" you are 😄 but I am glad you found the checkbox...

TL copies the streams from the ts files 1:1 and only changes the file container. This means TL is unable to alter the stream and therefor cannot introduce VFR if it was not there. Probably the streamer uses VFR (and does not know better) or the ts file gets handled better by Premiere than the mp4. Either way, TL does not introduce VFR, it is not possible since it does not re-encode anything.
