### ISSUE TITLE
My launcher is missing after it crashed  

### ISSUE THREAD

**Issue by NickBenRawb** [Franiac/TwitchLeecher#781]

**Comment by NickBenRawb** [comment]
So I tried to launch the app and a moment later it crashes and I do not see the application in its folder anymore I tried to reinstall and it still did the same issue.

**Comment by Franiac** [comment]
So basically you want to tell me TL deletes itself when started? That is very very unlikely.

What is likely, though, is that your anti virus software thinks TL is a threat (because it is not signed with a certificate) and therefor puts it into quarantine. That has nothing to do with TL but with your anti virus software. Put the installation folder of TL in the exception list and see, if it works then. This is not a TL issue.
