### ISSUE TITLE
Cannot Sign In - version 2.0.7

### ISSUE THREAD

**Issue by kofsmg** [Franiac/TwitchLeecher#798]
- Version 2.0.7
- Windows 10 64 bit

I am unable to connect to twitch with either the 2.0.6 or 2.0.7 versions of TwitchLeecher. Every time I try to sign in I get this error:
![image](https://user-images.githubusercontent.com/57279804/191640737-a429221c-5b71-464b-a1ef-a0150a297459.png)

I know that the issue is **not** with my login credentials as I can sign in at the twitch website via my web browser just fine and have signed out and back in thee just to confirm that my credentials work.

**Comment by obleasty** [comment]
Having the same issue, with 2fa turned on or off.
    Version 2.0.7
    Windows 10 64 bit

**Comment by jrm24** [comment]
I have the same problem. I don't understand why in twitch web if it lets me log in and here not. Any solution?

**Comment by C0untZero** [comment]
Same here

**Comment by MustangDSG** [comment]
Same trouble. I'm tried on versions 2.0.7, 2.0.6 and 2.0.5 - problem exist. Tried with different accounts, some accounts with 2FA enabled, some not - all unable to logging in.

**Comment by the4kw** [comment]
same

**Comment by BeefEnBy** [comment]
Hey im also having the same problem the in program browser is unable to log in, but i can log in on my regular browser.

**Comment by akosirmpr** [comment]
Im having a same problem. Do you think guys it will be fix? or not?

**Comment by pascalgilles** [comment]
same for me with windows 11

**Comment by do-ree** [comment]
I'm having the exact same issues

**Comment by ZoviSapphire** [comment]
Same issues here. have confirmed I am using correct credentials.
It would also be nice if the login query would just be opened in your default browser instead of an internal one.
It would allow us to give access to the account without giving credentials if we are already logged in.
Maybe the Twitch API is considering this a "new" device and blocking the login attempts? Or does that only happen if you have 2FA on?

**Comment by cheese-steak** [comment]
I found a new project. [devhotteok/TwitchLink](https://github.com/devhotteok/TwitchLink) Try this.

**Comment by helpd69420** [comment]
I am having this same problem. PLEASE help this is crucial

**Comment by akosirmpr** [comment]
> I found a new project. [devhotteok/TwitchLink](https://github.com/devhotteok/TwitchLink) Try this.

is this safe?

**Comment by ZoviSapphire** [comment]
> is this safe?
I have tried it out and it works great! and why would that one be any un-safer than TwitchLeecher?

**Comment by cheese-steak** [comment]
> is this safe?

See this. #799

**Comment by andrhp87** [comment]
Samme issue for me, cannot log in

**Comment by Franiac** [comment]
Please refrain from starting tool comparisons in very specific issues. This issue is called `Cannot Sign In - version 2.0.7` and not `how to find a better tool than TL in 24 hours`. You don't go to a BMW workshop with a broken clutch in your BMW M2 and while the mechanic is working on your car you tell him how much better the Audio RS3 is. That's disrespectful.

Closing this for off-topic and we continue on #800 (and stick to the topic)

**Comment by helpd69420** [comment]
> I found a new project. [devhotteok/TwitchLink](https://github.com/devhotteok/TwitchLink) Try this.

Thanks man, this is working for me :) Hopefully twitch leecher gets fixed tho but im glad I have two apps now
