### ISSUE TITLE
Cannot Authorize

### ISSUE THREAD

**Issue by jpcguy89** [Franiac/TwitchLeecher#84]
Allows me to go to authorization page but either redirect isn't sent or the application isn't handling it.

**Comment by Franiac** [comment]
https://github.com/Franiac/TwitchLeecher#support--issues

Please provide all necessary information, I cannot read minds :)

**Comment by Novynn** [comment]
Coming across this issue as well with a fresh download of 1.3.3.

![image](https://cloud.githubusercontent.com/assets/1468831/21950554/10ba44f4-da61-11e6-81c9-d68d2e0f0da3.png)

It seems to hang on the login action.

**Comment by Franiac** [comment]
I can confirm the issue. Stuck on "Sending". On my end nothing has been changed since the authorization system was introduced in TL. Interestingly enough the url works in Chrome and any other desktop browser (I receive an access token as expected). Could be a Windows or a .NET update that causes trouble here. Needs investigation, but so far I do not have any clue what's going wrong.

**Comment by Franiac** [comment]
So, I tried Chrome, Firefox and Opera and the authorization system works. Now guess what browser does not work... yea... Edge. I get an error dialog from Twitch:

"Oops! We encountered an unexpected error logging you in. Please try again."

This dialog is just not shown in TL, because I deactivated JavaScript error popups. Now TL uses a web browser control from .NET framework and that again uses the Edge browser engine in the background. If Edge does not work, TL does not work.

I guess this all is either a Microsoft or a Twitch problem. I suggest you to be patient and just try again tomorrow.

**Comment by hankshirley** [comment]
I am having the same issue... Otherwise working well though.

**Comment by Franiac** [comment]
I now even tried to switch the browser control in TL to Awesomnium (Chrome based browser). Did not do the trick. Edge worked today again. But as soon as I try to run the authorization process in any embedded browser control, Twitch does not redirect to the needed page. I still think it is a Twitch error. The redirect has to be initiated by the Twitch server and this does not happen.

Any advice is appreciated but there is actually nothing I can do about this right now.

**Comment by snmr1345** [comment]
So I managed to get the auth token response in my browser by right clicking on your in app browser, creating a shortcut, running it and logging in.  My twitch account is authorized now but I don't know where to put the auth token in your config...or if doing it this way is even possible.

**Comment by hankshirley** [comment]
snmr1345, would you mind explaining what you did with the auth token? I would also like to be able to use this aspect of the program.

**Comment by Novynn** [comment]
`%appdata%\Twitch Leecher\runtime.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<RuntimeData>
  <Authorization>
    <AccessToken>Put Token Here</AccessToken>
  </Authorization>
</RuntimeData>
```

**Comment by hankshirley** [comment]
Excellent! Got it working as well... Thank you, Novynn!

**Comment by leimmia** [comment]
how can i edit that? I can't find it <%appdata%\Twitch Leecher\runtime.xml>

**Comment by Franiac** [comment]
Ok guys, I realized that Twitch introduced a new dropdown box for the registered application where the developer has to set an "Application Category". Mine was not set to anything because when I registered Twitch Leecher, the dropdown box was simply not there yet. Now I have set a value and suddenly I could authorize Twitch Leecher again.

Can you please confirm that it works again, thanks!

**Comment by snmr1345** [comment]
I revoked and re-authorized, worked correctly.

**Comment by tripppnn** [comment]
Does anyone know why when I try verifying my account, it doesn’t even let me press the authorize button? It just does nothing, stuck and dont know what to do
