### ISSUE TITLE
Variable startup size / saving window position and size

### ISSUE THREAD

**Issue by Z-brah** [Franiac/TwitchLeecher#88]
Every time i open Leecher, it's looking like this:
![leecher](https://cloud.githubusercontent.com/assets/20454759/22075404/ed03d44e-ddbc-11e6-92e2-77e634b17537.jpg)

At least make it, so it remembers its position and size.
p.s. You are welcome to correct my english. =)

**Comment by Franiac** [comment]
Twitch Leecher is optimized for vertical resolutions >1024. I honestly did not think anyone streaming or watching on Twitch would show up with such a tiny vertical resolution. It has been a very long time since I saw the last 720p display ;)

Take a look from the other side of the medal: If you open up TL on a 1440p screen and the application pops up as a tiny square in the middle of the display I also looks kinda weird.

The solution would be a variable default size for the window related to the vertical resolution. Something like 80% perhaps. That would please all users.

Saving application size and position is on my list since the beginning. The biggest issue is my lack of freetime atm.

**Comment by Franiac** [comment]
🎉
