### ISSUE TITLE
Low visibility on check marks (maybe windows theme-related)

### ISSUE THREAD

**Issue by w4hnsinn** [Franiac/TwitchLeecher#89]
See screenshot from Preferences menu: http://i.imgur.com/BepxnHo.jpg
As you can(not) see, this box is checked - but the mark is barely visible.  This is the case for all check marks in Twitch Leecher (all versions, up to and including latest 1.3.4), not just the ones in Preferences.

- I am using a custom Windows7 theme, that may play into this
- The text color in the input fields below (e.g. "Temporary Folder") are fine though.

//edit: I forgot to add that the text on download progress bars (i.e. the actual percentage number) is also somewhat difficult to see for me, as it's black on dark blue; see screenshot: http://i.imgur.com/IQlt6n5.jpg

**Comment by Franiac** [comment]
Well, the checkbox and the progressbar background are the only two things that are changable by a windows theme. I could overwrite the theme like I did with any other control like the buttons and the textboxes. But this is not related only to TL. Every other program that uses unthemed Win 32 API controls will render your checkboxes like in your screenshots (white font on white background). The theme you use does not seem to be thought through very well in terms of foreground/background relationships. I do not treat this as a bug, but an indicator that I should overwrite all controls so that users cannot mess with the visuals of TL.

**Comment by Franiac** [comment]
🎉
