### ISSUE TITLE
Authorize Twitch Account issues

### ISSUE THREAD

**Issue by w4hnsinn** [Franiac/TwitchLeecher#90]
Issue 1) 
I wasn't sure whether I had to re-authorize with the new version (1.3.4), because clicking on the button in the top menu bar ("Authorize Twitch Account...") does not give any indication whether the program already possesses a working token or not.
(I had been using previous versions, so I probably should have assumed that it does, but an indication would be nice regardless).

Issue 2)
Since I was unsure, I wanted to make sure and authorize (again). So, upon attempting to "Connect with Twitch" and entering my login details, I get an error message:
"Access Token ... could not be verified! Authorization aborted!"
(login credentials are correct, Ive just logged out and back in with them on the actual twitch site)

See screenshot: http://i.imgur.com/womz2eF.jpg

Also, doing this has effectively broken any possibly existing previous auth token: "This video is sub-only".
So I cannot dl sub-only video at the moment.
//edit: Just to confirm, I've just rolled back to **v1.3.3** and authorization works correctly there.

**Comment by Franiac** [comment]
The authorize button in the headline will change to a check mark on a lime green background if TL is successfully authorized.

I can confirm that authorization is currently not working. Due to a switch from API version 3 to 5, the result gets parsed in a wrong way. I will investigate later and release a fixed version 1.3.5 of TL asap! Thanks for the info!

**Comment by Franiac** [comment]
Fixed
