### ISSUE TITLE
Microsoft SmartScreen blocks v1.3.6

### ISSUE THREAD

**Issue by a-rose** [Franiac/TwitchLeecher#94]
Hi,

I tried updating to v1.3.6 but I get a security warning that reads something like "Microsoft SmartScreen blocked this app". I tried x86 and x64, same result.
v1.3.5 re-installed fine.

**Comment by Franiac** [comment]
Well, TL is not signed since a .NET certificate is roughly 1000€ a year and I surely do not want to pay for that on my own. That could be a reason. SmartScreen in my opinion is a giant pile of shite and comes along with many false positives. You can install TL 1.3.6 anyway (ignoring SmartScreen). Since TL is free and open source, it would be hard for me to implement malware into it.
I have tested the installer on multiple PCs, some with and some without SmartScreen and so far have not encountered any problems. Make sure you download the installer here from GitHub and you are fine.

**Comment by a-rose** [comment]
Yup I'm aware of the costs, I'm just reporting the issue because it is the first version where the problem has occured.
Keep up the good work :)

**Comment by Franiac** [comment]
The thing is: look at the history of the installer project. since version 1.1 there are no changes to it except the new guids for the product code. so now i am thinking "what exactly should i investigate if i have nothing to investigate". the 1.3.5 and 1.3.6 installer are EXACTLY the same. so code-wise i cannot review something I might have done wrong, unfortunately.
but here is something you could do and maybe we can get something out of it: please check the windows event log (category "Application"). if smartscreen denies the installer, maybe it logs the reason for that in the event log.
other than that i really do not know how to either reproduce or further investigate the issue. maybe there are more people showing up in the future providing some hints. but at least i now know that there may be a problem and i definitely keep that in mind.

**Comment by a-rose** [comment]
Good idea, but I too was unable to reproduce my own issue ! Here's a recap:

- Up until yesterday I was running v1.2.4 (I'm not sure about the .4 but it was definitely 1.2.x)
- I tried upgrading straight to 1.3.6 and got the warning
- I upgraded to 1.3.5 instead without any problem.
- I can now upgrade to 1.3.6, the SmartScreen warning doesn't appear anymore.

Since the 1.2.x installer doesn't seem to be available anymore, I can't confirm the issue is only when upgrading 1.2.4 => 1.3.6, but whatever; I should have upgraded long ago 😆

**Comment by Franiac** [comment]
Ok, thanks for the info. 1.2.4 never existed, 1.2.3 was the last 1.2.x version. I delete the old installers from GitHub because they do not work anyway anymore. Even TL <1.3.5 do not work due to the API changes so I could get rid of those, too. I just keep them online for people to review the changes.

As for the issue: Well, I think in this case it is ok to say "yea, then fuck it and move on" 😈
