### ISSUE TITLE
Non-partner streams not showing quality options available in web browser

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#97]
Is there a glitch with Twitch's new API? Non-partner streams such as https://www.twitch.tv/videos/118394290 and https://www.twitch.tv/videos/117244645 don't get quality options in Twitch Leecher. But they have quality options in a web browser. 

Previously for non-partners, TL showed all options, though lower resolutions would list as 0x0. Youtube-dl still shows all options when entering the older URL https://www.twitch.tv/JessyQuil/v/117244645. (I can change the caster's name to nonsense and the link still works, even in youtube-dl.)

Youtube-dl downloads at 1.5Mbit max and doesn't permit timecodes though.

Would simply re-accepting the old URL work? I'd love to download non-partner streams with quality options in TL again.

**Comment by Franiac** [comment]
I know about this. Since Twitch switched to V5 all kind of nonsense is going on. Up until they switched, non-subs did not have the lower resolutions available. my older streams from a couple weeks ago still only show source in the API response whereas the newer ones show something like this with the 0x0:

`  "fps": {
    "audio_only": 0,
    "chunked": 29.9507130417012,
    "high": 29.950140966043,
    "low": 29.950140966043,
    "medium": 29.950140966043,
    "mobile": 29.950140966043
  },
  "resolutions": {
    "chunked": "1280x720",
    "high": "0x0",
    "low": "0x0",
    "medium": "0x0",
    "mobile": "0x0"
  },`

So the first thing is: You were not able for a very long time that you could download non-sub VODs in lower resolutions anyway.

I have checked in the browser what resolutions are behind the names:

Source -> well source...
High -> 1280x720
Medium -> 852x480
Low -> 640x360
Mobile -> 400x226

Now we have 2 options:

1. I check for 0x0 and replace those with the above resolution so that TL shows something usable
2. I leave it as it is and throw away the 0x0 nonsense like it was a few weeks ago

I personally prefer option 2 because anything below 1280x720 is nothing but eye-hurting. So I do not really understand why you would want to download such a pixel mess anyway if you can have the better material. What is your usecase? I am just interested.

As for the urls: I suppose that Twitch will disable the old endpoints with /v/[id] in the near future as they are already redirecting to the new ones. And if you navigate through the website you always get the new url format, so there is no need to provide support to the old one anymore.

**Comment by tezJR** [comment]
My usecase is that an ISP data cap means I have to choose streams and resolutions. (And I follow some retro gamers, so I don't really need Source.) 

I'm not sure I understand correctly. Non-partners could always get lower res if there was enough transcoding power available, and they expanded it to many more in September. And I could download the lower les streams with TL. They showed as 0x0, but that wasn't problematic because I knew what they looked like in the browser.

**Comment by Franiac** [comment]
I'll see what I can do. It is problematic, though. I do not know if I am building my logic upon a bug of Twitch. I do not suppose the 0x0 thing is intentional. So TL might again break if this weird behavior changes in a unforseeable way.

**Comment by tezJR** [comment]
Understood and thank you! (If it's not etiquette to thank a person here, let me know.)

**Comment by Franiac** [comment]
why should thanking somebody be bad etiquette? if there are places where this applies, i don't want to be there... so thank you for thanking me :P
